origin_ui/origin.go

Cleanup linter failures in origin_ui

---

cmd/origin_serve.go
origin_ui/origin.go

This implements the admin flow; the admin inputs a code printed out in the terminal into the browser to login then the user (now admin) can reset their password.

Finish implementation of the init login flow

---

cmd/director_serve.go
director/advertise.go

- Check HTTP response code from topology and fail as appropriate.
- Improve error messages coming from OSDF failures.  Was helpful in understanding a local misconfiguration.
- Switch to the common Gin configuration.  Enables prometheus and shares startup code with the origin.
- Add simple signal handling code so a Ctrl+C will cause the director to exit.  Useful for CLI debugging.

Various Director cleanups

---

images/supervisord/pelican_director_serve.conf

Turn off director's autostart to control behavior through entrypoint script

Turn off autostart for director daemon

---

cmd/namespace_client.go
config/init_server_creds.go
namespace-registry/client_commands.go
namespace-registry/registry-db.go
namespace-registry/registry.go

One thing I'd like close review of is the fact that I don't validate the token at the registry against a whitelist of issuers because I'm not sure where such a whitelist would come from. AFAIK, the issuer isn't something that gets stored in the pubkeys that are looked up at the registry.

Add deletion authorization

---

origin_ui/origin.go
origin_ui/src/Dockerfile
origin_ui/src/app/(dashboard)/Sidebar.tsx
origin_ui/src/app/(dashboard)/layout.tsx
origin_ui/src/app/(dashboard)/page.tsx
origin_ui/src/app/globals.css
origin_ui/src/app/initialization/code/CodeInput.tsx
origin_ui/src/app/initialization/code/LoadingButton.tsx
origin_ui/src/app/initialization/code/page.tsx
origin_ui/src/app/initialization/layout.tsx
origin_ui/src/app/initialization/password/PasswordInput.tsx
origin_ui/src/app/initialization/password/page.tsx
origin_ui/src/app/layout.tsx
origin_ui/src/app/page.module.css
origin_ui/src/components/graphs/LineGraph.tsx
origin_ui/src/components/graphs/RateGraph.tsx
origin_ui/src/components/graphs/prometheus.tsx
origin_ui/src/components/layout/Header.tsx
origin_ui/src/components/progress-pager.tsx
origin_ui/src/package-lock.json
origin_ui/src/package.json
origin_ui/src/public/theme.tsx

Adds Copyright info to the Typescript pages
Redirects root to /view
Adds some basic graphs to the initial view on login with xrootd data

UI updates

---

director/redirect.go

If a client presents a token in the original query, we should reflect the token into the redirect as well.  This allows HTTP clients to authenticate at the next cache or origin (as the HTTP spec mandates dropping the `Authorization` header on redirect).
Fixes #44

Include token in redirect

---

images/Dockerfile

Going to go ahead and bypass restrictions to get this merged and moving -- this is a follow-up from a PR that was merged previously and is needed for the registry containers to work properly.

Copy all supervisord confs into image

---

.github/workflows/test.yml

Testing on a different branch to avoid inundating subcribers with messages as testing must be done on a PR

Code comparison with base branch

---

config/config.go

Another thing I happened to notice while scanning through some files.

Remove redundant viper call

---

.github/workflows/publish-dev-container.yml
images/dev-config.yaml
images/dev.Dockerfile

99% of the work is courtesy @jhiemstrawisc and his Dockerfile.
Draft for now well I figure out why I can't run Goreleaser, everything else works as expected. 
Closes #88.

Add development Dockerfile

---

client/director.go
client/director_test.go
director/redirect.go
director/redirect_test.go
go.mod
go.sum
origin_ui/advertise.go

This is a port of PR #178. Creating a new PR was simpler route to fix the rebase.

Give the Director the ability to detect version mismatches

---

.gitignore
generate/param_generator.go

Added generation of a json file version of the yaml file for Cannon's use for the parameters page on the website.

Json generation

---

cmd/plugin_stage.go
docs/parameters.yaml

Kept them all named StagePlugin but changed the token one to be just Plugin.Token since future plugins might have a token as well.

Added the StagePlugin.* params to the param table

---

images/Dockerfile
images/dev.Dockerfile

Added an install of xrdcl-http to the two dev-images
Closes #307

Updated the docker images to include xrdcl-http

---

docs/parameters.yaml
generate/param_generator.go
xrootd/authorization.go
xrootd/authorization_test.go
xrootd/resources/scitokens.cfg
xrootd/resources/test-scitokens-monitoring.cfg
xrootd/xrootd_config.go

A note -- I tried but failed to figure out how to use `mapstructure` to get a clean unmarshal of the data from our config. To get this moving, I just grabbed the values manually.
Closes issue #96

Auto-configure origin issuer access

---

origin_ui/src/components/graphs/Graph.tsx

- Catches and displays errors for graph queries
- The uncaught errors prevented refresh to that is fixed as well
- Close #276

Graph Robustness #276

---

Makefile

Update so that this works with USE_DOCKER=1

Add go generate step to make file

---

docs/pages/_meta.json
docs/pages/parameters.mdx

Add Parameters page and order/name docs

---

cmd/namespace_registry_serve.go

Code cleanup in serveNamespaceRegistry

---

cmd/namespace_registry_serve.go

Reverts PelicanPlatform/pelican#341 Merge was done incorrectly, only the first of the two commits was merged in. Reverting to attempt to fix it.

Revert "Code cleanup in serveNamespaceRegistry"

---

cmd/namespace_registry_serve.go

These are the same commits that cleaned up the namespace registry code previously, just cherry-picked onto a new branch after the revert.
Hopefully it can be a quick approval and merge process.

Namespace registry serve cleanup

---

cmd/namespace_client.go
cmd/namespace_registry_test.go
cmd/origin_token_test.go
config/config.go
config/init_server_creds.go
director/authentication.go
director/director_api.go
director/origin_api_test.go
director/redirect_test.go
docs/parameters.yaml
origin_ui/origin_test.go
origin_ui/register_origin_test.go
web_ui/prometheus_test.go
xrootd/authorization.go

Refactor init_server_cred to be more clear on their usage

---

images/dev.Dockerfile
origin_ui/src/package.json

Updated dev image to have a later version of nodejs in order to run make web-build properly

Adjusted dev.Dockerfile to run make web-build properly

---

tests/citests.sh

Update integration test file

---

origin_ui/src/app/(dashboard)/config/page.tsx
origin_ui/src/app/(dashboard)/page.tsx
origin_ui/src/components/FederationOverview.tsx

- Implements Federation overview which provides a series of links to all Federation components
- Quiet Failure
Closes #221

Federation Overview #221

---

images/dev.Dockerfile

Need these in dev.Dockerfile for the tests to work.

Add test dependencies to dev.Dockerfile for PR #419

---

images/Dockerfile

- Did a quick grep and didn't see any other instances
- origin_ui/src -> web_ui/frontend

Update Web UI src code location

---

director/director_api.go
director/redirect_test.go

Refactor director SD tests and add test for duplicated origins

---

director/origin_monitor.go
origin_ui/self_monitor.go
utils/test_file_transfers.go
utils/test_file_transfers_utils.go
xrootd/origin_test.go

Refactor file transfer tests into a utility class

---

docs/parameters.yaml
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

Adding dir listing capability to Pelican Origins

---

cmd/namespace_registry_serve.go
config/mkdirall.go
config/resources/osdf.yaml
director/advertise.go
director/advertise_test.go
docs/parameters.yaml
namespace_registry/client_commands_test.go
namespace_registry/registry.go
namespace_registry/registry_db.go
namespace_registry/registry_db_test.go
utils/web_utils.go

I still need to sort out how this will play with the key chaining PR. Let's get that merged first.

Make the registry aware of topology

---

SECURITY.md

Since we're dealing with data, we should have some information about how community/federation members can report any security concerns they might have.

Add draft of SECURITY.md

---

cmd/director_serve.go
config/config.go

This reverts commit 1313facfe832d168fc3c4b2c7397fd07ffd035af, reversing changes made to 87b5a42e7fbb1d13f36eaf38dd9c4c37546d7e69.

Revert "Merge pull request #500 from turetske/pelican-authfile-fix"

---

cmd/registry.go
cmd/registry_client.go
cmd/registry_serve.go
cmd/root.go
namespaces/namespaces.go
registry/client_commands.go
registry/client_commands_test.go
registry/registry.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_ui.go
registry/registry_ui_test.go
server_ui/register_namespace.go
server_ui/register_namespace_test.go

Rename `namespace_registry` to `registry`

---

cmd/plugin.go

Additionally, ensure we fsync the final output file when we're finished.
Fixes #519
Fixes #528

Truncate the plugin output file as soon as possible

---

server_ui/register_namespace_test.go

Create `tempDir` for all config files to avoid file not found in test

---

.github/workflows/publish-container.yml
.github/workflows/publish-dev-container.yml
.github/workflows/release.yml

Only build and publish containers as well as releasing on tags >=`7.0.0` in GHA

---

xrootd/authorization_test.go

Adds a unit test for xrootd origin authfile generation.
Close #452

Added tests of generated authfiles for xrootd origins

---

web_ui/authentication.go
web_ui/frontend/app/(login)/components/CodeInput.tsx
web_ui/frontend/app/(login)/initialization/code/page.tsx
web_ui/frontend/app/(login)/initialization/password/page.tsx
web_ui/frontend/app/(login)/login/page.tsx
web_ui/ui_test.go

Login fixes

---

launchers/launcher.go

Move log for origin to the conditional block

---

xrootd/resources/xrootd-cache.cfg

Do not turn on http.trace all for the cache: it logs sensitive information

---

.github/workflows/publish-container.yml
images/Dockerfile

[For Pelican Issue #681](https://github.com/PelicanPlatform/pelican/issues/681)

Remove --snapshot tag from goreleaser command in Dockerfile

---

config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
server_ui/register_namespace.go

Add config param to change storage server registration retry delay

---

registry/registry_db.go

Fix bad topology reload interval in Registry

---

registry/registry_db.go
registry/registry_db_test.go
registry/registry_ui.go
registry/registry_ui_test.go
registry/registry_validation.go
web_ui/authentication.go

Closes #611 
Current test coverage for `registry_ui` is 71%, was 30%

Improve test coverage for various registry UI API functions and bug fixes along the way

---

director/origin_monitor.go
metrics/director.go

Rename director metric label and metric help text

---

registry/registry_db_test.go
registry/registry_validation.go
registry/registry_validation_test.go
test_utils/utils.go
test_utils/utils_test.go

Skip key chain check for caches

---

docs/pages/_meta.json
docs/pages/prometheus.mdx

Add docs to Prometheus metrics

---

docs/parameters.yaml

Just figured that I put something in the `parameters.yaml` that never get implemented. So just to remove it to not to cause confusion. The issue to implement them is here #676

Remove param docs that are not implemented

---

cmd/plugin.go

Changes include:
1. A recovery function that will catch any panics from stashPluginMain, this will attempt to write out a classad output file and exit
2. If we fail to create the classad outfile, we have an exit code of 3 to indicate that the problem is the creation of the file
3. If we fail to initialize our config, we also write classad output and exit
4. New function that can be used to write our output and exit

Stash_plugin produce classad output in more cases

---

.github/workflows/pre-release.yml

Proof that it works: https://github.com/CannonLock/pelican/actions/runs/7803311293/job/21282808963
I had to move the git tag reset to after the commit, not the actual file change.

Move the tag update

---

config/resources/defaults.yaml
docs/parameters.yaml
origin_ui/self_monitor.go
param/parameters.go
param/parameters_struct.go

Add knob to self test frequency

---

images/Dockerfile
images/dev.Dockerfile

For PR #771 due to possible bootstrapping issue

Update go versions in Dockerfiles to 1.21

---

config/resources/defaults.yaml
docs/parameters.yaml
go.mod
go.sum
param/parameters.go
param/parameters_struct.go
web_ui/authentication.go
web_ui/ui_test.go

Closes #711 
To test, build locally and run your any of your Pelican server and go to `https://<hostname>:<port>/view/login/index.html`
Hit `Confirm` button without typing any username. If you hit it slowly (not double click), then you should get 400 error. If you double-click or triple click, then you should get 429 error indicating too many requests.

Add rate-limiter to the login endpoint

---

images/Dockerfile

Fixing problems with the goreleaser fix from pr #684, since it didn't resolve the problem in Issue #681.

Fix Dockerfile goreleaser version fix for Issue #681

---

registry/registry.go

Fixes #514 
Easy test is to run `pelican namespace register --prefix <>` and make sure you got 200 as expected. Or you may run `--prefix` with a bad namespace to see if it returns error.

Remove nested gin status code writer in `cliRegisterNamespace`

---

cmd/main_test.go

Rename not rebuild binary for alias test

---

images/Dockerfile
images/dev.Dockerfile

The goal here is to get LotMan staged into the prod/dev containers.

Stage lotman

---

.goreleaser.yml

Implement @haoming29's suggestion.

Set prerelease as true

---

config/logging.go
config/logging_test.go

Per request from @matyasselmeci - if there's any token in the log message, redact its signature.

Redact tokens from the xrootd output

---

classads/classads.go
client/handle_http.go
cmd/plugin.go

All changes fix issues listed in #808

Cleanup scheme for ft plugin output

---

web_ui/ui_unix.go
web_ui/ui_unix_test.go

Fixes #857 
Comes with test to cover read-only file for the user admin password

Fix permission error in reloading the authdb

---

cmd/plugin.go
cmd/plugin_test.go

The test for StashPluginMain() now utilizes fed in a box and can successfully download a file. Also added unit test for the WriteOutfile function.

Expanded unit tests for plugin

---

director/director.go
director/redirect.go
registry/registry.go
registry/registry_ui.go

Always log 500 error in web handlers

---

director/redirect.go
xrootd/origin_test.go

Add Metalink for redirect to origin

---

config/config.go

Fixed incorecctly named Xrootd.Location - now Xrootd.RunLocation

---

director/origin_api.go
director/redirect.go
director/redirect_test.go
go.mod
origin_ui/origin_api.go
registry/registry.go
token/token_verify.go
token/token_verify_test.go
web_ui/authorization.go

Closes #559 and #572 
This PR is built upon #844. Open a draft PR as a placeholder for now. This should be ready once #844 is merged in.

Replace ad-hoc token verification logic by token.Verify

---

web_ui/authorization.go
web_ui/prometheus_test.go
web_ui/ui.go
xrootd/resources/xrootd-origin.cfg

Fixes #911 
**Note**: this PR is based on #931

Fix xrootd not collecting metrics with `pelican` binary

---

images/Dockerfile
images/dev.Dockerfile

Hash external repository to invalidate build cache when there's an update

---

.github/workflows/build-prod-container.yml

Removed android files to free disc space

Updating GitHub Actions to deal with size issues

---

config/config.go

Redirect logging location reminder to stderr

---

server_utils/server_utils.go

More detailed error message at `WaitUntilWorking` not working

---

registry/registry_ui.go

As @williamnswanson reported. When registering a namespace prefix that's existed in the topology, the user gets a `400` error with `{"error":{}}` which doesn't help them understand what's going on. This is due to the bug where `error` object was directly passed to `gin.H` instead of calling the `Error()` method to get the string representation of the error.
This PR overhauls all the APIs under registry and revise the way they return the error and ensure no empty error object will be returned.

Fix invalid error message type as server response

---

registry/registry_db.go
registry/registry_ui.go
web_ui/frontend/app/api/docs/pelican-swagger.yaml

List namespace topology through UI

---

web_ui/frontend/app/cache/layout.tsx
web_ui/frontend/app/cache/page.tsx
web_ui/frontend/app/config/page.tsx
web_ui/frontend/app/origin/page.tsx
web_ui/frontend/components/DataExportTable.tsx
web_ui/frontend/components/FederationOverview.tsx
web_ui/frontend/components/StatusBox.tsx
web_ui/frontend/components/graphs/Drawer.tsx
web_ui/frontend/components/graphs/Graph.tsx
web_ui/frontend/components/graphs/LineGraph.tsx
web_ui/frontend/components/graphs/RateGraph.tsx
web_ui/frontend/components/graphs/prometheus.tsx

- Add Cache webpage with Storage Metrics
- Refactor graph components
- Refactor Data Exports and Status
- Refactor Origin and Cache page grid order

Add Cache Webpage

---

cmd/plugin.go

Protocol version added to plugin -classad output

---

web_ui/frontend/app/cache/layout.tsx
web_ui/frontend/app/cache/page.tsx

- Remove merge error
- Remove Data Exports

Cache Updates

---

docs/pages/install/docker.mdx
docs/pages/serving_an_origin.mdx

Revise documentation on running Pelican servers in docker container

---

web_ui/frontend/components/Cell.tsx
web_ui/frontend/components/DataExportTable.tsx

Fix styling issues with Firefox

---

docs/pages/serving_an_origin.mdx
docs/parameters.yaml

Update origin documentation, including first pass at S3 config

---

director/director.go
metrics/director.go

Add Prometheus metric for number of advertisement the director receives

---

images/Dockerfile

Add `sssd` user to `osdf-origin` image

---

docs/parameters.yaml
launchers/launcher.go
param/parameters.go
param/parameters_struct.go
web_ui/authentication.go
web_ui/authentication_test.go
web_ui/frontend/app/(login)/login/page.tsx
web_ui/frontend/components/Namespace/DirectorCard.tsx

Enable OAuth for the director

---

.github/workflows/test.yml
local_cache/cache_linux_test.go
local_cache/cache_test.go

closes #1174 #1151 
Downgrading OSX Runner to fix tests

Lower macos version for now to fix failing tests

---

registry/registry_ui.go
server_structs/registry.go

Fixes #1194 
Also added back the description for the fields (that are unintentionally removed during previous merge)

Fix wrong type for Institution registration field in the registry 

---

director/director_api.go
director/director_api_test.go
director/director_ui.go
director/director_ui_test.go
swagger/pelican-swagger.yaml

Add namespaces to director UI server list API

---

web_ui/frontend/app/cache/page.tsx
web_ui/frontend/app/origin/page.tsx
web_ui/frontend/components/DataExportTable.tsx

- Add data export card with finish flow UI
- Adds endpoint permissions view
- Adds pagination for large amount of exports

Add Data Export Card

---

director/cache_ads_test.go
director/director_api.go
director/origin_api_test.go
launchers/director_serve.go
metrics/director.go

Add metrics to monitor director ttl cache and maps

---

origin/reg_status.go

Fixes #1229 
@CannonLock requested your review since you have the frontend set up to check this. Even with the fix, it takes ~1 min for the value to be updated unfortunately.

Fix origin registration status not updated

---

web_ui/prometheus.go

Fixes #1211 
According to [pprof](https://pkg.go.dev/net/http/pprof), we have one constantly increased goroutine, `utils.LaunchPeriodicWriteCABundle`. This function launches a goroutine to periodically reload the CA, and one instance is in Prometheus: https://github.com/PelicanPlatform/pelican/blob/ed756db5445eb724974f9636680a0903d814e718/web_ui/prometheus.go#L188-L193
However, the wrapper of this function, [‎configDirectorPromScraper](https://github.com/PelicanPlatform/pelican/blob/ed756db5445eb724974f9636680a0903d814e718/web_ui/prometheus.go#L727), was called in a loop that runs to update the token the director generated to access origin/cache's metrics: https://github.com/PelicanPlatform/pelican/blob/ed756db5445eb724974f9636680a0903d814e718/web_ui/prometheus.go#L664-L671
Consequently, …

Fix "memory leak" at the director

---

launchers/cache_serve.go
launchers/launcher.go

Removed extra advertise in CacheServeFinish, now only advertises in the launcher's PeriodicAdvertise
closes #1189

Fixed Cache shutting down if advertisement fails

---

cmd/plugin.go

Add 'pelican' to SupportedMethods list

---

cache/cache.go
cache/cache_api.go
cache/cache_api_test.go
cache/self_monitor.go
client/fed_test.go
cmd/fed_serve_cache_test.go
config/config.go
fed_test_utils/fed.go

Fixes #1259 and #1262 
A brief analysis of the cause is in #1281 
@turetske we want this to be backported to 7.8 to stop the error messages in the ITB cache

Fix cache self-test failure

---

origin/self_monitor.go
server_utils/server_utils.go
xrootd/authorization.go
xrootd/resources/test-scitokens-monitoring.cfg

Fix issuer for self-monitoring and scitokens issuer name

---

web_ui/ui.go
web_ui/ui_test.go

Closes #1235 
To test, run your director server, login to web UI, then go to `/api/v1.0/prometheus/query?query=gin_requests_total` and you should be able to see the aggregated time series where the `path` label has values ended with `/:xxx`

Aggregate gin routes for Prometheus metrics

---

director/advertise_test.go
director/director.go
director/director_test.go
director/resources/mock_topology.json

Reduce number of caches in `Link` header on director cache redirects to 6

---

images/Dockerfile
images/dev.Dockerfile

This should be patched into 7.8
Closes #1316

Add xrootd-multiuser dependency to container Dockerfiles

---

registry/custom_reg_fields.go
registry/custom_reg_fields_test.go

Check uniqueness of option names for custom registration fields

---

client/handle_http.go

Fix bug w/ client not working for WithToken option

---

client/fed_test.go

We ran into a bug where the WithToken transfer option was not working as it should. When set, the token was getting overriden and we were getting unexpected errors. This tests the fix that was made and ensures the WithToken works for uploads and downloads.

Unit test for testing WithToken option

---

web_ui/frontend/components/layout/Sidebar/SpeedDial.tsx

Add link to OpenAPI page on the UI

---

docs/parameters.yaml

In the descriptions of the Xrootd logging configuration, I included the values that are accepted. This was requested by Brian Lin.

Added XrootD logging accepted values to param

---

web_ui/frontend/components/Namespace/CardList.tsx
web_ui/frontend/helpers/useFuse.tsx
web_ui/frontend/package-lock.json
web_ui/frontend/package.json

Adds fuzzy/intelligent searching to the card list and the useFuse hook for fuzzy searching in the future. The cardlist is used in a couple places such as the director and the registry to display those respective components.
Closes #1069

Issue 1069

---

director/cache_ads.go
director/cache_ads_test.go
director/director.go
director/director_api.go
director/director_ui.go
director/director_ui_test.go
director/monitor.go
director/sort_test.go
swagger/pelican-swagger.yaml

Update `/director_ui/server` response and fixed director health status being `Unknown`

---

client/director.go
client/fed_test.go
director/director.go

Update Director responses and client handling

---

client/handle_http.go
local_cache/cache_test.go

This originally comes from PR #1354 
Closes Issue #1352

Bug fix for '+' in NEAREST_CACHE -- New PR

---

github_scripts/osx_install.sh
images/Dockerfile
images/dev.Dockerfile

The updates come with `ls` functionality in S3 and authorization bearer token support in HTTP.
Closes #1408

Update XRootD S3/HTTP plugins to v0.1.3 in containers

---

docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
web_ui/pprof.go
web_ui/ui.go

Closes #1441 
The path to pprof will be at `/api/v1.0/debug/pprof/`, which requires you login with admin permission to view

Add pprof endpoints

---

config/resources/defaults.yaml
director/cache_ads.go
director/director.go
director/director_api.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go

Fix deadlock in `recordAd` and `LaunchTTLCache` and add support to turn off `stat`

---

web_ui/ui.go

This PR addresses issue #1472.

Use client IP in Gin Logger 

---

cmd/registry_client.go
launcher_utils/register_namespace.go
launcher_utils/register_namespace_test.go
registry/client_commands.go
registry/client_commands_test.go
registry/registry.go

Allow registering site name as part of the auto-registration process

---

config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
server_utils/server_utils.go
server_utils/server_utils_test.go

Make server startup timeout configurable

---

client/handle_http.go

Previously, job completion was only checked whenever there were zero pending results left for the client; this was incorrect as the pending results could come from multiple different jobs.
If the jobs completed quickly enough for results to pile up, the client would stall and never return because it incorrectly thought it had active jobs.  Stall was observed by NRAO which had hundreds of files transferred by the plugin (each as a separate job).
[It's not clear how to write a reliable regression test for this one - it's a logic issue that triggered under high concurrency]

Check for job completion after every result

---

config/config.go
config/config_test.go

Given consistent (but infrequent) metadata lookup errors on NRP, this retries the metadata lookup after a few seconds.
This will still trigger a retry on metadata failures but hopefully will save a few stageouts.
Includes unit test.

Retry metadata lookup

---

docs/public/origin-dashboard-template.json

This PR addresses issue #1527. I have modified the existing template with a new version that I have worked on during my fellowship.

Use new Grafana dashboard

---

web_ui/frontend/next.config.js
web_ui/frontend/package-lock.json
web_ui/frontend/package.json

Add reporting script so that we can make sure to keep the bundle sizes minimal. This only activates when explicitly running the script in dev mode.

Add bundle analyzer

---

client/handle_http.go
client/handle_http_test.go

Passed the token to the head request for caches

---

.goreleaser.yml

Bump xrootd-server dependency to 5.7.0

---

web_ui/authentication.go

- Fix mismatch of redirect key

Fix Oauth Redirects to Source

---

web_ui/frontend/app/config/Config.tsx
web_ui/frontend/app/config/components/ConfigDisplay.tsx
web_ui/frontend/app/origin/issuer/Issuer.tsx
web_ui/frontend/app/origin/issuer/page.tsx
web_ui/frontend/components/MarkdownRender.tsx
web_ui/frontend/components/index.ts
web_ui/frontend/components/layout/AuthenticatedContent.tsx
web_ui/frontend/helpers/get.ts

Ran `npm run format:fix` and let prettier fixup the js.
No content changes.

Fixup Prettier errors

---

web_ui/frontend/app/registry/page.tsx
web_ui/frontend/components/Namespace/Card.tsx
web_ui/frontend/components/Namespace/DeniedCard.tsx

This feature enables user to delete their approved namespace in the registry.
Address issue #1593

frontend for deleting register namespace

---

web_ui/frontend/app/registry/page.tsx
web_ui/frontend/components/DataExportTable.tsx

Works in conjunction with https://github.com/PelicanPlatform/pelican/pull/1671 to close https://github.com/PelicanPlatform/pelican/issues/1599

Add / to end of routes so data can be prefetched

---

web_ui/ui.go

Small but fixes Client-Side navigation to make things much more snappy. 
Closes https://github.com/PelicanPlatform/pelican/issues/1583
Closes https://github.com/PelicanPlatform/pelican/issues/1599

Fix mimetypes for web responses

---

github_scripts/osx_install.sh
images/Dockerfile
images/dev.Dockerfile

@turetske, let's patch this one ASAP so we can start updating our S3 endpoints.

Update s3 backend to include new multi_curl handler

---

web_ui/frontend/package-lock.json
web_ui/frontend/package.json

Only a minor update to fix a set of vulnerabilities

Security patch

---

docs/pages/federating-your-data.mdx
docs/pages/install.mdx
docs/pages/install/macos.mdx

@aowen-uwmad, hoping you have time to review these updates for clarity, grammar, etc. I tried to clean up a bit more than was requested in the issues linked below so that I could hit a few things while they were in my context window 😄 
Closes #1535
Closes #1534

Cleanup MacOS installation instructions

---

oa4mp/resources/policies.qdl

Fix testing for overlap bewteen OIDC vs. required groups

---

config/config.go

Fixes #1741: Add `Director.DbLocation` defaults in `SetServerDefaults`

Add Director.DbLocation defaults

---

director/director.go

This PR addresses issue #1742. This a very simple fix but it should fix the bug mentioned in the issue.

Fix cache redirection metric over-collection bug

---

web_ui/frontend/app/director/layout.tsx
web_ui/frontend/app/director/metrics/page.tsx
web_ui/frontend/app/origin/globus/callback/page.tsx
web_ui/frontend/app/origin/globus/page.tsx
web_ui/frontend/app/origin/page.tsx
web_ui/frontend/app/registry/layout.tsx
web_ui/frontend/components/layout/AuthenticatedContent.tsx

- Redirect director metrics if not admin
- Hide navigation options if not admin
- Update AuthenicatedContent to consume static lists to enable easier SSR

Redirect Director Metrics if Not Admin

---

.github/scripts/validate-parameters/main.py
web_ui/frontend/components/configuration/Fields/Field.tsx
web_ui/frontend/components/configuration/Fields/ObjectField/PolicyDefinitionForm.tsx
web_ui/frontend/components/configuration/Fields/ObjectField/index.tsx
web_ui/frontend/components/configuration/Fields/StringSliceField.tsx
web_ui/frontend/components/configuration/Fields/index.ts

- Add Ordering to the StringSliceField
- Add PolicyDefinitions Form

Add PolicyDefinitions UI

---

.github/scripts/validate-defaults/main.py
.github/workflows/validate-parameters.yaml
docs/parameters.yaml

- Check parameters.yaml defaults align with the actual defaults
- Update parameters yaml to pass the test

Add default parameters check

---

web_ui/frontend/components/CardList.tsx
web_ui/frontend/helpers/get.ts

- Order registry by Updated Date
- Increase Card List to length 10
Closes https://github.com/PelicanPlatform/pelican/issues/1821

Card List Updates

---

web_ui/frontend/app/director/components/DirectorDropdown.tsx
web_ui/frontend/components/CapabilitiesDisplay.tsx
web_ui/frontend/components/NamespaceCapabilitiesTable.tsx
web_ui/frontend/helpers/util.ts

- No longer display mis-representative cache capabilities
- Remove Cache capabilities
- Update Namespace Capabilities to list Caches that can host that namespace

Fix Director Capabilities Display

---

images/Dockerfile

Rebase on OSG 24 (#1858)

---

.github/workflows/build-and-test.yml
.github/workflows/test-linux.yml
.github/workflows/test-macos-windows.yml
images/Dockerfile

In addition to motivations listed in #2034, I've taken this opportunity to make the textual definitions for the various testing workflows more similar to each other.

Build and test improvements

---

config/init_server_creds.go
config/init_server_creds_test.go

Remove private keys from in-memory key management when key files are deleted; 
Update comments to accurately reflect the lexicographical sorting order used for selecting the current key (lowest to highest);
Add unit test.
How to test this feature:
1. Assuming you already have one private key. Running Registry, Director, and Origin servers.
2. Add a new .pem key file to your IssuerKeysDirectory
3. Wait for 1 minute
4. Verify the new key is registered in the Registry by accessing `https://<registry-hostname>:<registry-web-port>/api/v1.0/registry/<Namespace>/.well-known/issuer.jwks` or checking Registry DB (there should be two keys, both the old one and the new one)
5. Delete the old key file
6. Wait for 1 minute
7. Verify the old public key gets deleted by accessing …

Remove private keys from in-memory key management when key files are deleted

---

docs/pages/monitoring-pelican-services/prometheus.mdx

Added documentation for `pelican_director_geoip_errors` metric.

Wrote up docs for pelican_director_geoip_errors

---

cache/self_monitor.go

As #1808 states, we'd observed something strange in the relevant functions where a) the file URL generation function could return an empty URL without an associated error and b) that URL file could be successfully cleaned up, but logged in a way where the URL is empty. After closer inspection of these functions, my best bet is that we're running into a case where `url.Parse()` passes on an empty/invalid string and does not produce an error. As [docs for `url.Parse()`](https://pkg.go.dev/net/url#Parse) indicate, the function may not always behave as expected due to "parsing ambiguities".
In addition to tidying up a few other error messages, I believe this makes it much harder for the conditions that caused this errant behavior to exist.

Fix cache self-test error message & prevent file name truncation

---

docs/parameters.yaml

The reviewer should double check that I got these correct -- I tried to determine where each one of these was used, but may have misunderstood some of it.

Update 'componenets' for Monitoring.XXX configs

---

config/config.go
config/mkdirall.go
docs/parameters.yaml
lotman/lotman_linux.go

This builds on the minimal changes in #2001. Let's get that merged first, and any change requests can be rebased here.

Handle `Lotman.LotHome` directory creation/permissions in Pelican

---

docs/pages/faq.mdx

Populating structure of the FAQs

---

web_ui/authentication.go

Figure this is enough time to last you all day, but makes you have to login the next day
@bbockelm Said I could do this awhile ago :)

Extend login cookie to last for 16 hours

---

launchers/launcher.go
metrics/health.go
web_ui/prometheus.go

This PR addresses #1965. This PR integrates Prometheus into the existing component health infrastructure.

Implement Prometheus health 

---

web_ui/frontend/app/director/components/DirectorCard.tsx
web_ui/frontend/app/director/components/DirectorCardList.tsx
web_ui/frontend/app/director/components/DirectorDropdown.tsx

@jhiemstrawisc This will need to make it into a rc. 
@h2zh Quick one that removes the downtime toggles on the director that I missed in the first PR.

Remove downtime toggles on Director

---

web_ui/frontend/app/director/components/DirectorCardList.tsx
web_ui/frontend/app/director/components/NamespaceCardList.tsx
web_ui/frontend/app/settings/api/components/TokenList.tsx
web_ui/frontend/components/CardList.tsx
web_ui/frontend/components/Downtime/DowntimeCardList.tsx
web_ui/frontend/components/Namespace/NamespaceCardList.tsx
web_ui/frontend/components/layout/Navigation/Navigation.tsx
web_ui/frontend/helpers/util.ts

Previously I was converting the incoming object to a string. Issue with this is the object was not deterministic so everytime the data updated React rerendered everything with new state because it thought they were all new objects.

Re-key the card list items

---

web_ui/frontend/app/registry/components/Form.tsx

Add the current user as the default security contact when registering a namespace without a security contact. 
For example it will add their Cilogon sub. For now this is a but useless but it is a start.

Auto add the current user as the security contact in new namespace

---

lotman/lotman_linux.go

While trying to set up Lotman in a production setting, I noticed a regression that caused all lot usage to be attributed to the default lot. After some debugging, I discovered a comment in the Lotman source that handles "directory-based usage updates" that indicated Lotman does not expect to have a trailing '/', but this is exactly how the federation-supplied namespace paths were being initialized in lotman.
I view this more as a Lotman bug, but in the interest of getting this moving I'm trimming the '/' in Pelican for now.

Trim trailing '/' from federation-derived lot paths

---

local_cache/cache_api.go

This PR addresses issues #2413 and #2406. This PR cleans up the local cache run directory after the local cache is killed. This PR also changes the permissions of the startup directory and the socket itself.

Local cache cleanup bug fixes

---

client/handle_http.go

The results channel is not read after the TransferEngine's context has been cancelled.  Any time where we write to the channel, we must have a switch statement and bail if the context has been cancelled.
Fixes a deadlock/hang observed in the wild.

Fix deadlock where `results` channel is not read after cancellation

---

client/fed_long_test.go
client/handle_http.go

This PR addresses issue #2548. This PR allows the client to recursively download to `/dev/null`.

Allow for Client to recursively download to `/dev/null`

---

docs/parameters.yaml
oa4mp/serve.go
web_ui/oauth2_client.go

This PR fixes an issue observed by @williamnswanson. This bug was introduced by the new groups improvements merged in earlier in to the 7.20 release. 
@jhiemstrawisc We will need this in 7.20

Allow for unset issuer group source
