PelicanPlatform/pelican

cmd/origin_serve.go
director/advertise.go
director/cache_ads.go
director/geosort.go
director/redirect.go
director/sort.go
go.mod
go.sum

This is a first draft of the conversion of the Director code into the Pelican CLI.
While it compiles, it's not tested -- just a rote conversion of the existing Python code.  It does include GeoIP lookup and integration with topology.  Currently, the biggest missing piece (beyond testing/debugging) is actually hooking it into the CLI itself.

Add Director capability into the Pelican CLI

---

cmd/origin_serve.go
config/init_server_creds.go
config/resources/defaults.yaml
metrics.go
origin_ui/origin.go
web_ui/ui.go

- Factor out the engine launching code into a common `web_ui` module.
- Fix the generation of the host certificate to use a key compatible with Chrome (issuer key is unchanged).
- Change the Gin engine startup to always run with TLS.

Have UI always use TLS

---

config/init_server_creds.go

XRootD is picky about the generated key being mode 0600; decrease permissions to make it happy.

Do not create key with group read permissions

---

director/sort.go

For the kubernetes deployment of the Director, it would be more convenient to pass the MaxMind key as an environment variable via the sealedSecret mechanism than trying to get the value safely into a configMap.

Allow passing key directly via CL

---

cmd/director_serve.go
cmd/origin_serve.go
config/config.go
config/resources/osdf.yaml
director/advertise.go
director/origin_api.go
director/redirect.go
origin_ui/advertise.go

This draft is the first piece of the periodic advertisement of the origin to the director service.  When complete, it'll contain:
- New APIs in the director for advertising services
- Periodic go routine in the origin code to invoke new APIs
- Bearer token generation / verification for authorizing the advertisement.
Goal is that all origins connecting to the director advertise their capabilities directly (and verified by the namespace registration service) instead of relying on OSG Topology to bootstrap the namespace.

Have origin advertise to the director service

---

.github/workflows/publish-container.yml
cmd/director.go
cmd/director_serve.go
images/Dockerfile
images/supervisord/pelican_director_serve.conf
images/supervisord/supervisord.conf
web_ui/ui.go

A few minor changes -- 
- Handle the case when the required tls key and cert aren't provided by generating them
- Reconnect Director to command line argument that allows setting the webport using the `-p` flag when running `director serve`
- Change binary name in Dockerfile to reflect OSDF defaults
- Add xrootd user to Dockerfile (existence of the user is set as a requirement in the general pelican configuration, although I don't see an immediate reason we need this for the director)
- Run supervisord in daemon mode

Fix director tls

---

cmd/director.go
cmd/director_serve.go
cmd/root.go
config/resources/defaults.yaml
director/redirect.go
images/supervisord/pelican_director_serve.conf

We need a way to redirect xrootd caches to origins, but as of the time of this PR, setting:
`pss.origin <director-domain>:443/api/v1.0/director/origin`
results in xrootd crashing after it's unable to parse the URL. 
This PR adds a command line option to set whether the default behavior is to serve caches or origins. Now a user can run:
`pelican director serve -p 443 -e <origin/cache>`
and the director will select the appropriate default endpoint redirection middleware.
As far as xrootd caches go, this should make it possible to set the `pss.origin` correctly

Add cl flag to make default endpoint serve caches or origins

---

cmd/namespace.go
cmd/namespace_registry.go
config/config.go
config/init_server_creds.go
config/resources/osdf.yaml

This implements small changes to the namespace client to simplify the registration process, including:
- Use federation auto-discovery to find the namespace API endpoint.
- Use the default config file location of the private key.
- Generate the public key in-memory instead of requiring it at the CLI.
Example commands that now work:
```
$ pelican -f osg-htc.org namespace register --prefix /test_bbockelm
```
and
```
$ osdf namespace list
```

Namespace client cleanup

---

errorAccum.go
handle_http.go

The error message 'bad content length' was given when the local copy of a file is larger than the remote server copy when downloading a file. The error message now reads 'Local copy of file is larger than remote copy' which I believe is much clearer. In addition, fixed the bug stating the error is retryable. It no longer states this type of error is retryable. This fixed issue #52 in htcondor/osdf-client

Fix bad error message (bad content length)

---

cmd/origin_serve.go
config/config.go
metrics/health.go
metrics/xrootd_metrics.go
origin_ui/origin.go
web_ui/ui.go

This PR fleshes out a few user interfaces / APIs that should be useful for Cannon to build the initial login page:
- "is authentication initialized?" API (`/api/v1.0/origin-ui/loginInitialized`) returns whether or not the admin password has been set for the origin.
- "whoami" API (`/api/v1.0/origin-ui/whoami`) returns the current login status and username (if applicable)
- Health status API (`/api/v1.0/health`) now reflects the status of the various components.
- Improve the messages printed out to the terminal for the code flow.
This builds on top of #16; that should be merged first.

Additional user interfaces and APIs

---

director.go
director/redirect.go
director_test.go
main.go

This:
1.  Converts the client to look for `X-Pelican-*` instead of `X-Osdf-*`.
2. Has the director always set `X-Pelican-Namespace`, even when the credential generation isn't known.
3. Avoids a panic when the `X-Pelican-Namespace` header is missing.
4. Slightly improves the debugging experience when a panic is raised.

Improve the use of the X-Pelican-* responses

---

.github/workflows/golangci-lint.yml
.golangci.yaml
web_ui/prometheus.go

Go has a reference source code formatting - and the VS code defaults seem to like auto-formatting to it.  We might as well enable it in the linters just to keep things consistent.
Note this disables reporting all linter issues as there's a codebase-wide reformat that should be done as a separate branch once some other pending work lands.

Enable `go fmt` as one of the linters

---

cmd/director.go
cmd/namespace_registry.go
cmd/origin.go
cmd/root.go
go.mod
web_ui/ui.go

When a flag is bound to the viper key (such as binding the `--port` flag object to the `WebPort` key), it's a global.  If you do this multiple times with multiple pointers, only the last one is used.
That means, if we invoke `cmd.Flags().StringP(...)` in multiple sub-commands, only one will actually set `WebPort`.
The solution for this is to create the flag once globally, then add the global object to multiple commands.  Note that I didn't use a parent-level "persistent flag" as that would also make `--port` usage strings appear for the `object` sub-command (which doesn't have an embedded webserver).
Fixes #63.

Create a single `--port` flag object

---

config/init_server_creds.go
director/origin_api.go
go.mod
go.sum

The library we use for JWKs and JWTs has both a v1 and v2 API.  As the various Pelican pieces were independently developed, some modules used V1 and others V2.  This brings up all the code to use V2, dropping V1 as a dependency.
Fixes #61.

Upgrade remainder of the code to lestrrat-go v2

---

namespace-registry/registry-db.go

We talked this morning about config variables that specify "Location" and how they should specify the actual filename. I had previously tried to implement some logic that if a file location was passed such as `/foo/bar/`, the namespace registry would auto create the registry database as `/foo/bar/ns-registry.sqlite`. Instead of fixing the bug in that logic, let's just say whatever is passed should be considered the file name. A side effect of this is that if the user configures `NSRegistryLocation = /foo/bar/`, the file will be created as `/foo/bar/.sqlite` because the code automatically adds a file extension when none is provided and in this case, the actual filename is empty.
This fixes #67

Fix small bug in ns-registry auto creation

---

config/init_server_creds.go
namespace-registry/client_commands.go
namespace-registry/registry.go

There were missing key values in the registry database (like kty, kid, etc) because of the custom structs being used to create the jwks that got stored. By using lestrrat's jwk package, we get those values for free.
One thing to note about the PR is that while the registration pubkey verification dance works when using the client in its current form, this won't work for a jwks with multiple keys in it. I didn't try to tackle that problem in this commit because I'm not sure where those other key pairs are coming from, so I wasn't sure how load them into the key set. 
Fixes #54

Use lestrrat jwks instead of custom structs in NS Registry

---

director.go
director/advertise.go
director_test.go

This fixes up the header generation for the director response.  Now, when I try the command from @jhiemstrawisc in #68, I get the following in the response headers:
```
...
< location: https://dtn-pas.cinc.nrp.internet2.edu:8443/ospool/PROTECTED/justin.hiemstra
< x-pelican-authorization: issuer=https://osg-htc.org/ospool
< x-pelican-namespace: namespace=/ospool/PROTECTED, require-token=true
< x-pelican-token-generation: issuer=https://osg-htc.org/ospool, max-scope-depth=4, strategy=OAuth2
```
Fixes #68

Fix director responses

---

images/Dockerfile

supervisord startup was failing when this was set ... let's revert for now and revisit dropping permissions in the future.
Fixes #90

Remove default user

---

images/supervisord/pelican_registry_serve.conf

This commit adds a supervisord program that allows the container to serve a namespace registry. To serve a namespace registry, launch the container with the argument `registry_serve`.

Add registry to container

---

cmd/namespace_registry_serve.go

All of my local testing disguised the fact that the registry didn't create its own signing key when it's started (I just happened to have one in the right spot from previous testing).
The changes I've made will create the private key `issuer.jwk` in the default location for `IssuerKey`, and this is primarily used by the registry to handle the key signing challenge on namespace registration. Tested by hand and it works locally.

Create a privkey for registry

---

namespace-registry/registry.go

This forbids a few potentially-confusing prefixes, including:
- Any path component starting with '.'
- The root prefix '/'
- /pelican, /api, /view
Fixes #53

Add simple verification to namespace registration

---

config/config.go
namespace-registry/registry.go

Also going to bypass restrictions on this one. A few of the configuration variables were named without taking into account nesting, and this was causing problems in the namespace registry deployment when registering with identity.

Fix naming of oidc config vars

---

images/supervisord/pelican_director_serve.conf
images/supervisord/pelican_registry_serve.conf

Wasn't sure from the docs whether I needed the `env` prefix here, and I guessed wrong the first time.

Remove redundant env prefix

---

config/config.go
config/resources/defaults.yaml
director.go
handle_http.go
main_test.go
namespaces/namespaces.go
namespaces/namespaces_test.go

This commit creates one common create transport function for https based writes, rather than having duplicating code. In addition, the timeouts for these transports are created in defaults.yaml so they can be changed easily. 
Other changes include:
1. Adding TLSSkipVerify to client's director query, which is a useful feature for testing for us when using a running director locally.
2. Found a bug in namespaces.go, where NamespaceURL was used when TopologyNamespaceURL should be used instead.

Using common transport for https based writes

---

origin_ui/src/app/(dashboard)/page.tsx
origin_ui/src/components/graphs/LineGraph.tsx
origin_ui/src/components/graphs/RateGraph.tsx
origin_ui/src/components/graphs/prometheus.tsx
origin_ui/src/helpers/login.tsx

- Adds a redirect for non auth'd users
- Refines the UI in the first 10 minutes where data is not yet populated
-

UI changes

---

handle_http.go

I found a bug with setting up TLSSkipVerify from the common transports. Looks like I put checking for that within the creation of the transport that only happens once. Therefore, if the transport is created, then it will never check again if TLSSkipVerify is set. From running my own tests by hand it seems to be working now.

Fix bug with common transport TLSSkipVerify

---

director/origin_api.go
director/redirect.go
namespace-registry/registry-db.go
namespace-registry/registry.go
origin_ui/advertise.go

I'm leaving this in draft mode for the moment because I haven't gotten through the whole process yet, and I suspect there are still bugs.
The part I'm getting stuck on is in `director/origin_api.go`, line 115 in my changed files where we do `ar.Get(ctx, issuer_url)`. It looks like under the hood, `ar.Get` instantiates an `http.Client` and tries to get the `issuer.jwks` from the `issuer_url`. Of course, testing locally I don't have a valid TLS setup, and I can't figure out how to bypass that issue through the jwk library because the x509 certificate is obviously not signed by a known authority.
Otherwise, a few bugs I think I've nailed out:
1. The origin now sends a token to the director for verification (before no token was sent)
2. There were issues with the ttlcache mutex in …

Send token and namespace ad to director

---

director/origin_api.go
director/redirect_test.go

This is response to the issue [here](https://github.com/PelicanPlatform/pelican/issues/81) - note that after discussion with Brian, we determined the last bullet point (Query the director for an object within the new origin's namespace. Ensure the response includes the newly registered origin) should be a separate issue and is not covered in this pull request.
* Created redirect_test.go to test code in direct/redirect.go
* Tests the director registration with both a valid and invalid token
* Also added an interface called NameSpaceCache in order to mock the cache in tests in origina_api.go

Added redirect_test.go

---

.pre-commit-config.yaml

This introduces pre-commit configurations to run golangci before any commits occur.  Goal is to decrease the number of "fixup linter" type commit messages in the repo.
Fixes #83

Add pre-commit hooks for the repo

---

.golangci.yaml

After timeouts at 2m, we're going to try bumping the linter timeout to 3m
Fixes issue #136

Bump linter timeout to 3m

---

director.go
handle_http.go
namespace-registry/client_commands.go
origin_ui/advertise.go

There were a few spots in newer code looking for the TLSSkipVerify on its own. Changed them over to use the common GetTransport function. I also had to rename the function to be capital letters since that's how Go reads functions from other packages.

Switched over remaining usage of http.Client to use common transport

---

.github/workflows/test.yml

- will comment on a pull request with current test coverage
- only runs on the ubuntu-latest test to avoid duplicates
- uses a third-party tool to add a message to a pull request called sticky-pull-request-comment whose source is located at https://github.com/marocchino/sticky-pull-request-comment

Added code coverage to github actions workflow

---

.github/workflows/test.yml

Removing the commenting code, at least until we decide on a fix so it's no longer causing a block.

Remove commenting code that causes errors when using a fork

---

config/init_server_creds.go
config/privs.go

Found an issue when trying to get a private key when running my unit test locally on my windows machine. From investigating found that privs.go only worked with uid's and gid's which is only functional with mac and linux. I modified a few things to work with windows SID's as well by checking what os is being ran. I ran my tests after modifying on both my linux container and locally on windows and it seems to work now. I also had to change around a few lines in GeneratePrivateKey since it calls a "chown" which is not a windows command.

Fixed Generate Private Key Problems in Windows

---

.github/workflows/codeql-analysis.yml

The CodeQL GHA previously ran in the `osdf-client` repo, and this PR gets it running in Pelican. The only fundamental change is that I've also set up CodeQL to run on release branches, eg v7.0.x.
Closes issue #84

Revive codeql

---

.github/workflows/test.yml

This now has code coverage information in the GitHub action summary metrics. Go the the pull request test workflow and click `summary` to see the results.

Updated test.yml to attach code coverage to the action summary

---

docs/parameters.yaml

Far from exhaustive, but these are the parameters I know I've used throughout code I've meddled in.

Add a variety of configurable parameters to docs

---

director/cache_ads.go
director/cache_ads_test.go

Previously, when two namespaces like /chtc and /chtc/PUBLIC existed in the cache, the matchPrefix function wound up matching whichever happened to be read first. Now it matches against the longest prefix, so a request for path /chtc/PUBLIC/foo/bar will always match /chtc/PUBLIC.
Closes issue #140

Match ns prefix by longest match, not first match

---

config/encrypted.go

Appears to have been a debug message that escaped into the wild.

Remove errant stdout message

---

origin_ui/origin_test.go

This is a unit test for the origin login api's. The tests have been ran on both windows and in a linux container and shows everything running successfully. This effectively tests:
1. Code-based login when no password is set
2. Password reset API
3. Password-based login API
4. "whoami" API

Test Origin Login APIs

---

config/config.go

That I'm aware of, nobody has encountered this bug yet. I just happened to notice it when reading through the file. I'm 99% sure the previous code was incorrect and would result in autodiscovery not being run if only the "DirectorUrl" was set, resulting in no valid NamespaceUrl.

Fix federation auto-discovery bug

---

handle_http.go

- The webdav library used does not do bearer token authorization so removed the directory existence check
This is dealing with issue #25

Removed `isDir` from handle_http.go

---

cmd/origin.go
cmd/origin_token.go
cmd/origin_token_test.go
go.mod

This PR exposes the ability for a user at an origin to create tokens for testing. It can be accessed via `pelican origin token create`. There are several claims that all default tokens will posses, namely iat, exp, nbf, iss, and jti. These can be overridden by passing them specifically to the tool as claims.
By passing a profile with the --profile flag, the tool will provide information about additional claims that are needed by the profile. NOTE: it only provides information about required values that ARE NOT auto-generated!
The lifetime and private-key flags can be used to set the token lifetime (in seconds) and the private signing key, respectively.
Next up is to create a CLI for verifying a provided token against a specific profile. While the basic infrastructure was set up for that …

Expose CLI for creating tokens

---

director/origin_api_test.go
director/redirect_test.go

Tests tokens with various scopes for the `VerifyAdvertiseToken` function
Tests the string created from `GetIssuerURL`
Tests token creation using the `CreateAdvertiseToken` function
Also adjusts the mocked cache in redirect_test.go to be used by both test files

Added tests for the three functions in origin_api.go

---

client/director.go
client/handle_http.go
config/config.go
namespace-registry/client_commands.go
origin_ui/advertise.go

Fixed an issue with common transports for some reason not getting correct value from defaults.yaml. Also addressed issue moving the common transports to the config sub-module and allowed initClient and initServer to recreate the common transport object. In addition, moved the TLSSkipVerify to only run when setupTransfer is called again (either first time `GetTransfer()` is called or `initClient()` or `initServer()` is called).

Pelican transport fixes and generated after configs

---

config/config.go
director/redirect_test.go
web_ui/prometheus.go
web_ui/prometheus_test.go

This addresses issue Issue #6 and puts the accessing of prometheus metrics behind the federation or origin token.

Put prometheus metrics behind federation/origin token

---

cmd/origin_serve_test.go
cmd/resources/xrootd.cfg

Additionally, add a simple regression test to ensure that the template at least compiles.

Fix template rendering failure

---

cmd/origin_serve_test.go
config/config.go
docs/parameters.yaml
origin_ui/origin.go
web_ui/README.md
web_ui/authorization.go
web_ui/prometheus.go
web_ui/prometheus_test.go

-- Refactored origin and federation check into their own module to be used by other functions
-- Added a README explaining which tokens is it okay to sign with the Federation and which aren't
-- Added a check for the authorization via the login cookie

Added check of cookie login for prometheus

---

client/main.go
client/main_test.go

This PR brings a PR from OSDF-Client to Pelican that handles parsing token names with `.`s in their name. For more information, see: https://github.com/htcondor/osdf-client/pull/87

Port OSDF-Client PR #87 to Pelican

---

origin_ui/src/app/(dashboard)/page.tsx
origin_ui/src/components/graphs/Graph.tsx
origin_ui/src/components/graphs/LineGraph.tsx
origin_ui/src/components/graphs/RateGraph.tsx
origin_ui/src/components/graphs/prometheus.tsx
origin_ui/src/components/layout/Drawer.tsx
origin_ui/src/package-lock.json
origin_ui/src/package.json

- Create setting drawer
- Create input to manipulate Prometheus rate graph - Provide sensible defaults

Create new graph components

---

cmd/plugin_stage.go

@jhiemstrawisc these are the typos we found way back when I was playing around with plugin staging. Realizing we never made these typos a permanent fix.

fixed typos within plugin_stage.go

---

cmd/main.go
cmd/main_test.go
cmd/root.go

According to issue #150 , we want to expose `--version` flag for pelican-client and display the version/build info to the user in a similar behavior as `stashcp` did. This PR addressed this issue but in a bit hacky way under various constraints from cobra.
* In order for all commands and subcommands to respond to a flag, we need to add logic to each individual command/subcommand in cobra. This can be done in a batch using `PersistentPreRun` [function](https://github.com/spf13/cobra/blob/main/site/content/user_guide.md#prerun-and-postrun-hooks), to add one handler for the root command and its child subcommands. However, cobra will not execute `PersistentPreRun` function for the command if the `Run` function of the command is not defined. See issue …

Add --version flag to pelican-client

---

.github/workflows/test.yml

* Replace `--rm-dist` by `--clean` in goreleaser command in Test CI as it's deprecated.
* Use `build` command with `--single-target` for Windows and Mac runners to only build one executable for their platform, keeping Ubuntu runner to build everything for platform coverage
Testing:
Reference GHA job: https://github.com/Techming/pelican/actions/runs/6485485842 See "Run GoReleaser for Non-Ubuntu" or "Run GoReleaser for Ubuntu" step log for details.
* Visually confirmed that the deprecated warning sign disappeared with this PR
* Visually confirmed that Mac OS and Windows runners will only build one artifact while Ubuntu runner will build all.

Update goreleaser command in test CI and enable --single-target

---

.github/workflows/test.yml

According to #209 , we want to add cache for tests CI to improve running time of tests. This PR added cache for both Go modules and Next.js/npm packages. Since setup-go GHA [already has caching function built-in since V4](https://github.com/actions/setup-go#v4), we only need to modify the sequence where we checkout the code. For node packages, [following the guide from Next.js](https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions), I added cache for it.

Add cache for Go modules and npm packages

---

director/redirect.go
director/redirect_test.go

Starting to move this patch into the 7.1.x branch

Fix director authz

---

director/redirect.go
director/redirect_test.go

I noticed while testing XRootD's ability to use a Pelican director as its redirector (defined via the `pss.origin` directive), that XRootD will take a token passed to it via an Authorization header and convert it directly into an authz URL query that gets passed to the director. For the director to return a valid redirect URL, the "Bearer " prefix must be stripped.

Strip "Bearer " from authz query and header if they're present

---

cmd/main.go
cmd/main_test.go
cmd/object_copy.go

This PR closes #124 where it supports `.exe` extension from windows and different uppercase/lowercase for the executable name and is able to distinguish between different executable alias.

Fix executable alias not working on Windows

---

config/config.go

We haven't used an HTCondor collector for some time now. Let's finish removing it.

Remove the collector from federation discovery

---

cmd/director.go
cmd/namespace_registry.go
cmd/origin.go
cmd/origin_serve.go
cmd/root.go
config/config.go

In some remote environments like HTCondor, we can't always assume that the user has a configured $HOME directory. Previously, this was enforced in both the root command and in the `main` package's chain of `init()` functions, preventing stash_plugin from running in HTCondor even though no $HOME directory is needed in that case.
This makes an unset $HOME a non-fatal warning at the root command level, and moves `InitServer()` into a pre-run for each cobra command that is actually responsible for starting a server. In the cases of servers, we do still require $HOME.
Closes issue #226

Update Pelican to not require a set $HOME in some configurations

---

go.mod
metrics/health.go

* Added a new Prometheus Gauge metric `last_update_component_health_status` with labels `component`, `status`, `message`, similar to existing in-memory data structure, and the value is Unix time in micro seconds
* This function is tested visually/using integrate test by calling `/query` API and verify the metric value can be distinguished between very small updates. Unit test for this function is a bit tricky and redundant given that 1. we can't mock the time value effectively. 2.Prometheus testutil only supports compare the result from a collector against an io stream but the times never match

Integrate component health status to Prometheus

---

config/config.go

This fix should close #229 by preventing TLSSkipVerify param from being overwritten by the CA cert param.

Prevent TLSSkipVerify from being overwritten

---

origin_ui/advertise.go

In #173, we want to monitor the advertising to federation status for origin. I added the "federation" component to the health status monitoring and mark it as "critical" if there's an error advertising to the federation, or "ok" otherwise.
I can confirm from visually testing the added metric with the origin UI running and that the federation status is returned by the `/health` api.
This PR did not come with a unit test as it requires us to mock "PeriodicAdvertiseOrigin" function but I can't do it without refactoring code and structure of `advertise.go` in origin_ui package, by adding interface and struct in that file, which will also cause refactors of code who imports those functions. Enable mocking functions in `advertise.go` can be a separate issue if we do want to improve test …

Federation component health status

---

cmd/config_mgr.go
cmd/object_copy.go
cmd/plugin.go
cmd/root.go
config/config.go
config/config_test.go
xrootd/authorization_test.go

Fixes issues with the 3 config files used with Pelican: defaults.yaml, osdf.yaml, and pelican.yaml. Before this fix there was a bit of a mess of where the configs are set up with viper. This fix moves InitConfig to config.go and sets up all the config files in the priority they need to be with pelican.yaml taking higher precedence than defaults.yaml. Also fixed issue in object_copy.go with some weird issues with the -d flag. Only need to check for the -d flag with stashcp since it does not go through root, any other modes are checked within root/initconfig and trigger debug mode.

Cleanup of pelican config files

---

.gitignore

This should now ignore the docs/parameters.json

Fixed mispelled filename in .gitignore file

---

cmd/director_serve.go
cmd/namespace_registry_serve.go
director/authentication.go
director/director_api.go
director/redirect.go

* Generate private/public key pair for director at the director's start
* Expose director's discovery url at `<directorURL>/.well-known/pelican-configuration` which contains the `jwks_uri` attribute for accessing the public keyset
* Expose director's public keyset uri at `<directorURL>/.well-known/public_signing_key.jwks`
* Added an API in `director_api.go` `LoadDirectorPublicKey` to access director's public key from anywhere in the application

Expose director's public key via Open ID style URLs

---

cmd/origin_serve.go
config/config.go

Just some replacements to viper.Get* that didn't occur before. Should be a very quick review.

Replaced some remaining viper.Get* calls with the appropriate param.GetString() call

---

director/advertise.go
director/advertise_test.go

Since the bug isn't super easy to catch in the diff, it was coming from:
```
cacheNS := NamespaceAd{}
cacheNS.Path = ns.Path
cacheNS.RequireToken = ns.UseTokenOnRead
cacheAdMap[cacheAd] = append(cacheAdMap[cacheAd], cacheNS)
```
I'm not sure why I ever did this because the appended value (`cacheNS`) should have just been `nsAd` like it is for the similar origin logic. I'll probably figure it out around the same time I figure out how many licks it takes to get to the center of a tootsie pop.
Once we're comfortable merging this, I'll patch it into 7.1 as this constitutes a bugfix.
Fixes issue #258

Fix broken Director auth headers and add regression test

---

cmd/main.go
cmd/object_copy.go
config/config.go
config/resources/defaults.yaml
docs/parameters.yaml

Sets the default log level to `ErrorLevel` within `defaults.yaml`. The user is now able to modify their config file and override the default to whatever log level they would like. In addition, the -d flag functionality should remain the same and override whatever config is set. Also found a problem in `object_copy.go` which this does not work if the binary is named stashcp, should work now. Fixed some noticed snake case variable names floating around too and decided to fix them.

Make default log level part of pelican config

---

tests/citests.sh

This adds two test cases, when `HOME` is not set and when `HOME` is set to a non-writable dir and ensures we exit(0) from `stash_plugin -classad` for both those cases. Meant to mimic an environment like HTCondor.

Improve test of stash_plugin to be more like HTCSS environment

---

images/dev.Dockerfile

Hot fix for the latest build-dev-container GHA failure on main branch as `scitokens-oauth2-server` base image isn't built for arm platform. Fix by specifying `--platform` on base image as `amd64`.

Fix dev container build failure by specify base image platform

---

.goreleaser.yml

Fixes only some of the issues with Pelican RPMs. The issues fixed are that the LICENSE and the README were world writable, so I made them read only. There was a typo with the homepage, and the license was changed to an accepted format for Apache 2.0.

Fix some issues with Pelican RPMs

---

.github/workflows/golangci-lint.yml
generate/next_generator.go
generate/param_generator.go
param/param.go

According to #72, we want to move the "placeholder file" creation for GHA linter from the GHA to `go:generate`. I created a `generator/next_generator.go` to programmatically generate path and placeholder file to `origin_ui/src/out/placeholder`, removed the same logic in GHA, and updated the command that calls `go:generate`
However, this change, as well as #268 makes `generate` and `param` package grow out of its original scope. I suggest that we move the `main` function from `param_generator.go` to a separate file like `main.go` and potentially move the call to `go:generate` from `param/param.go` to `generate/main.go` so that the logic is more clear as we are not just generating files for params.

Move npm path placeholder creation from GHA to Go

---

client/handle_http.go

Fixed issue when Content-Length header was ommitted when chunk encoding is enabled. Now if the original response size is not found it will do a HEAD request to get the proper `Content-Length`. The progress bars should always have the proper total now. 
Fixes issue #201

Fixed issues with Progress Bars

---

director/advertise.go
director/advertise_test.go
director/cache_ads.go
director/origin_api.go
director/redirect.go
director/redirect_test.go
origin_ui/advertise.go

This should close #285 where we need origin's web engine URL as part of the origin advertisement so that the director can talk to origin's web api.
For reviewer, I did check that `AdvertiseOrigin()` now carries the correct port number for `WebURl`, which is `Server.Port`. I didn't add test to it because I can't get away from making errors in generating ad token in the test case and I think until we can mock the token generation function, we can't really test `AdvertiseOrigin()`.

Add Web URL in origin's advertisement message

---

origin_ui/src/app/globals.css
origin_ui/src/components/StatusBox.tsx

- Remove some padding
- More robust to errors parsing response
- Status components are no longer hardcoded
- Added message view
- Closes #232

Upgrade status component

---

origin_ui/origin.go

This fixes the issue with `/api/v1.0/config` not checking `User` field in ctx and allows unauthed user to access config.

Fix bypassed authentication for /config API

---

.goreleaser.yml

This adds compat symlinks for `/usr/bin/stashcp`, `/usr/bin/osdf`, and `condor-stash-plugin` to use the `pelican` binary isntead, and a condor configuration for enabling the condor-stash-plugin.  This allows pelican to replace the old "stashcp" and "condor-stash-plugin" RPMs.
The appropriate `obsoletes` (`replaces` for Deb) and `provides` clauses are included, with the caveat that pelican-osdf-compat provides version "7" of the packages it's replacing, as opposed to whatever specific version the pelican-osdf-compat package itself is.  This is because GoReleaser doesn't expand templates inside `replaces` and `provides` lists so the value has to be hardcoded.
Deb, RPM, and APK use different syntax for specifying versions clauses:
- APK does not use `replaces` (`provides` is sufficient for …

 Add pelican-osdf-compat package

---

director/cache_ads.go
director/cache_ads_test.go
director/redirect.go

The Director had a null dereference bug that occurred when it tried to find ads for non-existent namespace prefixes. This commit fixes the bug, adds a regression test to catch similar bugs in the future, and re-orders the error reporting to the client in the event that it tries to get something from a non-existent namespace.

Fix null dereference bug in Director

---

cmd/director_serve.go
cmd/namespace_registry_serve.go
cmd/origin_serve.go
config/init_server_creds.go
director/director_api.go
director/redirect.go
director/redirect_test.go
web_ui/prometheus.go
web_ui/ui.go

Since our current Prometheus setup has a fixed datastore location, it is very difficult to get more than one instance of service (director/origin/registry) to run Prometheus at the same time. To test this PR locally, you need to have some local patches to make it work. Here is how you can do it:
First, make sure you specify the director's URL:
```yaml
Federation:
DirectorUrl: "https://localhost:8888"
```
Next, in `web_ui/prometheus.go`, `ConfigureEmbeddedPrometheus()` around line 218, you want to uncomment the code:
```go
if isDirector {
err := os.MkdirAll("/var/lib/pelican/director-monitoring/data", 0750)
if err != nil {
return errors.New("Failure when creating a directory for the monitoring data")
}
cfg.serverStoragePath = "/var/lib/pelican/director-monitoring/data"
} else { …
```

Director Prometheus scraper of origins' metrics

---

cmd/root.go
config/config.go
docs/parameters.yaml

Added an option for Pelican logs to output to a specified file rather than stdout. This is used with either the `-l` flag or by specifying Logging.File within the Pelican config.

Made Pelican logging able to output to file

---

config/config_test.go

The tests are no longer affected by changes in the user's Pelican.yaml

Fix problems with config_test.go

---

cmd/origin_token.go
config/init_server_creds.go
director/director_api.go
director/origin_api.go
director/origin_api_test.go
director/redirect_test.go
go.mod
go.sum
namespace-registry/client_commands.go
origin_ui/origin.go
origin_ui/register_origin.go
origin_ui/register_origin_test.go
origin_ui/self_monitor.go
web_ui/authorization.go
web_ui/prometheus.go
web_ui/prometheus_test.go

Close #314 
`getOriginJWK` is a confusing name because of the overloaded `origin` term. This changes that function to `getServerJWK`. If that's not an acceptable name, vscode makes refactoring very simple, so it can also be something like `getIssuerJWK` or `getHostJWK`.

Renamed getOriginJWK to getServerJWK

---

config/init_server_creds.go
docs/parameters.yaml

Closes #303 
With this PR merged, we should be consistently using Server.Hostname from parameters at all places. This PR also changes the param type of hostname from url to string, and noted the default value will be `os.Hostname()`
Note to the reviewer. I've tested that by changing the `Server.Hostname` from its default to `localhost`, remove existing CA file, spinning up an origin to let it generate new CA, and copy the CA file to `/etc/pelican/certificates/tlsca.crt`, and re-run the origin, the self-test works as expected.

Use Server.Hostname than os.Hostname() in generating CA

---

cmd/director.go
cmd/director_serve.go
cmd/namespace_registry.go
cmd/namespace_registry_serve.go
cmd/origin_serve.go
config/config.go
config/config_default.go
config/config_linux.go
config/config_test.go
config/init_server_creds.go
docs/parameters.yaml
go.sum

The big part of this PR is standardizing some of how servers are initialized. Importantly, this moves federation discovery and some key creation from the various `*_serve.go` files into `InitServer()`.
In the process of putting this together, I noticed a few other cleanup items. One was changing a parameter.yaml default value and type to match the description. Another was modifying config_test to use `assert.Equal` instead of `assert.True` so that if the test fails, it prints out what the expected and actual values are.

Standardize server init and cleanup a few other small items

---

client/handle_http.go

Fixes issue where if the cache sends a `permission denied` error, the next download tries to utilize the completed bar and panic. Now on failure it calls abort and removes the bar instance.

Fix issue with progress bar panic on download

---

config/config.go
config/config_default.go
config/config_linux.go
config/init_server_creds.go
docs/parameters.yaml

Closes #301 
Since `SciToken` doesn't like self-signed host certificate, we want to always generate our own CA at pelican config directory when there is no host certificate present, so that we can sign our generated host certificate by the certificate and private key of our generated CA.
This PR also introduced more robust checking of required files to set up TLS. It now checks that:
1. A valid TLS host certificate is present (via Server.TLSCertificate)
2. The private key of TLS cert if present (via Server.TLSKey)
3. A valid CA certificate is present (via Server.TLSCACertificateFile)
Or it will generate a new host certificate, and in this process, it will need a CA cert/private key to sign the host certificate (to avoid self-signed host cert). It will check if:
1. A valid TLS CA …

Always generate a CA if no host certificate present

---

config/config.go
config/resources/defaults.yaml
director/director_api.go
director/director_api_test.go
docs/parameters.yaml
origin_ui/origin.go
web_ui/authorization.go
web_ui/prometheus.go
web_ui/prometheus_test.go
web_ui/ui.go

Closes #291 
* Added Bearer authorization to Prometheus `/metrics` endpoint and issue token for the scraper of both director and server itself, with periodic reloading.
* Refactored authorization logic in `web_ui` to make it more flexible, clear, and reusable.
* Changed LoadDirectorPublicKey to return key, not pointer to the key
* Spin up `director` and you should expect `/metrics` requests are all successful, and their frequency should be around 15s.
* Change `Monitoring.TokenExpiresIn` and `Monitoring.TokenRefreshInterval` to smaller value to ensure token refreshment is successful
* Run `director`, `registry` and `origin`. At `origin` end, confirm that its `/metrics` requests are also all successful.
* Go to origin's web APIs and check auth works as expected. i.e. `/api/v1.0/prometheus` …

Add authorization to Prometheus /metrics endpoint

---

cmd/namespace_registry_test.go

Testing the main functionalities of namespace-registry: Adding a namespace (without indentity), listing/getting contents from a namespace, and deleting a namespace.

Unit test for namespace-registry

---

cmd/cache.go
cmd/cache_serve.go
cmd/origin.go
cmd/origin_serve.go
daemon/launch_unix.go
metrics/health.go
metrics/health_test.go
origin_ui/advertise.go
origin_ui/register_origin.go
origin_ui/self_monitor.go

Closes #351 
We want to be more robust in setting component health status. This PR introduces enum for both the health status and the component name to record. Related code are updated to adhere to this new convention.
I manually tested that `SetComponentHealthStatus` work without causing errors at `origin` side where the web ui dashboard can correctly display health status of all existing components, and when there's an error from a component, the health status updates as expected.
For reviewer, I recommend spinning up your `origin` and go to `/view` and check that all status on top right side is expected. You can then turn off your `director` and wait for the next origin advertisement to fail to see if that's correctly displayed.

Introduce enum for health status and component names for SetComponentHealthStatus

---

origin_ui/src/app/(dashboard)/config/page.tsx

- Add strong typing to avoid future bugs
- Add null, string[] and int[] support
Fixes #380

Fix Config Bug

---

.github/workflows/test.yml

Updated the GitHub test workflow to use our linux dev image (so the xrootd e2e test will work). Also updates the image to use a more recent version of nodejs.

Git test action updates

---

config/config.go

Previously, running pelican with `-f foo.com/a/path` would result in DiscoverFederation() trying to get metadata from `foo.com/.well-known/pelican-configuration/a/path` instead of the correct `foo.com/a/path/.well-known/pelican-configuration`. This fixes that.
It also uses the `url.JoinPath()` method for parsing URL paths instead of `path.Join()`. We never really do much with Windows, but if we did, that would prevent federation discovery from working, because it would try to use \ as a path separator in a URL. Whoops.
Closes issue #399

Fix small bugs in DiscoverFederation()

---

xrootd/authorization.go
xrootd/authorization_test.go
xrootd/resources/scitokens.cfg
xrootd/resources/test-scitokens-monitoring.cfg

Close #390 
Scitokens generation will now create a map of issuer urls and add a new base path to an already existing issuer url if it exists rather than adding a new Issuer struct

Fixed scitokens generation bug

---

swagger/pelican-swagger.yaml

Closes #352 
This is a hand-coded Swagger specification of APIs in Pelican servers. For now, I included APIs for authentication and common APIs (/config, /health, etc.)
As a next step, we might want to programmatically generate this spec using annotations on handler functions, and there's existing Go package to handle spec generation for us: [swaggo/swag](https://github.com/swaggo/swag)
If you are using VSCode as your IDE, you can render the Swagger UI from this `.yaml` file by installing the [OpenAPI (Swagger) Editor](https://marketplace.visualstudio.com/items?itemName=42Crunch.vscode-openapi)

Add swagger spec and include auth APIs and common APIs

---

cmd/cache_serve.go
cmd/origin_serve.go
daemon/launch_unix.go
origin_ui/origin_windows.go
xrootd/origin_test.go
xrootd/origin_test_linux.go
xrootd/xrootd_config.go

@turetske - not sure if this is helpful but I was tinkering with testing xrootd while on the airplane and cobbled together this PR.
Now, the tests shouldn't pass for the exact same thing you're struggling with -- waiting on the new release of `scitokens-cpp`.  But perhaps the approach is interesting for you?
One item we'll need to think through: How do we want to approach Mac OS X?  The homebrew-packaged version of XRootD comes without SciTokens, meaning that maintaining a test there would be fairly difficult.

End-to-end test for XRootD

---

metrics/xrootd_metrics.go
metrics/xrootd_metrics_serializer.go
metrics/xrootd_metrics_test.go

Closes #129 
A couple of lingering questions regarding the handler code, which will affect how I write the test code, see `TODO` and other comments in the code:
* Why we want to use SID as user id for u-stream and record it in our sessions cache? `SID` is an `int64` value per xrootd documentation while the `UserID.Id` is a `uint32` value, which can't hold `SID`.
* What `ComputePrefix` function is doing? It looks buggy because it will only return "/" no matter what
Besides, I fixed some bugs in the handler code as I write the tests. See code and comments below for details.
Finally, this PR introduced a considerable amount of code to serialize xrootd monitoring struct as well as adding such structs to our project. For the serializers, they look a bit redundant but I don't think reflection …

Add unit tests to XRootD monitoring handler

---

config/config.go
param/param.go

Fixes #389 
Run `director` `registry` and `origin`, and go to origin's ui `https://localhost:8444/view/config/index.html`
Check that under Origin subheader, the value of `NamespacePrefix` is set to whatever prefix you gave to your origin and registered at registry, say `/origin1`, because this value is being set after `InitServer()` was called.

Always unmarshall config when /config API is called

---

tests/citests.sh

Just figured out the `./stashcp` source wasn't updated and the integration test keeps failing. I thought for stashcp it by default add `stash:///` to the url you provided but turned out you can directly feed `osdf:///` to use the osdf URL

Update integration test file - update stashcp source

---

cmd/cache_serve.go
cmd/director_serve.go
cmd/origin_serve.go
director/cache_ads.go
director/cache_ads_test.go
director/director_api.go
director/origin_api_test.go
metrics/xrootd_metrics.go
xrootd/origin_test_linux.go
xrootd/xrootd_config.go

Closes #330 
The added unit tests to director's `serverAds` cache and `namespaceKeys` cache suggest that expired cache item won't be evicted with existing code, so this PR added `cache.Start()` to all TTL cache instances to ensure they work as expected.
The part I'm not sure about is whether we should call `cache.Stop()` at the shutdown of the program. I called `Stop()` for now but I don't know if this is redundant or not.

Ensure TTL caches evict expired item

---

images/Dockerfile
images/supervisord/pelican_origin_serve.conf

Now our production container can be started with "origin_serve" and the origin supervisord daemon will launch. To make the origin functional, add any origin arguments to the environment variable `OSDF_ORIGIN_ARGS`. For example, to serve an origin on port 8444 that mounts /foo to /namespace/bar in the ITB federation, you'd create the environment variable
```
OSDF_ORIGIN_ARGS="-f https://osg-htc.org/osdf/itb -v /foo:/namespace/bar -p 8444"
```

Add supervisor script to make origins servable

---

director/cache_ads_test.go
director/director_api.go
director/director_api_test.go
director/redirect.go
director/redirect_test.go

Fix #435 
Besides what mentioned in #435, this PR also introduced lock for the map to store cancel functions for direct-based-health-test (`healthTestCancelFuncs`)

Fix racing conditions in various director-related code and tests

---

utils/ca_utils.go
web_ui/prometheus.go
xrootd/xrootd_config.go

Both XRootD and Prometheus can't use our custom transport object, which combines the system CA pool with the custom CA.  This causes various failures unless you disable TLS validation (which we want to avoid doing).
This adds a helper function that periodically (re)creates the CA bundle. These bundles are made available to other functions at runtime.
NOTE: Neither Mac nor Windows have a standard system bundle.  On those platforms, we only create the bundle if the custom CA is present.

Periodically prepare a combined custom + system CA bundle

---

web_ui/frontend/package-lock.json
web_ui/frontend/package.json

Upgrade NextJS to ^14

---

generate/main.go
generate/next_generator.go
generate/param_generator.go
param/param.go

Close #304 
One question for the reviewer is that do we _actually_  want to exclude the generator files for the release? I tried to use `//go:build ignore` in the `generate` package but that will make `go generate` malfunction with missing function import in between Go files.

Refactor `generate` package

---

client/handle_http.go
client/main.go
cmd/object_copy.go

First draft of recursive uploads. This will go through a directory and upload every file to the destination. The only problem is that it will not maintain the same directory structure since I could not find a way to have PUT work with directories.

Implement recursive uploads

---

images/Dockerfile
images/dev.Dockerfile

Fixes #438 
Also fixed the current CI/CD release error with minio RPM missing by changing the package URL to archive with the pinned version.

Arm-compatible Pelican container and fix 404 minio RPM

---

config/config.go
docs/parameters.yaml
namespace_registry/client_commands_test.go
namespace_registry/registry.go
namespace_registry/registry_db.go

Another tool for admins, this PR allows a registry to be run such that it requires key chaining to register a sub/super namespace of an already-registered namespace. For example, if `/foo/bar` is registered, when key chaining is enabled, neither `/foo` nor `/foo/bar/baz` can be registered unless by a key paired with `/foo/bar`. Another example -- if `/foo` and `/foo/bar` are both registered, then we cannot register `/foo/bar/baz` unless the key is also registered to one of the superspace set (`/foo` and `/foo/bar`. 
I think eventually we should enable these types of registrations via tokens as well -- if I own `/foo` and I want to enable Emma to register `/foo/bar`, I should be able to generate a token with the key registered to `/foo` to enable any public key Emma wants to use. Based on …

Enable key chaining to protect super/sub namespaces

---

client/handle_http.go

Recursive download progress bar was panicing and exiting when we did not want it to. This patch is just a band-aid to keep functionality and to stop the panic, but they still do not look pretty when debug logging is enabled.

Fix progress bar for recursive downloads

---

web_ui/frontend/package.json

14.0.4 breaks the website build so lock it to 14.0.3

Lock NextJS to 14.0.3

---

client/handle_http.go
cmd/object_copy.go

The progress bars now appear below the debug log as they are running and are not duplicated. Also, disabled progress bars with specified debug log output. Figured you don't need the bars to be printed to a specific log file.

Fix progress bars w/ recursive uploads and downloads

---

director/director_api.go
director/origin_api.go
go.mod
utils/server_auth.go
utils/server_auth_test.go
web_ui/authentication.go
web_ui/authorization.go
web_ui/prometheus.go
web_ui/prometheus_test.go

Closes #405 
* Refactored out `checkAPIToken` as `CheckAnyAuth` into `utils` package and migrate dependency functions to `utils` as well
* Rename Prometheus token scopes
* Use cache for JWKS

Refactor `checkAPIToken` to be more generic and less verbose

---

.github/workflows/test.yml

Fixes #488 
Basically fix the `hashFiles` timeout error after 120s when doing hashing for Next.js runner cache by excluding `node_modules` from calculating the hash.

Exclude node_modules from calculating Next.js hash in GHA

---

cmd/director_serve.go
config/config.go

Two fixes, one which fixes the xrootd run file locations and one which moves the topology PeriodicReload to be behind the OSDF flag.

Pelican authfile fix

---

cmd/origin.go
cmd/origin_token.go
cmd/origin_token_test.go
utils/token_utils.go
utils/token_utils_test.go

Instead of passing a `claimMap` to create a token, now you can config your token by constructing `TokenConfig` and call `CreateToken` off this instance.
* Replaced `CreateEncodedToken` by `CreateToken`
* Ran regression tests and ensure existing code are not affected

Refactor and move token create logic to utils

---

cmd/registry_client.go
director/origin_api.go
director/origin_api_test.go
director/redirect.go
director/redirect_test.go
registry/client_commands_test.go
registry/registry.go
registry/registry_db.go
registry/registry_db_test.go
server_ui/advertise.go
server_ui/register_namespace.go
server_ui/register_namespace_test.go

This adds a requirement for admin approval before a cache can advertise to the director.
Currently there is no endpoint to approve caches, but the registry database can be altered via sqlite with the following commands after the cache has been created with `pelican cache serve`:
run sqlite
```
.open "/var/lib/pelican/registry.sqlite"
SELECT * FROM namespace;
```
There will be a list of origins and caches that looks like this:
```
id          prefix                pubkey             identity    admin_metadata         
----------  --------------------  -----------------  ----------  -----------------------
1           /caches/f1ec0afbfc09  <key_info>                     {"admin_approved":false}
```
Then run the following with `1` replaced by whatever id is in the id column of the cache you …

Namespace registry admin

---

cmd/main.go
cmd/object_copy.go

This allows us to version the binary by naming it something like <prefix>-7.2.2
Closes #513

Match binary name by prefix, not exact match

---

cmd/director_serve.go
cmd/namespace_registry_serve.go
metrics/health.go
metrics/topology.go
utils/web_utils.go

Closes #482 
Instead of adding # of errors as a separate Prometheus metric, I took advantage of existing component health metric by adding topology as a new component. If we want to look at number of errors (Status.Critical) over time, we should use PromQL to get what we want. Something like `query=count_over_time((pelican_component_health_status{component="topology"}%20==%201)[1h:5m])` which will give you total number of critical status over the period of time.

Add topology component to Prometheus health metric

---

director/director_api.go
director/redirect.go
director/redirect_test.go
web_ui/prometheus.go

Closes #481 
* Spin up your `director` `registry` `origin` and `cache`
* Go to your director's Prometheus query engine endpoint for discovered servers, i.e. `/api/v1.0/prometheus/query?query=up`
* You should be able to see your cache and origin in the list
* Go to an arbitrary metric and both origin and cache shared, say `xrootd_monitoring_packets_received`, i.e. `/api/v1.0/prometheus/query?query=xrootd_monitoring_packets_received`, you should be able to see the metric from both your origin and cache, distinguished by their label.

Include cache in director's service discovery endpoint

---

cmd/director_serve.go

Moved the `director.RegisterDirectorAuth(rootGroup)` `director.RegisterDirectorWebAPI(rootGroup)` before the ShortcutMiddleware Call
This is the last bit to close #300

Match routes before redirect request in director

---

cmd/cache.go
cmd/director.go
cmd/director_serve.go
cmd/namespace_registry.go
cmd/namespace_registry_serve.go
cmd/origin.go
cmd/origin_reset_password_test.go
cmd/origin_serve.go
cmd/registry.go
config/config.go
config/config_test.go
namespace_registry/client_commands_test.go
registry/client_commands_test.go
server_ui/register_namespace_test.go
server_utils/server_struct.go
web_ui/prometheus.go
web_ui/ui.go
web_ui/ui_test.go
xrootd/authorization.go
xrootd/authorization_test.go
xrootd/origin_test.go
xrootd/xrootd_config.go

Closes #501 
Now you can use `config.IsServerEnabled` anywhere in the server code to test if a server is enabled. A private function `setEnabledServer` is called in `initServer()` to indicate which server(s) are enabled.
This would be a necessary step for UI to redirect server web UI user to correct server UI landing page.
This can also be used in #172
When browsing through places where we used ServerType, it seems that we had a `XrootDServer` interface that relies on implementation to tell which server is running. I didn't touch that part of the code in this refactoring but if we want I can remove `GetServerType()` from `XrootDServer` interface and replace existing ones to `config.IsServerEnabled`. I'm fine either way. @turetske

Refactor `config.ServerType` to provide a globally accessible source for server(s) enabled

---

go.mod

Closes #505 
Note that once this PR is merged, someone needs to "push" the change to Go package repository. On the main branch of the central repository (not your fork), run `GOPROXY=proxy.golang.org go list -m github.com/pelicanplatform/pelican@v1.0.4`
This way, we should be able to retract our modules from Go.

Unpublish Go package

---

.goreleaser.yml

stashcache-client was the name of the old Python-based stashcp; have the pelican-osdf-compat package provide and replace that package too, since it's apparently still installed in a few places and we want a smooth upgrade path.

Have pelican-osdf-compat package replace "stashcache-client"

---

cmd/cache_serve.go

Closes #309 
Several things left in this PR compared to what Origin currently has:
* Periodic self tests (unrelated to web_ui stuff directly but is a missing piece still)
* Periodic director tests
* Dedicated frontend for cache (current there's no option as "cache" when selecting the site to go at the frontend)
This PR is useful for making #493 actually work by spinning up the embedded Prometheus instance for cache.

Enable Web UI for cache

---

xrootd/authorization.go
xrootd/xrootd_config.go

When user provide xrootd config files i.e. `authfile` and `scitokens.cfg` by mounting them through docker/kubernetes in read-only mode, there will be a failure in origin/cache at the start, where Pelican will try to change the user group of both files to the daemon name (xrootd in most case), which is not allowed. 
This chmod is redundant as we eventually copy the two files, make some changes, and save them as final files to xrootd run location, so we only need to be able to read those files.

Remove chmod on user-provided xrootd config files

---

cmd/registry_client.go
config/config.go
config/config_test.go
director/origin_api.go
director/origin_api_test.go
director/redirect_test.go
docs/parameters.yaml
registry/client_commands_test.go
server_ui/register_namespace.go
server_ui/register_namespace_test.go

Closes #388 
Per request, `Federation.NamespaceUrl` is preserved but marked as deprecated. User can still use this config but a warning message will should up if `Federation.NamespaceUrl` is used instead of `Federation.RegistryUrl`

Rename `Federation.NamespaceUrl` to `Federation.RegistryUrl`

---

go.mod

I only did it half-right in the previous PR #540 where I created a higher version for go (v.1.0.4) but forget to retract all previous version (v1.0.0-v1.0.3) so that the retract is void. I found this error while already pushed the new 1.0.4 tag.
Added all the previous versions in this PR, I need to build a new tag and push it again. Sorry about adding unhelpful tags to the repo.

Fix error in retracting pkg with not including previous versions

---

images/Dockerfile
images/dev.Dockerfile

Closes #485 
@bbockelm It seems that testing the production container requires supervisord and it can't run without it, but I can confirm that dev container now uses `xrdcl-pelican` plugin. Although I tried to build plugins in a separate stage, the final size of the image is still ~2.3GB. Not sure what's wrong.

Replace `xrd-http` plugin by `xrdcl-pelican` plugin in dev-container

---

cmd/cache.go
cmd/cache_serve.go
cmd/director.go
cmd/director_serve.go
cmd/origin.go
cmd/origin_reset_password_test.go
cmd/origin_serve.go
cmd/registry.go
cmd/registry_serve.go
config/config.go
config/config_test.go
go.mod
registry/client_commands_test.go
server_ui/register_namespace_test.go
server_utils/server_utils.go
utils/ca_utils.go
web_ui/engine_test.go
web_ui/ui.go
web_ui/ui_test.go
xrootd/authorization_test.go
xrootd/origin_test.go
xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

We want to provide for clean updates of the TLS certificate for production services.  This PR does two things:
1.  Makes a copy of the TLS certificates for XRootD, avoiding file permission issues that tend to hit Kubernetes.  Adds a goroutine that periodically updates XRootD's copy of the certificate.  Uses a combination of fsnotify and polling for updates.
2. Using the same update approach, pull in new certificates in the pelican web UI.
Includes unit tests for both items.

Reload TLS certificates as needed

---

director/resources/geoip_overrides.yaml
director/sort.go
director/sort_test.go
docs/parameters.yaml

First and foremost, this allows a director to configure IP blocks that we want to directly map to a lat/long pair. Valid IPs include IPv4 and IPv6, both masked and unmasked. In the event that MaxMind either doesn't contain a coordinate for an IP or we just don't like the coordinate it returns, we can now set where we want a director to think the server is. Note that this affects both servers (origins/caches) as well as clients, because we update server coordinates at ad recording time, and we get client coordinates at redirect time.
One small change is that we now log at the Director when an IP address results in the null coordinate. This should allow us to filter such requests in the logs when we're collecting metrics.
This also fixes another small bug that's been annoying me -- we don't …

Allow GeoIP overrides and fix server geoip randomization

---

registry/registry_db_test.go

With what current registry DB test has, if the local machine timezone is different from UTC, tests will report errors. This PR fixes this issue by convert time to unix time first before making the comparison.

Fix time zone difference in registry DB test

---

cmd/cache.go
cmd/cache_serve.go
cmd/fed.go
cmd/fed_serve_test.go
director/cache_ads_test.go

This cleans up a deadlock in the `pelican cache serve` mode generated in #570 and fixes some race/ordering conditions I spotted which may be causing flakey unit tests also post the #570 merge.

Fixup various cache and testing failures

---

xrootd/authorization.go
xrootd/authorization_test.go

The first commit handles line continuation characters, allowing the current syntax generated by topology to be used.
The second commit ensures we merge in lines that _aren't_ public lines.  This is needed for VOMS/X509-based authentication.
Fixes #567 
Fixes #568

Fixup merging of authfiles

---

launchers/launcher.go

Currently, we can't run any server other than origin as the launcher script will always call `OriginServeFinish` and `LaunchPeriodicAdvertise` which are only for the origin, and calling it for other server will lose any origin-specific config values and will cause program to exit.

Only run Origin start script when it's origin

---

client/main.go

When dostashcpsingle is called and detects a writeback, it will now return the uploaded bytes instead of just an error

Stash_plugin uploads now record bytes transferred

---

cmd/cache_serve.go
launchers/origin_serve.go
origin_ui/advertise.go
server_utils/server_utils.go
web_ui/ui.go
xrootd/authorization.go
xrootd/authorization_test.go
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

To replace existing OSDF caches, which rely on X509 authentication that we don't want to pull into the Pelican codebase, we'll need to merge with their authfiles (which are periodically updated).  This utilizes the Xrootd maintenance routine to regenerate authfiles and scitokens.cfg when an update occurs.
Includes unit tests.
Fixes #562

Regenerate the authfile and scitokens.cfg periodically

---

cmd/cache_serve.go
launchers/origin_serve.go
origin_ui/advertise.go
server_utils/server_utils.go
web_ui/ui.go
xrootd/authorization.go
xrootd/authorization_test.go
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

The INI library always returns a key when there's a lookup -- if the key isn't in the section, the returned object is a valid key with an empty value.  When this empty string was being parsed as JSON, an error was thrown.
Fixed the conditional to check for a non-empty key and added a short unit test.
Note this branch builds on top of #594.
Fixes #601

Correct parsing of scitokens.cfg with empty audience_json value

---

launchers/launcher.go

This re-enables S3 origins, but does not cover any E2E tests. I'm assuming we'll spend a good amount of development time for 7.5 working on all things E2E.

Re-enable S3 Origins

---

registry/registry.go

I believe when I did #175, I changed the value for various device based token flow request, which are just empty string and breaks the flow. Revert back to what they are supposed to be in this PR.

Fix broken namespace registration with device code flow

---

cmd/plugin.go
cmd/plugin_test.go

Stash plugin will now call init-config on startup so it can get the configured timeouts and log levels as well as any other default/environment configuration. Added a unit test to test functionality of stashPluginMain as well as this new fix.

Stash plugin calls init-config & added unit test

---

metrics/xrootd_metrics.go
metrics/xrootd_metrics_test.go

Closes #495 
A note to reviewer: Although this PR implemented the metric for both origins and caches, we won't receive any metrics from cache yet as we don't have web stuff for cache implemented by the time this PR is ready (it's in a separate ticket here #309). 
I think #493 might suffer from this, as we added caches to director's service discovery endpoint but they are essentially "dead" endpoints. Director Prometheus instance might produce a bunch of "false positive" error messages

Add storage volume Prometheus metrics from XRootD monitoring packets

---

cmd/director_serve.go
cmd/fed_serve.go
cmd/main.go
cmd/origin_serve.go
cmd/registry_serve.go
cmd/root.go
launchers/launcher.go
web_ui/ui.go

When an error occurred, ensure we always cancel the context and then wait for cleanup to finish.  Without this PR, we are leaking xrootd processes because neither occurs.
Further, this makes the `/api/v1.0/servers` API always-on to make the test for the web engine functionality more reliably succeed.

Fixes to the shutdown / error sequence

---

registry/registry_ui.go

Current we check if a prefix exists for both create new registration and update existing registration, which is wrong. We should only check when we create.

Only check namespace exists when create

---

registry/registry_db.go
registry/registry_db_test.go
registry/registry_ui.go
registry/registry_ui_test.go
web_ui/authentication.go
web_ui/frontend/app/api/docs/pelican-swagger.yaml
web_ui/oauth2_client.go
web_ui/ui.go

Closes #606 and #591 
* Improve Swagger to include csrf token, query params, RBAC
* Refactor namespace db function to allow generic filtering
* Control ns visibility based on auth status

Add status filter to registry API, improve Swagger docs

---

cmd/registry_client.go
director/origin_api.go
director/origin_api_test.go
director/redirect.go
director/redirect_test.go
registry/client_commands_test.go
registry/registry.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_test.go
server_ui/register_namespace.go
server_ui/register_namespace_test.go

Fixes #566 
See #566 for reasoning behind this implementation.

Roll back registry api from `v2.0` to `v1.0`

---

client/handle_http.go
client/handle_http_test.go
client/main.go
cmd/object_copy.go
cmd/origin.go
cmd/root.go
config/config.go
director/advertise.go
director/cache_ads.go
director/origin_api.go
director/redirect.go
docs/parameters.yaml
origin_ui/advertise.go
param/parameters.go
param/parameters_struct.go
server_ui/advertise.go

Changes made with this PR:
- Client now gets the endpoint for a put request through the director, this endpoint is the origin_url. PUTs now require a running director to work.
- When running origin serve and as a configurable option, you can specify if the origin is writeable (default is true).
- Made a test within handle_http_test.go end-to-end with xrootd, using the federation in a box since now PUTs require a director to be running.
- To remove an import cycle, made the pelican version global through config
Might have missed some other patch work to make everything work properly as well but this is the gist of it

Director advertise origin instead of writebackhost

---

client/director.go
client/director_test.go
client/handle_http.go
client/handle_http_test.go
client/main.go
client/sharing_url.go
cmd/origin.go
config/resources/defaults.yaml
director/advertise.go
director/cache_ads.go
director/origin_api.go
director/redirect.go
director/redirect_test.go
docs/parameters.yaml
origin_ui/advertise.go
param/parameters.go
param/parameters_struct.go

These fixes are for PR #622 which helps reinstate backwards compatibility. Changes include:
- Returning `UploadFile` to its original state
- Running a PUT on the director to get PUT endpoint instead of a GET
- Moved this logic to `client/main.go` when we gather ns info
- Moved the gathering of ns info to a separate function

Fixes to origin/director advertise to client

---

web_ui/frontend/app/config/page.tsx

- Use path base aware link component for page navigation

Fix Config Links

---

client/handle_http.go
client/main.go
cmd/object_get.go
cmd/object_put.go

The command `pelican object get` and `pelican object put` separated out from `pelican object copy`.

`pelican object get` and `pelican object put`

---

generate/param_generator.go

I was having issues with param_generator making param_struct.go have an extra new line at the bottom whenever it was generated. Go-linter does not like this so I have to `git restore` it every time I want to commit. This should fix that (hopefully it's not just me having this issue)

Fixes to how param_struct is generated

---

cmd/main_test.go

Bug where the test changes the client version and never sets it back, causes issues with other tests using a director

Main test now restores current version

---

config/config.go
config/config_test.go
launchers/launcher.go
param/parameters_struct.go
web_ui/frontend/app/(landing)/page.tsx
web_ui/frontend/app/(login)/login/page.tsx
web_ui/frontend/app/api/docs/pelican-swagger.yaml
web_ui/frontend/app/config/page.tsx
web_ui/frontend/components/StatusBox.tsx
web_ui/ui.go

Fixes #588 by renaming the function `EnabledServers` to `GetEnabledServerString`. Preserved the *ServerType.String() function to return the string representation of a single ServerType enum. Added function comment to explain.
* Put `/server` api behind the auth, as well as restructured the return value from array to json object with `{servers: []}`. Updated UI accordingly
* The above change breaks the server self check at launch time, as it depends on `/server` to tell if the web engine is working, so changed that to check `/health` instead
* However, `/health` was used to get the server component health status, so renamed original `/health` endpoint to `/metrics/health` and use `/health` to only provide a public health check  endpoint of web engine.

Improved common Web API endpoint

---

config/resources/defaults.yaml
docs/parameters.yaml
launchers/registry_serve.go
param/parameters.go
param/parameters_struct.go
registry/registry_ui.go
registry/registry_ui_test.go

Fixes #635 and Closes #648 
To test locally, you may use the topology URL which gives valid institution list for OSDF: https://topology.opensciencegrid.org/institution_ids

Take a URL from config value to fetch institution list for Registry 

---

cmd/cache_serve.go
cmd/root.go
director/director_api.go
director/redirect.go
launchers/launcher.go
metrics/xrootd_metrics.go
origin_ui/origin_api.go
param/parameters_struct.go
server_ui/advertise.go
server_utils/server_utils.go
web_ui/prometheus.go
web_ui/ui.go

Fixes #661 
* Fix the issue where Pelican won'y exit main process if error group goroutine returns error, unless an error returns in the main goroutine
* Fix the panic at the director when a cache advertise itself to the director, as we didn't have the case for cache when doing version compatibility check
* Improve logging at program exit to be consistent.
* Improve cache error group, remove duplicated exit handler that `root.go` already had.
~~However, this didn't fix the issue where when we exit the program with `ctrl+c` , xrootd reported error as it treated SIGINT similar as SIGSEGV. We might have to refactor some of the code in `daemon/launch_unix.go`. Created a separate issue for this: #672~~

Exit main process if error group goroutine returns error

---

param/parameters_struct.go
web_ui/frontend/components/graphs/RateGraph.tsx

The latest merge #497 causes linter failure on main branch, due to outdated local branch. This fixes the linter issue.

Fix linter failure on main

---

launchers/launcher.go
xrootd/xrootd_config.go

To specify the local export and namespace prefix when serving an origin, both `Origin.ExportVolume` or a combination of `Xrootd.Mount` and `Origin.NamespacePrefix` are valid options. There was a bug that prevented the origin from spinning up in the case that `Origin.ExportVolume` was not directly specified, or populated via the command line volume mount flag. This fix allows either combination to work.
Closes #621

Fix origin export options to allow Xrootd.Mount/Origin.NamespacePrefix combo

---

.github/workflows/codeql-analysis.yml
.github/workflows/pre-commit-linter.yml
.github/workflows/publish-container.yml
.github/workflows/publish-dev-container.yml
.github/workflows/release.yml
.github/workflows/test.yml

Closes #697 
The warning is still there because the `pre-commit` action hasn't updated the dependent action they are using but there's a PR for that already, so it should be updated soon: https://github.com/pre-commit/action/pull/188

Update various GHA actions

---

client/handle_http.go

Within the auto-unpacking code, the dest was reading as just "." so I changed it to recognize that is the current working directory and change it manually

Fixed issue: auto-unpacking failing if dest is "."

---

cmd/plugin.go

Now the plugin can move files just like handle_http does, starts up many workers and has a producer/consumer setup to download files in parallel.

Have pelican plugin move files in parallel

---

.pre-commit-config.yaml
cmd/cache_serve.go
daemon/launch.go
daemon/launch_unix.go
github_scripts/osx_install.sh
github_scripts/pelican_protocol.patch
launchers/origin_serve.go
xrootd/launch.go
xrootd/origin_test.go
xrootd/resources/xrootd-cache.cfg
xrootd/xrootd_config.go

This enables the `pelican://` protocol for the cache's `pss.origin` setting.
Contains four parts:
- Setting the `pss.origin` xrootd configuration variable directly
- To avoid having to touch system files, creating a separate client plugins directory and point the cache at the new directory via environment variable.
- Extending the "launcher" setup to take environment variable overrides
- Updating the OSX GitHub builder scripts to patch in `pelican://` support for XRootD.  For Linux, I assume we'll pull in the patched version via the OSG build.

Use `pelican://` protocol for pss.origin setting in the cache

---

client/handle_http_test.go
cmd/fed_serve_test.go
cmd/object_get_put_test.go
config/resources/defaults.yaml
config/resources/osdf.yaml
director/origin_api.go
director/origin_api_test.go
director/redirect.go
director/redirect_test.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
registry/registry.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_test.go
server_ui/advertise.go

Closes #680 and fixes #633 
This PR gives the option for admin user to control whether the caches and origins should be approved before joining the federation. There are two config knobs to turn `Registry.CacheApprovedOnly` and `Registry.OriginApprovedOnly`.
This PR also fixes the bug where the director returns wrong error message if the server wasn't approved. As well as the bug where origin/cache returns "not approved" error on every 403 response it gets from the director

Reject unapproved origin/caches based on config and more robust director error response

---

cmd/root.go
launchers/launcher.go

Fixes #715 and #732 
For reviewer, the following can be a good verification process of the fix:
* Client should not log "Pelican is safely exited"  at the end of file transfer
```
./pelican object get -f osg-htc.org /ospool/uc-shared/public/OSG-Staff/validation/test.txt /dev/null
```
* Pelican should exit with status code = 1 if there's an error
* Spin up your origin by appending `; echo $?` at the end of your existing command. i.e `./pelican origin serve; echo $?`
* Kill XRootD by finding your xrootd process and kill it
* Pelican should exit with something like:
```
ERROR[2024-01-31T19:22:06Z] Fatal error occurred that lead to the shutdown of the process: xrootd process failed unexpectedly: signal: killed 
1
```
Note that `1` means the status code is 1.
Also this PR removed the error log …

Fix server exit status code and remove verbose log at the client

---

client/handle_http.go
client/handle_http_test.go
client/main.go
client/main_test.go

For downloads, if the `ProjectName` is present in a job ad for the plugin, it is added to the user-agent in the http request header.

Project name added to user-agent

---

web_ui/ui.go

Fixes #718 
However, for registry, since we have a wildcard handler to handle all the `GET` request at `/api/v1.0/registry/*wildcard`, 405 won't be returned but rather 404

Return 405 wherever it's supposed to be returned

---

director/origin_api.go
director/origin_api_test.go
director/redirect_test.go
registry/client_commands.go
registry/registry.go

Previously, namespace keys were fetched by hardcoding the issuer jwks relative to the namespace.
Now we conform to openid-style lookups by fetching the JSON located at
<registry url>/api/v2.0/registry/metadata/<namespace>/.well-known/namespace-configuration
and following the URL associated with the `jwks_uri` key. Currently this is still the same key path
in all instances that I'm aware of, but in theory this could be expanded to point to other locations.
We can also expand this namespace-configuration JSON to include additional information as needed.
The architecture of this PR is that a GET request to the namespace-configuration url mentioned above
should dynamically generate the JSON with `jwks_uri` key and associated value. The value is used throughout
and assigned the issuer URL in …

Update ns key discovery to follow openid-style lookups

---

.gitignore
Makefile
docs/parameters.yaml
generate/param_generator.go
web_ui/frontend/app/config/page.tsx

Closes https://github.com/PelicanPlatform/pelican/issues/654

Filter config

---

config/resources/osdf.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
xrootd/authorization.go
xrootd/authorization_test.go

OSDF origins and caches now pull permissions from topology. This is to get around x509 legacy issues in OSDF.

Topology authfile generation

---

.goreleaser.yml

This is one RPM that provides default configs and SystemD service files for the origin, cache, registry, and director.  This provides the virtual dependencies "pelican-origin", "pelican-cache", "pelican-registry", and "pelican-director" so anyone trying to do `yum install pelican-cache` will get this RPM.
Due to GoReleaser limitations, an RPM will be built for each arch (even though there are no arch-specific contents), and I can't make the versions in the "provides" lines based on the pelican version, I have to hardcode the number.
Closes #331 .

Add pelican-server RPM

---

client/main.go
cmd/plugin.go
config/config.go

NOTE: This switches the default for the plugin to use the director which will migrate a large amount of load to the director compared to what's currently seen.
Fixes #720

Enable OSDF defaults for stashcp/stash_plugin as well

---

classads/classads.go
client/handle_http.go
client/handle_http_test.go
client/handle_ingest.go
client/main.go
cmd/object_copy.go
cmd/object_get.go
cmd/object_put.go
cmd/plugin.go

This is a work in progress still but current changes include:
- Populating the new `DeveloperData` classad created by Todd M with most of the fields specified in the document of the issue
- Changing some inner-workings of the client, so that we can pass all relevant information back to the plugin
- Classads package can now decipher types of map[string]interface{} for nested classAds
Work still needed:
- Still need to add a few more classads with more info on each attempt
- More testing by hand is needed, to ensure functionality and backwards compatibility
- Testing with Todd M's latest merge to HTCondor to ensure functionality there
- Need to figure out how/what to return for classads on uploads

Expanding plugin error reporting from plugin to starter

---

.github/workflows/pre-release.yml

Fixes the broken release action by allowing the reused actions ( Release, and Release Container ) to use the original workflows secrets.

Allow reused workflows to inherit secrets

---

xrootd/authorization.go
xrootd/authorization_test.go

-- Removed extra newline when generating an authfile with a
provided authfile with a plublic line
-- Adjusted an authfile test to catch this

Fixed issue with added new line in cache authfile

---

config/config.go

When specifying the -l flag, log files now have permissions set to 0640 (not world readable) instead of 0644

Create non-world-readable logfiles

---

.goreleaser.yml
systemd/osdf-cache.yaml
systemd/osdf-director.yaml
systemd/osdf-origin.yaml
systemd/osdf-registry.yaml
systemd/pelican-cache.yaml
systemd/pelican-director.yaml
systemd/pelican-origin.yaml
systemd/pelican-registry.yaml

This is a workaround for #782 to avoid exposing sensitive data in world-readable logs, though it might be worth keeping around even after that issue is fixed, as an extra layer of safety.

Put default logfiles in /var/log/pelican; create /var/log/pelican non-world-readable in the RPM

---

config/resources/osdf.yaml
registry/client_commands_test.go
registry/registry_db.go
registry/registry_db_test.go

Should fix #789 
* From ITB registry log, the registry was killed with the following log message
```console
time="2024-02-08T17:08:39Z" level=fatal msg="Failed to create topology table: database is locked (5) (SQLITE_BUSY)"
```
Looks like there's race condition in DB write access, which makes sense because the error occurs every time someone tries to update/create a new registration
Looking at the code, we call `log.fatal` when we failed create the topology table, and we create the table every "topology update" cycle. The update interval was supposed to set to 10min but the value is `10` which was recognized by viper as **10 milliseconds** and it keep creating the table, doing a bunch of topology update, every 10ms.
This also fixes `504` error we sometimes get from topology, as we …

Only create topology table at server start and update topology table 10m instead of 10ms

---

config/config.go
config/resources/defaults.yaml
docs/parameters.yaml
metrics/shoveler.go

We now no longer set debug as a default config value and whenever it is used, we print a warning letting the user know that it is overriding anything set for Logging.Level. This is still needed however because of how our flags work with viper.

Debug config value is remove and warnings added

---

xrootd/xrootd_config.go

In XRootD, PSS debug level is the integer "4"; this makes the generated config match the XRootD code.
Only backporting to v7.5.x branch because @joereuss12 has a larger overhaul in progress for main.

Fix PSS debug level

---

xrootd/xrootd_config.go

Fixed an issue where the pss.origin wasn't being generated properly from the Federation.DirectorUrl
Note: I did do an end-to-end cache test where I curled the cache and was able to get a file served from a local origin.

cache directorUrl fix for pss.origin

---

cmd/origin.go
go.sum
launchers/launcher.go

It was a mistake to require that S3 origins be configured with a bucket. In the case of AWS public data, for example, it would be nice to have a single origin that exports all public buckets from `s3.amazonaws.com`. Under the old scheme, this would require an origin per bucket -- whoops!
- Spin up a registry/director.
- Serve a public origin (`Origin.EnablePublicReads: true`) that exports a single bucket from AWS open data -- we do still want this to work, even if we no longer require it:
`pelican origin serve --mode s3 --port 8444 --service-name "s3.amazonaws.com" --region "us-east-1" --bucket "noaa-wod-pds" --service-url https://s3.us-east-1.amazonaws.com -d`
- Now curl a test file from the origin: `curl -v -k https://<origin hostname>:<origin …

Remove bucket requirement for S3 origins

---

.github/workflows/release-container.yml
images/Dockerfile

Change release-container action to have build use goreleaser with snapshotting if  input.tags is empty, and only use goreleaser without snapshotting if input.tags contains a tag.

gorelease with snapshotting unless there are tags for Issue #681

---

.github/workflows/publish-container.yml
.github/workflows/publish-dev-container.yml
images/dev.Dockerfile

This downloads the latest xrootd source RPM from the OSG 23 development repos, and uses rpmbuild to build it locally for the current architecture.  The resulting RPMs are put into /usr/local/src/rpmbuild/RPMS/$arch/* (where $arch is the architecture, either x86_64, noarch, or aarch64) and a yum repo is built from it. The repo has highest priority so the locally built RPMs are picked over what's in EPEL.
To save time and space, the xrootd-compat libraries are not built, and neither are the docs.  Even with that, though, it's a good 20 minutes to build on ARM.  Caching the build results might be a good idea.

Rebuild OSG's xrootd RPM from source inside the dev container

---

docs/pages/prometheus.mdx
metrics/xrootd_metrics.go
metrics/xrootd_metrics_test.go

Closes #797 
To test, rename your `pelican` binary to `osdf` and set `Federation.DiscoveryURL` to `osg-htc.org`, and run your origin.
Login to the web UI, then go to `https://<origin-host>:<origin-port>/metrics` endpoint. Wait for a couple of minutes, refresh the page, and at the bottom of the page, you should be able to see the following metrics.
Note that now the `proj` label is available which is the `User-Agent` header from the client requesting the object.
```console
xrootd_transfer_bytes{ap="https",dn="",org="",path="/.well-known",proj="",role="",type="read"} 18709
xrootd_transfer_bytes{ap="https",dn="",org="",path="/.well-known",proj="",role="",type="readv"} 0
xrootd_transfer_bytes{ap="https",dn="",org="",path="/.well-known",proj="",role="",type="write"} 0 …
```

Add project to Prometheus file transfer metric

---

.github/workflows/publish-container.yml
.github/workflows/publish-dev-container.yml

Fixes the issue where the caching didn't work for building dev and production container. According to the log, it's due to 404 when GHA tries to push docker image manifest to harbor: https://github.com/PelicanPlatform/pelican/actions/runs/7975774289/job/21774758514
The fix was found here: https://github.com/goharbor/harbor/pull/18105#issuecomment-1811951274
Also adding debug to buildx for more verbose log.

Update GHA to allow manifest to be written to harbor

---

config/config.go
config/resources/defaults.yaml
docs/parameters.yaml
go.sum
web_ui/prometheus.go

Fixes #787 
The cause of the issue was that only the self-scraper config and service discovery config are reloaded. The origin/cache scraper never gets reloaded.
This PR also reduced the token refresh time to 5m to ensure we won't wait until another 59m if the token update wasn't successful.
To test, set the following config for faster expire/refresh cycle:
```yaml
Monitoring:
TokenExpiresIn: 2m
TokenRefreshInterval: 1m
```
Also make sure you have `Federation.DiscoveryUrl`  set to your director address.
I'd suggest spin up your servers individually in separate terminals in the order of `director`, `registry`, and `origin`. It also works for fed-in-a-box, but you'll see much more verbose log.
And you should see `200` for all `/metrics` request at the **origin** server (your log level …

Fix Prometheus token expires

---

config/resources/defaults.yaml
config/resources/osdf.yaml

The correct parameter name for requiring admin approval for origins and caches are `RequireOriginApproval` and `RequireCacheApproval`. But what we had in the default.yaml and osdf.yaml are the outdated names. This PR is to fix it.
To test, change your origin prefix to a new name you haven't registered in your registry, run your fed-in-a-box in OSDF mode and you should see something like: 
```
INFO[2024-02-20T18:52:15Z] Served Request                                client=172.17.0.2 daemon=gin fields.time="286.125µs" method=POST resource=/api/v1.0/registry/checkNamespaceStatus status=200
WARNING[2024-02-20T18:52:15Z] Failed to verify advertise token. Namespace "/haoming/testorigin5" requires administrator approval 
INFO[2024-02-20T18:52:15Z] Served Request …
```

Fix wrong parameter names for default and osdf config files

---

.goreleaser.yml
systemd/pelican.logrotate

This rotates at 500 MB, 10 times, but given that distros by default run logrotate only once a day, this just means that light days won't rotate out heavy days; we still need to be conservative about log sizes so a sudden spike won't use up all the disk.
Closes #728

Add logrotate file

---

cmd/cache_serve.go
cmd/root.go
config/config.go
docs/parameters.yaml
generate/param_generator.go
launchers/launcher.go
param/param.go
param/parameters.go
param/parameters_struct.go
web_ui/frontend/app/api/docs/pelican-swagger.yaml
web_ui/ui.go

This should close part of the ticket #753 with all necessary backend support added.
Test is a bit tricky and a bit complicated:
1. Build and spin up one of your server (I used registry as the example below but it work for all servers)
2. Login to your server web ui **with your admin account** (You may test with a general user account but the API will return 403)
If you are using [postman](https://www.postman.com/downloads/), here is the instruction:
1. After login, `inspect` the current page in your browser (cmd+opt+i for Chrome) 
2. Go to `Application` tab
3. Find on the left side `Cookie` and go to the domain where your server is hosted (likely `localhost:xxxx`
4. Copy the value of the `login` cookie 
5. Go to postman and create a new HTTP session with `PATCH` action and …

Web-based config change - backend support

---

common/director.go
director/advertise.go
director/advertise_test.go
director/cache_ads.go
director/cache_ads_test.go
director/director.go
director/director_api.go
director/director_api_test.go
director/redirect.go
director/redirect_test.go
director/sort.go
director/stat.go
launchers/director_serve.go
web_ui/frontend/app/api/docs/pelican-swagger.yaml

Closes #847 
The first commit and third in this PR tackles on the massive public functions inside of the director and change them to private. The most related changes to close #847 is the second commit

Add API at the director to return the longest prefix match given a path

---

docs/pages/client-usage.mdx
docs/pages/install.mdx

`/osgconnect/public/osg/testfile.txt` is outdates and unreachable in most of cases. This PR replaces the outdated file by `/ospool/uc-shared/public/OSG-Staff/validation/test.txt`

Replace broken test file path in docs

---

metrics/xrootd_metrics.go

In #823, the debug message was kept in the commit. This PR removes such debug log.

Remove debugging log from xrootd metrics handler

---

common/director.go
director/redirect.go

Fixes #851 
The cause of the issue is that in #705, when we added `brokerUrl`, we used `*url.URL` instead of `url.URL`. When broker service is turned off, `brokerUrl` is empty. When the director reads an empty url string, parses it as an empty url instance, and _pass the pointer to the empty url instance_ to the `serverAd`, the `serverAd` records the **address** of the empty `url.URL` instance, instead of just an empty url.
This causes bug because in the following registration from the same server, that address of empty url will change, resulting in a different `serverAd` than before, and all the map structure we have took it as a new key.

Fix duplicated server advertisement at the director

---

cmd/origin.go
config/resources/defaults.yaml
docs/parameters.yaml
github_scripts/osx_install.sh
param/parameters.go
param/parameters_struct.go
xrootd/origin_test.go
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

This is the Pelican plumbing needed to use the new options in the S3 plugin.

Add knob to enable path-style S3 URLs

---

client/errorAccum.go
client/main.go
cmd/object_copy.go
cmd/object_get.go
cmd/object_put.go
cmd/plugin.go
config/config.go

Adds and error to config so that if there is a timeout getting the metadata response, we mark as retryable and exit(11). In addition, found that we were marking things as retryable even when the client has no errors in its checked error stack array, so check for that now and return false for retryable if that array is empty.

Failure to get metadata is now retryable error

---

config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

Changes include:
- Xrootd logging now uses the standard logrus logging values
- Instead of string comparisons for mapping, we now use log.ParseLevel and compare the levels (which are unsigned ints)
- The program now exits when there is an improper config value and returns a proper error
- Anywhere these configs are listed, they are all listed alphabetically for consistency and an easier time finding each option
- Unit tests for the generation of the xrootd config file

Fixes to xrootd logging config

---

config/config.go
config/config_test.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go

Closes #886 
@turetske If this is merged in before 7.6 release, we should note the breaking change in the release note

Remove `Federation.NamespaceUrl`

---

client/handle_http_test.go
director/redirect.go
director/redirect_test.go

Closes #345 
Since currently we only return the longest-prefix-match of the namespace prefix given a file path, the `depth` attribute, if exists, will be identical for all the `Link` headers in the response. We can for sure change this if we want to offer different levels of hierarchy of namespaces for a file request

Add depth attribute to link header in redirect response

---

github_scripts/get_put_test.sh
github_scripts/stat_test.sh

When fixing test failure in #885 I spot that the `get_put_test.sh` leaves zombie pelican and xrootd processes if the test fails, and the grep condition for output logs seem not to capture the correct server response, causing false negative (or positive, depending on how you look at it) test result. So this PR attempts to fix the problems in the test script.

Refactor integration test scripts to be more robust

---

xrootd/xrootd_config_test.go

Fixed the bug where xrootd tests would create files outside of tmpdir. Found the leak was doing a viper.reset() and resetting the cache and origin run locations so the config was being written locally. Should be fixed now!

Xrootd tests now do not generate files outside tmp

---

config/config.go
config/config_test.go
docs/pages/client-usage.mdx
docs/parameters.yaml

When a discovery-url contains a path (when set in config or with `-f`), we will throw an error when we call DiscoverFederation on that url. If it is contained within a `pelican://` url however, we cannot really catch that specific error since we will assume any paths added to the discovery-url to be the namespace-prefix and so on. Therefore, I added a few notes to the documentation alerting that this will fail.
Note: I realize the client-usage docs are out of date but I added this for when we refresh the docs

Added error when discovery-url contains a path

---

cmd/root.go
daemon/launch_unix.go

Fixes #868 
There are two issues causing the bug:
1. We return immediately if `err := rootCmd.ExecuteContext(ctx); err != nil`, not waiting for error group to clean up.
2. We didn't kill daemons if the `ctx` parameter is cancelled, which is the case when there's error from server goroutines (where it will call shutdownCancel). We only did it either when receiving OS signal or the daemon expires.

Clean up goroutines when fatal error occurs at server start

---

param/parameters_struct.go
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

Legacy caches won't work with public pelican origins without the ability to fallback to xroot protocol. This adds `sec.protbind * none` to the origin config if the origin is run with `Origin.EnablePublicReads: true`. Note that when we have multi-exports origins configured from #858, we'll have to handle this more carefully.
So that the reviewer doesn't have to hunt, the addition to the struct in `xrootd/xrootd_config` is `EnablePublicReads`. I had to adjust spacing to make the linter happy, and it buried the change.
To test, try running an origin with `Origin.EnablePublicReads` set to true and then to false. You should see the `sec.protbind * none` line appear in the xrootd config for public, and be absent for non-public.

Configure 'sec.protbind' for public origins

---

.github/workflows/build-prod-container.yml
images/entrypoint.sh

I think I missed changing the docker image tag from `pelican_platform/pelican` to `pelican_platform/<server-name>`. This PR attempts to address the issue.
Update:
This PR also fixed the bug where pelican arguments can't be passed to tini

Replace `pelican` with server name for production image

---

web_ui/frontend/components/layout/Sidebar.tsx

Closes #629 
With admin privilege:
Without:
I kind of hate fetching `/whoami` one more time during rendering (I believe we already did 2 or 3 times per page) but not doing that requires us using context or some state management package which seems outside of the scope for this ticket.

Add user role icon to the side bar in UI

---

images/Dockerfile
launchers/launcher.go

Fixes #917 
Also fixes the bug where we check director's endpoint to ensure director is working but we are checking against `Server.ExternalWebUrl`, which is wrong.
Building the container and running locally, I can confirm this fix will enable cache to run.

Fix production cache container failure at start up due to outdated xrootd

---

web_ui/authorization.go
web_ui/prometheus_test.go
web_ui/ui.go

In the merge from #877 and #840, git seems to skip one important line that causes the Prometheus endpoint to return 200 with empty response body. This PR fixes this issue and added test to ensure

Fix Prometheus handler not called

---

.github/workflows/build-prod-container.yml
.github/workflows/pre-release.yml
images/Dockerfile

This PR fixes the issue that for the production docker image where we didn't set the correct branch ref when checking out for building the base image.
This PR also attempts to fix the missing input argument in GHA workflow file

Fix misplaced branch check in GHA

---

.github/workflows/pre-release.yml

Fix GHA linter error in releasing where the `tag` input feed from `pre-release.yml` is not used in `release.yml`, which is true. So this PR removes the tag input.

Removed unused input tag in `release.yml`

---

.github/workflows/pre-commit-linter.yml

Attempted to fix #929 based on https://github.com/golangci/golangci-lint-action/issues/135 Since folks are still reporting the issue with the fix, I can't be sure if the fix is guaranteed to be always effective and it does reduce the chance of hitting the error.

Upgrade golangci GHA version and turn off caching

---

config/config.go
config/logging.go
go.mod

Fixes #918 
Second attempt to fix the logging bug where log color are lost in a TTY terminal and `LogLocation` is not working.
This PR also fixes the bug where `Logging.Level` was not respected.
@turetske  Marking this as critical and putting it under 7.6 because the bug causes trouble at deployment/monitoring side. We can backport it in 7.6.1 if this can't be merged in before 7.6 release.

Fix log color loss and `LogLocation` not working

---

cmd/plugin.go

This fixes the bug we were getting with the pelican plugin where we would see the plugin exiting 0 but sending out `no valid classads`. The issue was an error type being written out and bypassing strconv.QuoteToASCII which would remove any inside quotes.
Also found a spot where we were getting a nil pointer dereference because we were accessing data before an error check, fixed as well

Fix pelican plugin bug `no valid classads...`

---

images/Dockerfile
images/entrypoint.sh

Embed `serve` as default command to run the server container

---

docs/pages/install/_meta.json

One line fix for the typo in `meta.json` for documentation page for Docker

Correct the key for docker doc page

---

.github/workflows/release.yml
images/Dockerfile

Closes #459 
I tested locally that removing the whole `generate` package locally won't cause build to fail, and the docker container I built with that runs as expected.

Remove `generate` package when releasing

---

cache_ui/self_monitor.go

Create tmp cinfo file for cache self test under the same folder as the final file

---

.goreleaser.yml
config/config.go

Goreleaser was not setting version correctly for the 'config' package. Should work properly now.

Fix bug with version being "dev"

---

registry/registry.go
registry/registry_db.go
registry/registry_ui.go
web_ui/frontend/app/api/docs/pelican-swagger.yaml

API support for registry admin to delete a namespace registration

---

broker/client.go
cmd/registry_client.go
config/init_server_creds.go
config/init_server_creds_test.go
registry/registry.go
registry/registry_ui_test.go
web_ui/authentication_test.go
xrootd/origin_test.go

Fixes #956 
This PR allows admin to pass RSA key in either PKCS8 or PKCS1 form as the TLSKey or TLSCAKey. Came with tests.
This PR also bypass the error reporting if only TLS cert and TLS key are present and CA cert is missing. It will instead generate a CA with its private key (mostly for xrootd and broker) and continue.

Allow RSA key for TLS

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

In #937, the `generate` package was removed before we call goreleaser, but it causes our changes in git which goreleaser doesn't like. This PR revert the removal of `generate` package to allow goreleaser pass the validation check. There seems to be no apparent alternative to this approach.

Revert changes that remove `generate` package

---

registry/registry.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_ui.go

Consolidate two `namespaceExists` DB function

---

.github/workflows/go-generate-check.yml
.github/workflows/release.yml
.goreleaser.yml
generate/param_generator.go
images/Dockerfile

[Unify Build Process](https://github.com/PelicanPlatform/pelican/pull/972/commits/9a2bda35ea9c99799ce2ea98fbd3539d0f8b9763) 
Adds check that go generate has been run on the latest commit
Moves make web-build into goreleaser before which will make how we build dev binaries more similar to how we build production binaries
Rewrites the dockerfile moving the web build into the gorelease section
Doesn't needlessly update parameters.json on go generate ./..
Closes #971

Import parameters.json into website

---

director/director.go
launchers/director_serve.go
launchers/launcher.go

Short and sweet, this should allow us to issue HEAD requests against the API the `/api/v1.0/director/<origin or object>` endpoints. The tagged issue also mentioned making this compatible with our shortcut middleware in the director, but it looks like it already was -- the middleware was agnostic of verbs that weren't `PUT`. My addition to the middleware here explicitly ties `GET/HEAD` requests to the appropriate redirect functions so that other verbs we don't anticipate don't creep in.
One thing to note is that if a client who issues a `HEAD` for some resource chooses to follow the redirect, XRootD appears to hang with an open connection. Since that's in XRootD land, I'm considering it outside the scope of this small fix.
Closes #754

Fix director default response and add HEAD as allowed verb

---

client/handle_http.go
client/handle_http_test.go

The client now sets a X-Pelican-Timeout header for download requests which should get passed along to the cache

Pelican client advertises timeout to cache

---

client/fed_test.go

Added unit test for statHttp within Pelican client. Note: this should not be merged until #884 is completed since currently statHttp only works with topology. Therefore, I expect tests to fail and I will readdress them once that PR is merged and this function is working properly.

Unit test for statHttp within Pelican Client

---

client/handle_http.go
client/handle_http_test.go
client/main.go
client/main_test.go
cmd/plugin.go
local_cache/local_cache.go

Project name, if set, will now show up in the user-agent header for requests. This PR also removes some old unused legacy code of the "payload" object (the only piece of the object still used was the project name). Also includes a unit test checking that the client properly sets this header.

Fix bug where project name not set in user-agent

---

config/config.go
launchers/launcher.go

Closes #953 
To not to confuse user when they spin up the server instance without the intension to see the config file, this feature only turned on if logging level is set to debug or info. Also the output it directed to stderr instead of stdout to exclude it from other server output.

Output pelican config to stderr at server start

---

docs/pages/prometheus.mdx

Update Prometheus doc to introduce counting server number

---

metrics/xrootd_metrics.go
xrootd/resources/xrootd-cache.cfg

Closes #944 
This PR also fixes the issue where handling summary monitoring packet with cache reports error due to misformat xml packet
This PR fixes the bug where xrootd summary packet was not monitored if the binary is not `OSDF`
Although this PR collected byte hit/miss/bypass from xrootd g-stream monitoring packet, it appears to me that we only get byte hit number increasing while not for byte miss nor byte bypass. I tried locally to move a brand new file (that the cache doesn't have) and check the `.cinfo` file which should be the source of the g-stream, but the byte miss is 0 in that file. Same thing with the case where no file at the cache side and origin has `direct reads` turned on, the only number got updated in byte hit.
Will open a separate ticket for further investigating this …

Cache hit/miss bytes Prometheus metric

---

images/Dockerfile
images/dev.Dockerfile

Closes #881 
This PR pins commit when building from source in dev/production containers for s3 plugin, xrdcl plugin, and lotman

Pin external c++ dependencies at a specific commit

---

docs/parameters.yaml
web_ui/frontend/app/config/page.tsx

Added a 'cache' string [here](https://github.com/PelicanPlatform/pelican/pull/889/files#diff-e64181cce5ce490155a33cdffaa48b7eea8d1f07e4c7f0aef3ae447f720e7641) so that I could view the cache only `Lotman` configuration. 
This is to remove that leaked testing code.

Remove Testing Code

---

server_utils/server_utils.go
server_utils/server_utils_test.go

As @williamnswanson noticed in #1033, at a failure of `WaitUntilWorking` test, we don't know the server URL that Pelican attempts to check. This PR add server URL to various error/log messages. Come with tests.

Add server urls to error messages for `WaitUntilWorking`

---

.goreleaser.yml
cmd/main.go
cmd/main_test.go
cmd/object_copy.go
cmd/plugin.go
config/config.go
launchers/launcher.go

Closes #1026 
Print the version regardless of logging level

Print pelican version at server startup to stderr

---

client/fed_linux_test.go
client/fed_test.go
client/handle_http.go
client/handle_http_test.go
client/handle_ingest.go
client/main.go
client/main_test.go
client/sharing_url.go
client/sharing_url_test.go
cmd/object_copy.go
cmd/object_get.go
cmd/object_put.go
cmd/plugin.go
cmd/plugin_test.go
config/config.go
config/config_test.go
github_scripts/get_put_test.sh
local_cache/cache_test.go
local_cache/local_cache.go
namespaces/namespaces_test.go
registry/client_commands_test.go
registry/registry_db_test.go
xrootd/authorization_test.go
xrootd/xrootd_config.go

This is v2 of PR #798  since the merge conflicts were becoming very tedious. Therefore, I took the changes from that PR and converted it over to a new branch. You can get the changes split up a little better from that PR as well but I will do my best to list them here:
Changes include:
- Added a ttl cache for storing federation url metadata so we do not have to look up each time
- Improved unit tests for client commands, Note: for pelican prefix and osdf:// url scheme, it's hard to test since we use osg-htc.org for metadata lookup. Therefore it is hard to work with fed in a box so I just check for the proper metadata lookup
- Added function called discoverUrlFederation which discovers a federation from a url and does not populate global metadata config values
- Added a function called …

Remove use of global fed metadata within client

---

cmd/plugin.go

After talks with some facilitators, they told us ways to improve error messaging from the plugin. Now, all errors from the plugin now begin with PELICAN CLIENT ERROR as well as end with HOSTNAME and GLIDEIN_SITE
Before:
```
Transfer input files failure at the execution point using protocol osdf. Details: Error from 
slot1_7@glidein_253984_295706592@uct2-c516.mwt2.org: FILETRANSFER:1:non-zero exit (1) from 
/var/lib/condor/execute/dir_253982/glide_YoREfU/stash_plugin. |Error:  Failure downloading 
osdf:///chtc/staging/jrreuss/foo-v1.txt: failed connection setup: server returned 403 Forbidden 
( URL file = osdf:///chtc/staging/jrreuss/foo-v1.txt )|
```
After:
```
Transfer input files failure at the execution point using protocol osdf. Details: Error from …
```

Improved plugin error messaging

---

web_ui/authentication.go
web_ui/authentication_test.go
web_ui/frontend/app/api/docs/pelican-swagger.yaml
web_ui/ui.go

Fixes #1004 
This PR also fix a bug in admin auth handler where if the user is not a admin, the handler didn't abort the request, causing the response to pass.
This is a critical bug with security concern and we should consider backport to 7.6 and 7.5.
Improved testing to cover both cases.

Add "login required" endpoints behind "admin" check and fix bug in admin auth handler

---

director/advertise.go
director/advertise_test.go
director/cache_ads_test.go
director/director.go
director/director_api_test.go
director/director_test.go
director/director_ui.go
director/director_ui_test.go

Because osdf origins and caches still have separate AuthURLs, this PR doesn't remove them fully from ServerAds. Rather, if it is a Pelican ServerAd, the AuthURL isn't set.
The director has been changed so that if an AuthURL isn't set, it will return the regular url instead when an AuthURL is needed and an AuthURL otherwise.

Removed the setting of an AuthURL for Pelican serverAds

---

director/director.go
director/origin_api.go
launcher_utils/advertise.go
launcher_utils/register_namespace.go
launchers/cache_serve.go
launchers/launcher.go
launchers/origin_serve.go
metrics/health.go
origin/origin.go
registry/client_commands.go
registry/client_commands_test.go
registry/registry.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_ui.go
registry/registry_ui_test.go
registry/registry_validation.go
registry/registry_validation_test.go
web_ui/frontend/app/api/docs/pelican-swagger.yaml
web_ui/frontend/components/StatusBox.tsx

Closes #1029 
* Added a `Registry` health component to the UI to should if registering namespace succeeded or not
* Better status tracking/updates of the health component overall
* Better error messages and plumbing
The updated policy is as follows (only for OSDF):
Given that a namespace exists in the topology, say `/foo`:
* If an origin server has prefix `/foo` or `/foo/**/**`, and the admin starts the server without registering the namespace at registry website, the auto-registration in the origin will _fail_, with an error message to ask them register the namespace at the registry web UI:
```
The namespace <namespace> already exists in the OSDF topology. To register a Pelican equivalence, you need to present your identity. If you are registering through Pelican CLI, try again with the …
```

Refactor registry namespace check to be compatible with OSDF topology

---

broker/broker_test.go
client/fed_test.go
cmd/fed_serve_cache_test.go
cmd/fed_serve_test.go
cmd/plugin_test.go
fed_test_utils/fed.go
launchers/launcher.go
server_utils/server_utils.go
server_utils/server_utils_test.go
xrootd/origin_test.go

Should fix #1033 
The suspicion is that there's a racing condition at the registry start somehow, and the web engine is not "ready-ready" to serve requests, although it could be other issues. However, this PR will make the web ui check more robust in case of the error code returned

More error tolerant web ui check

---

docs/parameters.yaml

Moved over the multilines to literal formatting rather then folding as Markdown expects literal. 
https://yaml-multiline.info/

Config fixups

---

images/dev.Dockerfile

In unit tests, we've been seeing timeouts in xrdcl-pelican due to what appears overly-long delays for DNS lookups.  I believe this is due to the DNS lookup not correctly being waited on for the curl multi-wait.  This bumps the dev image to the curl testing code; if successful, we may do a similar thing for prod.

Bump the revision of xrdcl-pelican for libcurl testing

---

client/errorAccum.go
client/fed_test.go
client/handle_http.go
client/main.go
cmd/plugin.go
local_cache/cache_test.go

v7.6.x has a regression where the `downloadObject` function returns an error whenever an error occurs; rather, it's only supposed to return an error if no transfers are attempted.  That change causes the multiple attempts to not be returned to the transfer plugin -- instead, only the last one is.
This change:
- Returns all the failed attempts
- Fixes the "15s since start" in error messages by recording when the error occurred.
- Stubs out any paths in the plugin error message (since HTCSS also reports the path).
- Switches the client to golang time objects where appropriate, converting to integers (and floats) only at the plugin level.

Correctly return the transfer attempt information

---

cmd/origin.go
config/config.go
config/resources/defaults.yaml

Because we have no way to tell whether defaults in defaults.yaml are user-provided or not, the default there of `Origin.S3UrlStyle` was throwing an error meant to notify users that they have incompatible config variables set.
This moves setting of that default into config.go where we now use `viper.SetDefault`, which later on allows us to `viper.IsSet("Origin.S3UrlStyle")` without catching our own default.

Move default S3 url style from defaults.yaml to config.go

---

cmd/plugin.go
cmd/plugin_test.go

Recursive uploads/downloads of directories work with the pelican plugin now! Tested with condor, it seems downloads work great however some functionality is not there for uploads when doing a transfer_output_remap. Going ahead to push this for now since it seems to be working for us. To do this, run:
stash_plugin osdf:///<some/path/to/directory>?recursive=true .
I decided to hold off on a unit test since it is not much different from our current recursive uploads/downloads tests and this can be a test ran in the condor test infastructure in the future.

Allow recursive uploads/downloads in plugin

---

fed_test_utils/fed.go

We saw some failures in the unit tests (which may-or-may-not be false positives) that complained about some other process listening on the common Unix socket.
Ensure that each federation test case will use a unique socket name, hopefully making the tests more robust.

Make the local cache location unique for each test run

---

.github/workflows/build-prod-container.yml
.github/workflows/pre-release.yml

This should fix the critical bug described in #1075 but leave the part untouched where "automatically tagging the latest release with the largest semantic version as the latest"

Only push the production container when the release was cut

---

director/advertise.go

The URLs for the topology namespace in director are broken. The current code gives `http:8000` as `url` or `authUrl` for namespaces from the topology (try `/api/v1.0/director_ui/severs`). The original code https://github.com/PelicanPlatform/pelican/commit/10fd09f8b803019098f5bdbaf10c91b39957f866 was correct in that `url.Parse` requires the scheme to be present, which is contrary to what I tested in the playground: https://github.com/PelicanPlatform/pelican/pull/1043#discussion_r1553705373
But since `url.Parse` documented that parsing a url without scheme is invalid, let's keep doing what we were doing to ensure nothing breaks.

Fix broken URLs of namespaces from the topology at the director

---

.github/workflows/build-prod-container.yml

Closes #1079 
This one should be merged in before subsequent releases after `7.7.0` to make sure our `latest` tag works as expected

Set the largest semantic version tag to the latest image

---

client/errorAccum.go
client/errorAccum_test.go
client/handle_http.go
client/handle_http_test.go

Made StoppedTransferError and Cannot allocate memory a retryable error

Made additional retryable errors

---

client/fed_linux_test.go
client/fed_test.go
client/handle_http.go
client/handle_http_test.go
client/sharing_url_test.go
cmd/plugin_test.go
cmd/root.go
config/config.go
config/config_test.go
config/encrypted.go
launchers/director_serve.go
launchers/registry_serve.go
namespaces/namespaces.go
namespaces/namespaces_test.go
oauth2/oauth2.go
registry/client_commands_test.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_ui_test.go
xrootd/authorization.go
xrootd/authorization_test.go

Refactored the functionality of Get/SetPreferredPrefix to utilize the ConfigPrefix type to further ensure whatever prefixes we get/set are correct.

Refactor Get/SetPreferredPrefix ConfigPrefix type

---

launcher_utils/advertise.go

When a cache started and the registry requires admin approval, the cache exits with the following error message:
```
The namespace \"\" requires administrator approval. Please contact the administrators of [https://itb-osdf-registry.osgdev.chtc.io:443](https://itb-osdf-registry.osgdev.chtc.io/) for more information."
```
where the namespace is empty, which is wrong. This PR attempts to provide a better error message

Fix empty namespace in error message when cache is not approved

---

director/director.go
director/director_api.go
director/director_test.go
director/origin_api.go
director/origin_api_test.go
utils/web_utils.go

Fixes #1108 
The issue #1108 describes in the production server is likely triggered with the following conditions:
* The registry server pod is down (for whatever reason), but visiting registry URLs gives 404 (probably due to traefik)
* When the director attempts to verify a token origin/cache server sent to advertise, it calls `server_utils.GetJWKSURLFromIssuerURL(issuerUrl)`. This function first attempts to request `issuerUrl` and get the `jwks` endpoint from `issuerUrl` response. The `issuerUrl` is `https://<registry>/path/to/issuer`, which returns 404. The function recognize the response 404 as a compatibility issue and thought it hit the legacy OSDF topology, so it instead construct the jwks endpoint by concatenating  `Federation.IssuerURL` with predefined path …

Replace `jwks.cache` by TTL cache for namespace jwks at the director

---

daemon/launch_unix.go
web_ui/frontend/package-lock.json
web_ui/ui.go
web_ui/ui_test.go

Closes https://github.com/PelicanPlatform/pelican/issues/1097 
Also fixed the issue where the component health metric has the wrong name `Xrootd.cache` instead of `xrootd`

Fix cache dashboard page skips auth check and wrong health metric name

---

cmd/plugin.go

Added the PluginVersion to the StartdAttrs so that it can show up as a starter ad.
Jira ticket: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1051
Pelican ticket: https://github.com/PelicanPlatform/pelican/issues/1112

Populate StartdAttrs in plugin -classad output

---

cmd/plugin.go
cmd/plugin_test.go

The plugin now works if it receives classads in the infile that are not the url or LocalFileName as long as the infile contains them at some point. This is useful for HTCSS devs as they will eventually pass things to the plugin through the infile and for now we don't fail when that happens. Updated unit test and fixed bug in writing the error message to check that we have a url (string) before parsing it (in cases of panic we don't pass a url).
This was a request from TJ and other HTCSS devs

Allow plugin to work w/ non-url/localfile classads

---

xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

PR #1143 had a mistake in that it set a scheme for the XRDHOST env var. This PR removes the scheme and updates the tests to check the correct thing.

Don't include scheme when setting XRDHOST for osdf origins

---

cache/cache_api.go
cache/cache_api_test.go
docs/parameters.yaml
launchers/cache_serve.go
launchers/launcher.go
param/parameters.go
param/parameters_struct.go
server_utils/origin.go
server_utils/origin_test.go

Add support for checking a sentinel file for the cache

---

docs/pages/serving_a_federation.mdx

The configuration parameter `Registry.AdminUsers` was deprecated and replaced by `Server.UIAdminUser`, but the documentation records the wrong updated param name.

Fix wrong information in config OAuth for the registry

---

config/config.go
config/env.go
config/env_test.go

Closes #1123 #954 
This PR makes it possible to take both OSDF/STASH prefix and PELICAN prefix for `osdf` / `stash` binary.

Deprecate OSDF/STASH environment prefix and use PELICAN

---

.github/workflows/test.yml
cmd/main.go
cmd/main_test.go
cmd/object_copy.go
cmd/plugin.go
config/config.go
github_scripts/version_test.sh
launchers/launcher.go

Fix version flag output

---

registry/custom_reg_fields.go
registry/registry_ui.go
registry/registry_ui_test.go

As @CannonLock found out, the current validation for customized registration fields fails on `integer` type values, since Go will by default marshal JSON numbers to `float64` type. This PR converts any customized fields with `float64` or `float32` type to `int` type, which should be a relatively safe assumption as we currently don't support float-time customized fields. 
This PR also improves test coverage for the registration to cover this case.

Fix wrong type for integer values in requests with customized registration fields at the registry

---

client/handle_http.go
client/handle_http_test.go
client/main.go
client/main_test.go
cmd/plugin.go
local_cache/local_cache.go

For uploads and downloads we now can see an X-Pelican-JobId header that records the GlobalJobId from a condor classad. I also refactored the GetProjectName function to be just a SearchJobAd function to work with the two different classads we look for.

Add JobId to X-Pelican-JobId header

---

director/advertise_test.go
director/cache_ads.go
director/cache_ads_test.go
director/director.go
director/director_api.go
director/director_api_test.go
director/director_test.go
director/director_ui_test.go
director/sort.go
director/sort_test.go
director/stat.go
director/stat_test.go
server_structs/director.go

Closes #870 
This PR also removed the mutex locks we used for TTL cache as TTL cache is thread-safe.

Change director TTL cache key from `ServerAd` to server URL

---

broker/broker_test.go
config/config.go
director/director.go
launcher_utils/advertise.go
launcher_utils/advertise_test.go
launcher_utils/register_namespace.go
registry/custom_reg_fields.go
registry/registry.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_test.go
registry/registry_ui.go
registry/registry_ui_test.go
registry/registry_validation_test.go
server_structs/registry.go

Closes #1106 
Some points to note (copied from the ticket above):
* We need to have https://github.com/PelicanPlatform/pelican/issues/1107 ASAP; otherwise, with multi-export support at the origin, we can't wisely determine which namespace to fetch the site name from the registry. Currently, this PR only grab the first exported namespace as the prefix to query the site name at the registry, which is a bit sketchy.
* ~~We need to add an extra serverAd field Hostname to the director (and during advertisement), with this change.~~ When implementing this PR for caches, the director fails to verify the advertisement token from the cache because it relies on the `Name` field from the `serverAd` to find the namespace for the cache and grab the public jwks from the registry. If the Name is …

Improve site name handling

---

web_ui/ui.go
web_ui/ui_test.go

As recently found out in the Denver cache deployment and NSDF S3 origin deployment, the web UI is trapped in an infinite redirect at the server start (not yet initialized with admin password). This PR is to fix this issue.
To test the fix, follow the instructions below:
* Remove your admin password file (backup first): `rm /etc/pelican/server-web-passwd`
* Build and run an origin `./pelican origin serve`
* Go to the admin website at https://localhost:8444/
* You should be redirect to the initialization code page at `/view/initialization/code/`

Fix infinite redirect of UI init page

---

images/Dockerfile
images/dev.Dockerfile

The `v0.1.1` plugin had a snippet of code that wasn't thread safe, but was only triggered in the case of PUTs. That has been fixed/tagged upstream in [this issue](https://github.com/PelicanPlatform/xrootd-s3-http/pull/33).
This PR updates the plugin version used in our containers.
@haoming29, when this is merged we should also patch it into 7.7

Update S3 plugin in containers to fix segfault

---

config/resources/defaults.yaml
director/director_test.go
director/resources/geoip_overrides.yaml
director/sort.go
director/sort_algorithms.go
director/sort_test.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go

Currently, the director blindly redirects clients to the cache nearest to them without any consideration of whether that cache may be overloaded. While we work to make cache load information available in the Director, this adds a "load-aware" load balancing function -- that currently assumes the same load for every cache.
When we have load information for each cache, this new feature should be able to grab that information from the cache's serverAd and do something intelligent with it. For now, I'm assuming load will be from [0,1] where 0 is no load and 1 is the highest.
This commit also makes it a bit easier to develop more load-balancing algorithms by hooking up algorithm selection to a configurable parameter. For testing, we can also randomly sort things.
Closes #1173

Shim in ability for the director to use load-aware cache redirects

---

client/errorAccum.go
client/errorAccum_test.go
cmd/plugin.go

Adds net timeouts to the list of retryable errors. Also, in the plugin, where we check if we already failed we used to only return TransferError and TransferSuccess, now we return TransferRetryable as well.

Allow net timeouts to be retryable errors

---

config/config.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-cache.cfg
xrootd/xrootd_config.go

Allows a used to specify multiple cache/meta data file locations

Added the ability to specify a list of data/meta folders for the cache

---

github_scripts/osx_install.sh

My previous PR missed one place where the S3 version was declared. In a future release cycle, I hope we can centralize this so I don't have to remember the growing list of places that need these updates.

Bump s3 plugin version for OSX CI test

---

client/director.go
client/director_test.go
client/errorAccum.go
client/errorAccum_test.go
client/fed_linux_test.go
client/handle_http.go
client/resources/both-auth.yml
client/resources/both-public.yml
client/resources/one-pub-one-auth.yml
config/resources/defaults.yaml
director/director.go
director/director_test.go
director/director_ui.go
director/director_ui_test.go
origin/advertise.go
server_structs/director.go

This is a different approach to the change of directory listings. Now, for recursive downloads, we will query the director for a PROPFIND to get the location of our "dirlisthost" (or origin). Then procede with the normal recursive download code. If we receive a 405 from the director doing this PROPFIND, we will revert back to the old way of doing things

Directory listing changes in Pelican client

---

client/main.go
client/main_test.go
cmd/object_copy.go
cmd/object_get.go
cmd/plugin.go
local_cache/cache_test.go
utils/utils.go

To specify the local cache, users need to set the NEAREST_CACHE env variable. In the old functionality, setting this means we do not look for any other caches and just try to use this "preferred cache". Now, if the specified NEAREST_CACHE has a '+' character at the end of it, it will now append the "normal" list of caches behind the preferred cache in the list of caches to try.

NEAREST_CACHE preprend cache list when specified

---

director/cache_ads.go
director/cache_ads_test.go

With the new TTL cache key in place #1186, there can be a case where a server from the topology shares the exact same url as a Pelican server, so there's a "key collision" and the two servers will fight against each other in the cache. This PR sets the rule that, in case of a key collision:
* If the existing server in the cache is a _Pelican_ server, and the incoming server is from the topology, then we ignore the incoming server/
* If the existing server in the cache is a topology server, and the incoming server is from Pelican, then we **overwrite** the existing server by the incoming server

Overwrite topology server if there is a Pelican server with the same url

---

classads/classads.go
client/fed_test.go
cmd/plugin.go
cmd/plugin_test.go

Fixes up a very long error message from condor with the Plugin. This ensures that the plugin will return TransferUrl and TransferFileName even when empty so condor will be happy. Also fixes bug with error message for 404 no namespace found for path not returning correct error.

Plugin include TransferUrl & TransferFileName

---

registry/registry_validation.go
server_utils/monitor.go

`HandleDirectorTestResponse` API returns if the authentication check fails

---

client/handle_http.go
cmd/plugin.go
cmd/plugin_test.go

There was a bug with the plugin when doing recursive downloads. If some error happened such as a 404 on the directory we are requesting or a 500 which is doing the ?recursive query on a file instead of a directory, PROPFIND would fail and the error was not making it back to the plugin. Now, when we discover this error (eventually makes its way to RunMux() in client/handle_http.go) we populate the results channel with the failed result before closing it. This way, the plugin can see the results and record the failure.
In addition, I added some unit tests toward these failures as well as for recusive downloads for plugin in general.
To test: run `stash_plugin pelican://path/to/some/file?recursive=true .` and see that we get classads returned that record a TranferError as well as other …

Plugin recursive download errors returned properly

---

client/fed_linux_test.go
client/main.go
cmd/plugin.go
utils/utils.go
utils/utils_test.go

This removes the need for a value to the ?recursive query parameter, we just check that it exists. Added a deprecation warning if a user utilizes a value and informs the user the value will be ignored. In addition, added the ability to use the ?recursive parameter outside of the plugin to avoid any confusion.

Remove the need for =true for ?recursive

---

cache/advertise.go
director/director.go
director/director_test.go
origin/advertise.go
registry/registry.go
server_structs/director.go
web_ui/frontend/app/registry/components/util.tsx

Fixes #1241 
The bug was introduced in 7.8.0 where the director uses `hostname` of `DataURL` of the cache to concatenate with `/caches/{hostname}` for looking up the namespace prefix for the cache in the registry. This is based on the premise that the default value of `Xrootd.Sitename` is `Server.Hostname`, which is what the cache used to register itself at the registry.
However, in most of our ITB/production servers, we changed `Xrootd.Sitename` to something more human-readable, which causes the discrepancy between director look-up and what register records. 
This PR fixes the issue by adding a new field in origin/cache advertisement, `RegistryPrefix`, which is the full namespace prefix the cache used to register itself at the registry, i.e. `/caches/{Xrootd.Sitename}`, so that the …

Fix director bug in looking up prefix for cache

---

cmd/plugin.go
github_scripts/citests.sh

As requsted from the condor devs, Pelican now accepts PELICAN_NEAREST_CACHE. This is so this set environment varible looks more important and not confusing for what it is for when set in condor configuration

Plugin now also accepts PELICAN_NEAREST_CACHE

---

cmd/plugin.go

Ran into an issue on ospool since the pelican plugin stopped advertising PluginVersion with -classad, this change reimplements that advertisement in addition with PelicanPluginVersion.

Plugin advertises PluginVersion

---

client/director.go
client/handle_http.go

Found a bug when we try to PROPFIND against an outdated director, the director returns a 404 not found (because it redirects to a cache and that cache cannot find the object to PROPFIND so it returns a 404). When this happens the client returns just the error and not the response. Therefore, the fix is to check if we fail querying the director with a PROPFIND, we check if the namespace has a dirlisthost. If dirlisthost is present, we continue and otherwise, we fail. We'll need to eventually create a way to test against outdated directors but for now, we'll stick to this band-aid.

Fix bug when director returns 404 for PROPFIND

---

github_scripts/citests.sh

The PR to add 'pelican' to SupportedMethods list was merged before the integration tests could run. Once they were run it was revealed that I forgot to update the check for the -classad output. This fixes that.`

Fix integration test failure

---

director/advertise.go
director/advertise_test.go
director/cache_ads.go
director/director_api.go
director/director_ui.go
launchers/director_serve.go
registry/registry_db.go
utils/web_utils.go

Fetch topology downtime for cache servers

---

cmd/main.go
cmd/origin.go
config/config.go
config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
server_utils/origin.go
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

Some non-pelican origins currently in the OSDF don't speak HTTP. This makes them incompatible with Pelican and is preventing us from fully transitioning legacy services. To work around that limitation, this adds an "xroot" backend, which allows us to stand a Pelican origin (speaking HTTP) in front of an xroot-only origin.
This backend isn't meant to be extensible, and as such I haven't added any tests. To test by hand, you can configure:
```
Origin:
StorageType: xroot
EnablePublicReads: true
XRootServiceUrl: <some xroot-only origin url, with port>
FederationPrefix: <a valid prefix for that origin>
StoragePrefix: <same as federation prefix>
```

Add an XRoot storage backend

---

client/director.go
client/handle_http.go
client/handle_http_test.go

The Pelican client now will look out for duplicate caches to try returned from the director. This is done with a new helper function that will get the caches to try and check for any duplicates. If we find a duplicate, it will not be added to the list of the caches to try. In addition, there are various cleanups of old debug logging as well as some new logging that seems cleaner without removing anything important.

Client de-duplicate cache entries from director

---

client/fed_linux_test.go
client/fed_test.go
client/handle_http.go
client/handle_http_test.go
client/main.go
cmd/plugin.go
config/config.go
config/resources/defaults.yaml
local_cache/cache_linux_test.go
local_cache/cache_test.go
local_cache/local_cache.go

The transfer engine in the client now throws a clear error if config.InitClient() has not been called. Before this fix, if InitClient() was not called we would get an error from the TransferEngine about not having worker count set or other unexpected/undesired behavior. Now, InitClient() checks if the workercount has been set (sets a default value if not) and NewTransferEngine() now throws an error if the client has not been initialized.

Throw clear error when InitClient() not called

---

docs/parameters.yaml
origin/origin_ui.go
server_utils/origin.go
swagger/pelican-swagger.yaml

Closes #1180 
This added extra fields to the `/origin_ui/exports`, additional UI work required to render the data.

Add http backend to origin data export API

---

images/Dockerfile
images/dev.Dockerfile

Closes #1199 
For the rest of vulnerabilities, they are coming from the `scitoken-oauth-server` image we inherit, essentially the OA4MP software we depend on. I've opened an issue in the OA4MP repo for fixing those vulnerabilities: https://github.com/ncsa/oa4mp/issues/183

Bump base os to el9, use osg 23 main repo, and fix maven vulnerability

---

cache/self_monitor.go
director/cache_monitor.go
director/director.go
director/director_test.go
director/monitor.go
origin/self_monitor.go
server_utils/test_file_transfer.go
xrootd/origin_test.go

Closes #1281 
The director won't reject redirect requests such as `/pelican/monitoring/xxx.txt`, `/pelican/monitoring/selfTest/xxx.txt`, and `/pelican/monitoring/directorTest/<wrong-prefix>.txt` for backward compat reason, but the rest of the requirements are implemented in this PR.

Tune up file transfer tests

---

server_utils/server_utils.go
server_utils/server_utils_test.go

When `WaitUtilWorking` was pointed at the OSDF Director (located in Madison) from a distant server, it couldn't get a response in the previously-configured 50ms. After peeking at this function, it doesn't seem like there's a good reason not to have a more permissive timeout.
I also adjusted the error message that was output from the previous circumstance. Setting up a distant cache resulted in saying "Server director <url> did not startup after 10s of waiting," which makes it seem like the cache is trying to start up a director.
Closes #1324

Increase `WaitUntilWorking` transfer timeout and adjust error message

---

registry/custom_reg_fields.go
registry/registry_db.go
registry/registry_db_test.go
registry/registry_test.go
registry/registry_ui.go
registry/registry_ui_test.go
swagger/pelican-swagger.yaml
test_utils/utils.go

Fixes #1220 
This is built upon the existing `GET /registry_ui/namespaces` API with an additional query parameter `legacy`. By default the API ignores any legacy registrations, but with `?legacy`, it will only display the legacy registrations. Note that you may pass the parameter either in `legacy` or `legacy=true`.
@CannonLock  The idea for the UI is to render a list of legacy registrations as a separate table and allow registry admin to edit/delete those registrations.

Display legacy namespace registrations in the registry web UI

---

director/director.go
director/director_test.go
xrootd/resources/xrootd-cache.cfg

The `pelican.timeout` / `X-Pelican-Timeout` headers should be passed by the director in its redirect and enabled in the cache config.
This (and a corresponding PR for `xrdcl-pelican`) will allow the client to differentiate between an unresponsive origin and an unresponsive cache.

Add support for `pelican.timeout`

---

.goreleaser.yml

Note that it is not installable on debian:latest or ubuntu:22.04 because they do not have the required version of xrootd.  It does install on ubuntu:24.04 (ubuntu:latest).
Closes #1272

Build deb pelican-server package and make sure it pulls in its required dependencies

---

client/director.go
client/errorAccum.go
client/handle_http.go
client/handle_http_test.go
client/main.go
client/util.go
cmd/plugin.go
cmd/plugin_test.go
config/config.go
config/resources/defaults.yaml
docs/parameters.yaml
local_cache/cache_linux_test.go
local_cache/cache_test.go
param/parameters.go
param/parameters_struct.go
test_utils/utils.go

This PR tracks whether there was a cache hit or miss based on the `Age` header in the server response.  The goal is to provide some indication to users in the hold message as to why their transfer failed -- was it a slow origin or a slow cache?  (The assumption is if it was a cache hit and a slow transfer then the cache is at fault.)
Also in this PR:
- Minor cleanup of the debug log messages when doing transfers.  Less repetition; do not print caches that we won't ever use.
- Fix the pre-transfer queries to selected cache hosts; particularly, put caches that respond with an error to the back of the list.
- Send correct header for PROPFIND request.
- Fix a small "airplane mode" issue causing tests to fail when there's no internet connectivity.

Report cache hits/misses

---

config/config.go
config/config_test.go

@haoming29, I came across these old deprecation warnings, and thought they were old enough that we could safely clean them up. If you disagree, you can close the PR as `wontfix` and we can open a separate issue to remove them in a later release.

Cleanup a few deprecation warnings from the old Federation.NamespaceUrl config key

---

.mailmap

`git shortlog -se` provides interesting statistics about the repo.
Unfortunately, it seems my and Emma's git configuration differs from host to host and it doesn't aggregate the contributions correctly. The `.mailmap` file instructs `git` to correctly merge these entries when calculating authorship.

Add simple mailmap file

---

.github/workflows/test.yml
config/config.go
config/config_test.go
config/config_validation.go
config/config_validation_test.go
docs/parameters.yaml
generate/param_generator.go
param/parameters.go
param/parameters_struct.go

It turns out Pelicans are picky birds, and they only like eating config options they recognize. Instead of feeding our beloved bird things it doesn't like and can't eat, this PR warns users when config options that are passed via config files or env vars that are unrecognized. Ewww!
This is accomplished by adding a mapstructure value to entries in our generated param.Config struct consisting of each field's lowercased name, and then using that to match against viper keys read in from config. When a viper key exists and can't be mapped to a field name in param.Config, we add the key to a list that is passed to the user as a warning.
To test, try passing some garbage values in your config file, or passing something like `PELICAN_BAD_KEY` through the environment.
Closes #998

Warn users about unrecognized configuration

---

director/resources/geoip_overrides.yaml
director/sort_test.go

The tests didn't catch a bad IPV6 CIDR block that I passed as "this should be good". The updates fix the tests and fix the IPV6 address.

Fix tests for GeoIP overrides

---

director/advertise.go
director/advertise_test.go
director/cache_ads_test.go
director/director.go
director/director_api_test.go
director/director_test.go
server_structs/director.go
server_structs/director_test.go
xrootd/authorization.go
xrootd/authorization_test.go

NamespaceAdV2 has a weird duplication between `ad.PublicRead` and `ad.Caps.PublicReads`. Since we have the `Capabilities` struct, we should switch to populating that and to checking that. This will have to be done over several releases because this will break backwards compatibility if an old director (prior to whichever release this PR ends up in) tries to receive an ad from a new Origin.

Start phasing out NamespaceAdV2.PublicRead in favor of NamespaceAdV2.Caps.PublicReads

---

.goreleaser.yml

See #1271. This puts the contents of the pelican tarball into a pelican-<version>/ directory and also has the pelican apk/rpm/deb create and take ownership of the /etc/pelican directory.

Various GoReleaser artifact tweaks

---

config/config.go
config/config_test.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go

This adds the ability to define "Continue" directories in your config, where doing so causes Pelican to merge in any additional files in that directory. For example, if my `/etc/pelican/pelican.yaml` has the line `Continue: /foo`, this addition causes Pelican to merge any extra yamls located in `/foo`. If `/foo/config.yaml` further defines `Continue: /bar`, Pelican will then look to `/bar` for extra config.
Config files in a "Continue" directory are parsed according to lexicographical order. This does not currently support adding entries to viper slices, so, for example, if `/etc/pelican/pelican.yaml` defines:
```
Origin:
Exports:
- < values for export 1 >
Continue: /foo
```
and `/foo/config.yaml` defines:
```
Origin:
Exports:
- < values for export 2 >
```
the exports slice will be …

Add "Continue" method for config file patching

---

director/advertise.go
director/advertise_test.go

Fixes #1406 
A quick check can be running the director in `osdf` mode, then go to `/api/v1.0/director_ui/servers`. Look for `unl-origin.nationalresearchplatform.org:1094` which should export 4 namespaces, and `sdsc-origin.nationalresearchplatform.org:1094` which should export 11 namespaces.

Consolidate multi-export topology origins

---

config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

Caches take too long to pull permissions changes from upstream origins (12hours, from Xrootd's default `acc.authrefresh 43200`). This sets the default refresh time to 5m and adds a mechanism for admin to adjust as needed.
Closes #1335

Add mechanism to change authfile reload intervals

---

docs/parameters.yaml
origin/globus.go
origin/globus_client.go
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

This adds a generic config for adding an bearer token to the `Authorization` header on requests from the origin to an http backend. In particular, this is needed for Globus collections.
Closes #1413

Add bearer token config to HTTP backends for Globus compat

---

.github/workflows/pre-commit-linter.yml
director/prom_query_test.go

Our linter GHA on the main branch is failing, and this PR addressed the issue by fixing the uncaught import error.

Fix golangci linter on imports

---

director/monitor.go
director/stat.go
metrics/director.go

Closes #1431 
To test, first spin up your director. If you'd like to also test a local file, then you'll need to spin up your local federation (director, registry, origin)
* Get the test file through the origin: `curl -k -o /dev/null https://localhost:8444/api/v1.0/director/ospool/uc-shared/public/OSG-Staff/validation/test.txt`. Assuming that your local director runs at `8444`
* Check the Prometheus `/metric` endpoint to confirm the value. Login to your director web UI and go to `https://localhost:8444/metrics`. You should see two metrics named `pelican_director_stat_active` and `pelican_director_stat_total` where the value of `pelican_director_stat_total` should be 1 (for the test file you just queried)

Add two Prometheus metrics for director `stat` queries

---

director/advertise.go
director/advertise_test.go
registry/registry_db.go
server_utils/server_utils.go
utils/web_utils.go

This PR is to address the issues raised by @bbockelm in #1445 with regards to moving around functions and structs

Moved utils.GetTopologyJSON and related structs to server_utils package

---

launchers/registry_serve.go
metrics/registry.go
registry/registry_api.go

This PR implements a metric for tracking the number of participating institutions in OSDF mode. It includes:
- A goroutine that periodically collects and updates the institution count metric.
- Support for fetching institutions from both configuration values and a URL.
- Integration with Prometheus to expose the metric as `pelican_osdf_institution_count`.
This PR addresses the issue #1424

Add OSDF Institution Count Metric Collection

---

director/cache_ads.go
director/director_api.go
director/stat.go

The fix in #1438 only partially fixed the issue. With the patched binary, the director runs OK at the server start, until some point in the future another deadlock happens.
The Prometheus log in the past several day shows this pattern:
where stable lines means no deadlock and sudden drops are server restarts.
Thanks for the `pprof` added in 7.9.1, after digging into `goroutines` stack trace, it seems that there's a deadlock in `healthTestUtil` itself, where we acquire the lock to clean up one instance of healthTestUtil at cache eviction, we call` ctx.Cancel` to cancel the goroutine in the errgroup that belongs to that serverAd, then we `Wait()` on the errgroup to return. However, the function in the goroutine may acquire the same lock to update the test result. If we call `Wait()` and …

Fix health test deadlock

---

director/director_ui.go
director/director_ui_test.go
director/stat.go
director/stat_test.go

Fixes #1464 
For topology legacy origins, they have `authUrl` for protected objects and `url` for public objects. However, our `stat` call only checks against `url` as the base url of the object. This PR added an additional attempt to try the `authUrl` endpoint if we get error from the first two attempts (first one is `url` endpoint with digest requested, second one is to get rid of digest)

Retry auth endpoint if the `stat` timeout

---

metrics/xrootd_metrics.go
metrics/xrootd_metrics_test.go
utils/utils.go
utils/utils_test.go
xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg

This PR addresses #1425. This PR adds a IP address (netwrok) label to XRD access metrics (xrootd_transfer_readv_segments_count, xrootd_transfer_operations_count, and xrootd_transfer_bytes). This PR also updated some tests to handle the new label. This PR also addresses comments from @bbockelm in PR #1445.

Add IP address (network) label to XRootD access metrics

---

metrics/shoveler.go

As @bbockelm reported, the current logging setup in the shoveler logs every message it sent to the MQ, which causes lots of noises at the debug level. This PR removed logging such messages.
Also, currently the `version` field in the message sent to MQ is empty, due to the fact that we shoveler is now part of Pelican code. This PR set the related shoveler build info with that from Pelican

Removed logging shoveler message at debug level and fix empty version

---

director/director.go
director/sort.go
director/sort_test.go
director/stat.go

Closes #1308 
The idea is that for redirectToCaches, if `stat` is enabled (by default):
* Query **all** origins and caches that claim to serve the namespace
* If no caches claim to serve the namespace (not that they have the object), then iterate queried origins that claim to have the object and check if they enable "DirectRead". If none, then return 404. If there is, use the first one as the object server.
* If there's one or more caches claim to serve the namespace, we sort the caches based on existing GeoIP, but then sort again by availability. Caches that have the object have higher priority in the list
* Return the sorted caches

Add `stat` query to `redirectToCaches`

---

github_scripts/osx_install.sh
images/Dockerfile
images/dev.Dockerfile

@turetske, I'll cut a `v7.9` release when this is passing tests and gets merged. It fixes a bug in the S3 plugin that mishandles S3 service URLs with a trailing slash. Contents of the bugfix can be found [here](https://github.com/PelicanPlatform/xrootd-s3-http/pull/37)

Update S3 backend version to v0.1.4 to fix trailing / bug in URLs

---

client/handle_http.go
client/handle_http_test.go

A missing conditional caused stash:// URLs to not trigger metadata discovery (subsequently causing topology to be used instead of the director).
This fixes the conditional and adds a regression test.

Populate director information for stash:// URLs

---

cmd/plugin.go
cmd/plugin_test.go

The destination file name was being overwritten by `parseDestination` when `pack=auto` was being set.
Move the destination file name logic to the `parseDestination` helper function, correct it, and make sure there's unit test coverage for the name generation.

Ensure unpack directory name is correct

---

client/errorAccum.go
client/handle_http.go

Goal is to improve the user understanding of the error messages:
```
the existing TCP connection was broken (potentially caused by server restart or NAT/firewall issue)
```
Also marked these are retryable.
No unit tests here -- it's not clear how to inject TCP-level problems into the testing.

Rewrite TCP connection reset / broken pipe messages

---

config/resources/defaults.yaml
director/director.go
director/stat.go
director/stat_test.go
local_cache/cache_test.go
metrics/director.go

Fixes #1474 
This PR fixes two issues related to `stat`:
- If `stat` uses AuthURL instead of URL due to Topology server authentication, there is a mismatch when we compare the `stat` result and available serverAds and generate the final server response, thus a successful stat returns 0 matched servers and a 404
- Shadowed variable name in the `stat` goroutine that gave back wrong URL in both log and as the `issuer` url
- The default `300ms` timeout is too short for the Origins distant from the director, and this PR raised default value to 1000ms 
With this patch in, we should be able to fix most of the 404s the director returned in the production

Fix various issues in `stat`

---

client/acquire_token.go

Two failure cases were combined in a conditional; this makes each unique so there's clearer messages on failure.
(This tweak was used to debug the director failing to send a credential generation header)

Tweak credential generation error messages to distinguish cases

---

director/director.go
director/director_test.go
metrics/director.go
utils/utils.go
utils/utils_test.go

This PR addresses issue #1483. This PR adds a new middleware to collect and parse the user-agent from client requests and increment a counter metric with the label being the client version.

Implemented client version metric

---

images/Dockerfile
images/dev.Dockerfile

Things in osg-testing started breaking, and I crave stability in this wild, uncertain world. Let's go back to installing xrootd from the `osg` repos and remember a time when life was simpler.
Doing so seems to fix the prod container's inability to build xrdcl-pelican due to CMake errors complaining about bad function overrides.

Switch xrootd source in prod container from osg-testing repo to osg

---

director/cache_ads.go
director/sort.go
director/sort_algorithms.go
director/sort_algorithms_test.go
director/sort_test.go

The underlying issue relates to the "Kansas" problem, where valid IP addresses that don't have a known GeoIP resolution are assigned the default Kansas lat/long.
This approach is _slightly_ different when compared to the GH issue, but I think it resolves the issue in a simpler fashion. Rather than incorporate logic that says "if Kansas AND large accuracy radius", this only looks at accuracy radius because a high radius, set to 900 km here, is as good as "I don't know where this IP comes from".
When we see such a radius, we set the lat/long to null (0,0) -- and this happens for both client IPs AND server registrations.
The sort logic was modified to detect any null lat/long and create a random, negative distance weight for these. The result is we sort these to the end of our list. If the …

Modify sort algorithm to treat unresolvable IP addresses as random

---

images/Dockerfile
images/dev.Dockerfile

This gets us a fixed patch to improve S3 origin performance by switching to the `osg-testing` repos for xrootd installation.
Closes #1552

Switch container builds to use osg-testing instead of osg repos

---

client/fed_test.go
client/handle_http.go
cmd/object_ls.go
cmd/root.go
github_scripts/get_put_test.sh

This PR addresses two issues, both involving cleaning up client interaction and responses.
The first changes "ls -L" to "ls -l" This also changed the log flag to "-L" to avoid conflicts.
The second changes the output of "ls -l" and "stat" to return the full object name with the namespace rather than just the top level name.
closes #1498 
closes #1497

Client cleanup

---

config/resources/defaults.yaml

Direct reads are now enabled by default in pelican origins

Origins now have directreads on by default

---

config/resources/osdf.yaml
director/director.go
director/prom_query.go
docs/parameters.yaml
local_cache/local_cache.go
param/parameters.go
param/parameters_struct.go
registry/custom_reg_fields.go
xrootd/launch.go

When a requested object matches a pre-configured set of paths, then indicate to the cache it should turn on client X509 authentication.
This fixes support for legacy OSDF namespaces which may require the cache to use client X509 authentication when requesting from the origin because a token is not otherwise available.
Fixes #1562

Selectively enable client X509 authentication

---

github_scripts/osx_install.sh
images/Dockerfile
images/dev.Dockerfile

This new xrds3 version contains the first pass at fixing PUTs against S3 origins. In particular, it implements the S3 multipart upload flow. See https://github.com/PelicanPlatform/xrootd-s3-http/pull/41 for more information.

Update xrds3 to v0.1.6 to fix S3 multipart PUTs

---

web_ui/frontend/README.md
web_ui/frontend/dev/.env.template
web_ui/frontend/dev/image/Dockerfile
web_ui/frontend/dev/image/crontab
web_ui/frontend/dev/image/entrypoint.sh
web_ui/frontend/dev/image/login.sh
web_ui/frontend/dev/image/nginx.conf
web_ui/frontend/dev/run.sh

- Add the ability to proxy prometheus requests to an active service for real data
- Works by running a cron to get a new jwt and add it to the proxy auth headers every 30 minutes

Add Proxy for active services

---

images/dev.Dockerfile

Compiling xrootd greatly slows down the build and is no longer necessary since OSG has builds for both X86 and ARM in the osg-testing repos.

Do not compile xrootd when building the dev image

---

config/resources/osdf.yaml
director/advertise.go
director/advertise_test.go
director/resources/mock_topology_downtime_template.xml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
registry/registry_db.go
server_structs/topology.go
server_utils/server_utils.go

This changes the overall approach for grabbing downtime information from Topology. Previously, we generated the list of downed servers by getting a diff of the servers returned in the namespaces JSON when querying that endpoint with `?include_downed=<0/1>`. The issue with this approach is that Topology services marked as Pelican services are explicitly excluded from the returned JSON.
However, Pelican services that are recorded in Topology are still included in the downtime URL, so this new approach grabs the list of resource names from that instead. That was probably the right approach all along, but topology endpoints remain inscrutable ¯\_(ツ)_/¯
This also corrects a documentation issue that claimed filtered servers could be added in the Director using their hostname. In fact, they need …

Fix topology downtime integration by using downtime URL and not ns JSON

---

client/acquire_token.go
client/bearer_auth.go
client/bearer_auth_test.go
client/fed_test.go
client/handle_http.go
client/handle_http_test.go
client/handle_ingest.go
client/main.go
client/main_test.go
go.mod
go.sum

The token tracked internally through a transfer is now a standalone struct instead of a string.  The `get` method that produces the string needed for transfers will check the validity of the current token and, if it's expired, iterate through the environment to find a new one.
The goal is long-lived transfers will be able to acquire a fresh token, as needed, from their environment (or from the token issuer) instead of using the expired one.

Convert the token from a string to an object

---

github_scripts/osx_install.sh
images/Dockerfile
images/dev.Dockerfile

This update, among other things, includes the ability to handle X509 auth when caches speak to origins.

Update xrdcl-pelican to v0.9.4

---

client/director.go
client/director_test.go
client/fed_linux_test.go
client/handle_http.go
client/main.go
client/sharing_url.go
cmd/config_mgr.go
cmd/object_sync.go
director/director.go

This adds a "rsync-like" interface, `object sync`, to the command line client.  Example:
```
pelican object sync pelican://localhost:8444/tmp/test /tmp/download
```
This can be called multiple times; partially-downloaded files will be completed and completed files will be skipped (similar behavior on uploads).
The intent for this functionality is to allow someone to do a transfer of a large number of files into the OSDF from a host that might be rebooted or otherwise interrupted.
This includes multiple small bugfixes discovered in the client while testing, including:
- Fixed client hang for transfers of empty directories.
- Fixed client hang if the transfers finish before the directory walk finishes
- Do not consider a zero-sized file an error.
- If the director notices a namespace …

Add "sync" functionality to the client

---

cmd/object_ls.go
cmd/root.go
github_scripts/get_put_test.sh

Switched the 'ls -L' and the logging '-l' flags

---

client/acquire_token.go
client/fed_test.go
config/issuer_metadata.go
xrootd/launch.go

This tweak will cause the client to search for the issuer's private key in its local configuration and auto-generate a token as needed.  (On simple origin deployments, it's not uncommon for the origin to be run by a single individual who has the private key)
This prevents the user (in this specific case) from needing to know how to create tokens to use Pelican: simply drop the private key into `~/.config/pelican/issuer.jwk` and go!

Auto-generate token if the issuer is available

---

xrootd/resources/xrootd-origin.cfg

It looks like the path style directive is scoped to each s3.begin/s3.end block, which is why the previous declaration failed for multiple buckets. Technically it would succeed if all the buckets were supposed to use virtual paths (the default), but in the path-style case, only the first bucket inherited the value. Other buckets reverted to the default.
This commit scopes the path style to each origin export to guarantee each of the request URLs generated by XRootD follow the same bucket convention.
The easiest way to test this is probably by starting an Origin with full debug logging at the origin/xrootd level and point it at two public AWS buckets. Here's origin config I used:
```
Logging:
Level: debug
Origin:
Xrootd: trace
Http: debug
Origin:
S3UrlStyle: "path"
S3Region: "us-east-1" …
```

Move s3 path style into s3.begin/s3.end blocks

---

director/director.go
director/sort.go
director/sort_test.go

This PR aims to improve the Director's cache sorting algorithm, specifically in the case of clients whose GeoIP resolution can't be determined.
With these changes, client IPs that don't have an entry in MaxMind entry (or that can't be parsed as an IP in the first case) are assigned a random location in the contiguous United States. Doing this makes the Director behave as though it knows the client's true location by delivering caches sorted based on the new location. This differs from the previous algorithm, where those IP addresses resulted in completely random cache sorting.
When a client IP is assigned a random location, that location is cached for 20 minutes, unless refreshed by further client interactions. This is done so that repetitive client requests get a consistent cache …

Assign unknown client IPs a random geo ip in the contiguous US & cache the result

---

client/handle_http.go
client/main.go

Prior to the new token generator object, an empty / missing token was a no-op.  After it, the token generator could potentially try to acquire a token.  Even though it was non-fatal when no token was available, the error messages were awfully confusing.
Now, if no token is required, we explicitly nil out the token generator object, preventing the request.

Null the token generator pointer for public reads

---

cmd/object_sync.go

Exactly what the title says, which is what the original PR (#1586) for the `sync` sub-command was aiming for:
> This can be called multiple times; partially-downloaded files will be completed and completed files will be skipped (similar behavior on uploads).
This PR addresses issue #1611.

Modify the `sync` sub-command to sync based on size differences (#1611)

---

cmd/object_copy.go

Stashcp needs to determine the copy direction dynamically, so we can't treat the source as a defacto Pelican/OSDF URL -- sometimes we're dealing with a GET, sometimes a PUT. The function `UrlWithFederation` was introduced with the intention of standardizing the way we handle gets/puts that don't conform to our `<pelican/osdf>://` url specification by building a pelican URL by default. This is safe to do when we know the direction of transfer, but copy commands _require_ a schemed url to determine direction. Because of this, all schemeless paths for copies _must_ be treated as local.

Don't construct Pelican URLs for copy commands

---

director/advertise.go
director/advertise_test.go
director/director.go
origin/advertise.go
server_structs/director.go
server_structs/director_test.go

This moves us away from using something like `ad.Writes` in favor of `ads.Caps.Writes` by using our capabilities struct across the board where appropriate.
The work in this PR has been spread out over 3 releases to minimize potential impact to backwards compatibility issues, with the 7.11 release targeted for final breaking changes.
Closes issue #1367 
Closes issue #1368

Use capabilities structs in various types of server ads

---

server_structs/director.go

This reverts commit ba186d23895835285d79b118feabbdec22a902cc. I thought this change would be non-breaking but I was WRONG.
I'll follow up later today with another PR that handles potential breaking changes so we can stage this change over the next release or two.

Revert "Update JSON representations of Capabilities structs to match internal"

---

client/acquire_token.go

When generating a token, particularly for the `sync` command, we want to have the ability to overwrite incomplete remote files.
Fixes #1618

Switch write capability to `storage.modify`

---

images/Dockerfile
images/dev.Dockerfile

@williamnswanson, as you requested
When this is patched into 7.10, it should also cause the container builds to pick up xrootd 5.7.1 (unless there's some weird caching going on that I'm unaware of).

Install sssd-client in dev/prod containers

---

config/config.go
images/entrypoint.sh
launchers/launcher.go

This PR fixes #1502
- It incorporates Goose output into the logging system. Goose has two levels of output: `info` and `fatal`, which are now mapped to the corresponding levels in `logrus`.
- The build information at server startup is now logged as part of the `info` logs.
- Removed unwanted echoes when the origin starts in `entrypoint.sh` and suppressed the output from running the script `boot.qdl` inside `entrypoint.sh`. The `boot.qdl` script starts a new OA4MP issuer and always exits with a non-zero status, which appears to be the expected behavior for now.

Cleanup origin startup stdout

---

systemd/osdf-cache.yaml

The issue causing caches to have to be told the location of the "origins" director has long since been solved.

Stop specifying Federation.DirectorUrl in osdf-cache config

---

images/Dockerfile

In a previous PR, I installed `sssd-client` into the wrong intermediate container. This should make it available in all the finished containers.
`sssd-client` is needed by multiuser origins that plug into LDAP to gather user information.

Move sssd-client installation to final stage builder

---

.github/workflows/build-prod-container.yml

No longer need to grab the branch as the tag is still valid. Lets us remove the if check for how the workflow was called.

Release prod containers

---

systemd/osdf-cache.yaml
systemd/osdf-origin.yaml

The asymmetry was bothering me. Though it's unclear to me /why/ we need separate run dirs? Because we can't serve different federations with single origin/cache services now?

Align OSDF RunLocation hierarchy with Pelican components

---

server_structs/director.go
server_structs/director_test.go

This change fixes the stuff I broke in commit ba186d2 by handling previously- unconsidered backwards compatibility issues. Now, unmarshalling the NSAdV2 struct will correctly populate capabilities even if the source JSON uses the old style of capabilities.
This also fixes the capabilities displayed for each origin at the Director.
In addition to passing unit/CI tests, the reviewer should verify that they can start a federation with an Origin and Director based off of this branch AND an Origin based off of a different branch. Both origins should successfully advertise to the Director at the same time, and they should display the correct, updated capability names (e.g. no FallbackRead).

Switch to use new Caps struct but still handle old JSON from Director

---

director/cache_ads.go
director/director.go
director/director_test.go
director/sort.go
director/sort_test.go
metrics/director.go

This PR aims to fix issue #1605. This PR implements a new metric called `pelican_director_geoip_errors`. This metric has the following labels:
- `network` - this is the client's network
- `source` - this is the source of the error, it can take the value of `client` or `server`
- `project` - this is the project that the client sends along in the User-Agent
The goal is to integrate this metric into the WebUI, as addressed in #1548.

New GeoIP Error Metric

---

client/fed_test.go
client/resources/test-https-origin.yml
cmd/origin.go
cmd/plugin_test.go
cmd/resources/test-https-origin.yml
docs/parameters.yaml
server_utils/origin.go
xrootd/fed_test.go
xrootd/resources/test-https-origin.yml
xrootd/resources/xrootd-origin.cfg

This PR accomplishes two things -- first, it plumbs a few of the https backend components through the CLI, allowing users to serve minimal https origins without writing a configuration yaml.
Second, it adjust the https backend to use storage prefixes. Consider the following configuration:
```
Origin:
StorageType: "https"
HttpServiceUrl: "https://data.lhncbc.nlm.nih.gov/public"
Exports:
- StoragePrefix: "/Tuberculosis-Chest-X-ray-Datasets/Montgomery-County-CXR-Set/MontgomerySet/CXR_png"
FederationPrefix: "/my-prefix"
```
The adjustments cause a request for object `/my-prefix/MCUCXR_0005_0.png` to be converted to a libCurl request in the Origin for `https://data.lhncbc.nlm.nih.gov/public/Tuberculosis-Chest-X-ray-Datasets/Montgomery-County-CXR-Set/MontgomerySet/CXR_png/MCUCXR_0005_0.png` …

Plumb HTTPS backend through CLI and adjust it to use full storage prefixes

---

cmd/fed_serve_cache_test.go
config/resources/defaults.yaml
director/cache_ads.go
director/director.go
director/stat.go
director/stat_test.go
docs/parameters.yaml
local_cache/cache_test.go
metrics/director.go
param/parameters.go
param/parameters_struct.go
utils/errgroup.go

This PR enables the director to keep a local cache of job existence query results.
That is, if it issues a HEAD to see if a remote cache already has an object, then keep around that result for a minute and elide future queries.
This also takes the opportunity to rename and split the stat option, fixing #1566.

Enable caching of object existence queries

---

config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
web_ui/prometheus.go

This PR addresses issue #1640. This PR adds a new configuration called `Retention`. This PR defines the default retention time as 15 days.

Configurable Prometheus Retention

---

client/fed_linux_test.go
client/handle_http.go
client/main.go
cmd/object_sync.go
cmd/plugin_test.go

This code adjust the sync behavior for transfers to and from origins. Only fully tested on POSIX right now due to S3 PROPFIND/LS issues.
The cases and behavior that should occur are discussed here: #1638 - For the benefit of the reviewer, here is the list of test commands I ran with the various caveats about the files/dirs/collections/objects. Be sure you match the various different existence cases of each test.
| Left Argument Type | Right Argument Type | Command | Expected Result | Description |
| ----------  | -------------------- | --------------------- | ------ | ------------ |
| Collection | File (which exists) | `/pelican object sync pelican://3695d3c19055:8445/my-origin/test origin.go` | FAILURE | Trying to sync a remote collection with a file is expected to fail|
| Collection | …

POSIX Sync Handling

---

github_scripts/osx_install.sh
github_scripts/pelican_protocol.patch

Adding back in the accidentally removed poller fix for the MacOSX and the pelican protocol. Should hopefully make Mac tests more robust.

Macos poller fix

---

oa4mp/serve.go

see the linked issue for the goal of this PR
How I test it:
(1-4 corresponds the blue dots in the screenshot)
1. delete `/opt/scitokens-server/var/storage` directory if it exists
2. build and run the pelican project. verify if the above directory gets created
3. check the permissions of parent directory is 0755
4. check the permissions of leaf directory `/opt/scitokens-server/var/storage` is 0700

correct OA4MP storage directory permission

---

docs/pages/install/linux-binary.mdx

Assumed focus would be on x86_64, so made that the "main" naming used throughout.
Added note to PATH section about changing the folder name if using ARM, to mirror previous section.

Correcting inconsistent use of x86_64 vs arm64

---

director/director.go
director/director_api.go
launchers/director_serve.go
metrics/director.go

This PR addresses issue #1636. This PR removes unnecessary labels from the metric and changes the metric to a gauge. This metric should now reflect at any given moment, how many servers are connected to the director.

Improved `pelican_director_server_count` metric

---

.github/workflows/test.yml
github_scripts/osx_install.sh

Update MacOS GHA test env to fix deprecation error

---

server_structs/director.go
server_structs/director_test.go

Instead of targeting NamespaceAdV2 like I did previously, this change moves the unmarshal logic to the level of the Capabilities struct. Why I didn't do that in the first place? I couldn't tell ya
In addition, I now test that JSON for ServerAd and OriginAdvertiseV2 (which may also arrive to the Director with old/new capabilities) unmarshal correctly.
Closes #1715

Unmarshal Capabilities correctly in all structs that use them

---

client/fed_linux_test.go
client/handle_http.go
cmd/plugin_test.go

Currently, when trying to upload an object without the recursive option and a directory path is provided, Pelican does not handle this gracefully. It outputs an error because it attempts to read a directory, and it also creates an empty file at the destination in the process.
This issue affects both `pelican object put` and `pelican plugin` commands since the same underlying function manages object uploads.
When Condor attempts to transfer a directory, it iterates through it and places both directory paths and file paths in the infile. Attempting to transfer a directory without the recursive option causes Pelican to create an empty file at the destination, which breaks the code.
This PR adds an `IsDir` check before initiating an object transfer. This update resolves both issues:
1. …

IsDir Check to Prevent Creation of Empty Files on Object Uploads

---

director/director.go
director/director_test.go
metrics/xrootd_metrics.go
utils/utils.go

This PR addresses issue #1635. This PR moves the project extract logic outside of the director and adds to the `utils` package. This allows us to use the same logic to get the project from the `appinfo` provided by XRootD. The proj label will be empty if there is no project in the user-agent.

Fix `proj` label setting bug

---

server_structs/director.go
server_structs/director_test.go

I'm hoping this is enough to revert any of the breaking changes introduced during the 7.11 rollout. As much as I'd like to move forward with these changes and fix things to make them backwards compatible, that started becoming more complicated than I'd like for something I consider urgent.

Fix caps 7.11

---

director/director_ui.go
director/director_ui_test.go
swagger/pelican-swagger.yaml
utils/utils.go

Add director endpoints to facilitate easier mapping between endpoints and the servers that work with them.
- /servers/:name
- /servers/:name/namespaces
- /namespaces

Add director endpoints

---

docs/parameters.yaml

Fixes #1726: Set default value for empty stringSlice to `[]` in documentation

Set default value for empty stringSlice to [] in docs

---

docs/pages/install/macos.mdx

In the current readme, `curl` and `tar` refer to different osx architectures. This PR makes them match.

Update macos.mdx to make architectures match

---

web_ui/frontend/components/CardList.tsx

If you removed an item from the cardlist so that the page is empty afterwards then, and only then, change the page
Closes https://github.com/PelicanPlatform/pelican/issues/1473

Decrement page if empty on Cardlist

---

.github/workflows/test.yml
local_cache/cache_test.go

This has been a flaky test for too long, and I've even seen it start failing locally when I'm running heavy Docker processes in the background. Clearly something just needs a bit more time to do its thing.

Attempt longer ctx deadline in flaky localcache test

---

cmd/main.go

Closes #1600 by adding pelican_plugin as an acceptable binary name for plugin.

Add pelican_plugin as an acceptable binary name for plugin

---

cache/cache_api.go
cache/cache_api_test.go
cache/self_monitor.go
client/fed_test.go
cmd/fed_serve_cache_test.go
config/config.go
docs/parameters.yaml
fed_test_utils/fed.go
local_cache/cache_test.go
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-cache.cfg
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

This PR tries to clarify some of the language surrounding these configuration options and removes mention of `Xrootd.Mount` which has no effect on caches.
Closes #1664

Update/clarify `Cache.<Data/Meta>Locations` documentation

---

config/resources/defaults.yaml
docs/parameters.yaml
images/dev.Dockerfile
param/parameters.go
param/parameters_struct.go
xrootd/launch.go

Valgrind is incredibly useful C++ debugging tool to check for leaks and other memory usage errors.
However, it also makes the application incredibly slow: it's often a 20x (or more) performance penalty.  Xrootd caches hit the timeouts frequently.
This PR adds a few hidden tunables to allow us to increase timeouts enough for xrootd to run under valgrind.  It also adds some standard C++ debugging tools into the development container.

Tuning Pelican for running xrootd under valgrind

---

config/config.go
launchers/launcher.go

Fixes #1720: On server startup, prints the full configuration after applying defaults if log level is INFO or higher. On client initialization, prints client-specific configuration when log level is DEBUG.

Include defaults in debug config print

---

docs/parameters.yaml

I copied the documentation from the [XrdSciTokens documentation](https://github.com/xrootd/xrootd/tree/master/src/XrdSciTokens) and made some light edits for consistency.

Fix documentation for the `Origin.Scitokens*` parameters

---

director/cache_ads.go
director/sort.go
director/sort_test.go

This PR addresses issue #1717. This PR fixes the unnecessary logging and separates out the GeoIP error metric collection. This is achieved via using a custom error type. This new error type carries along the prometheus labels. When we observe this new error type, we then update the metric with the passed along labels.

Fix OSDF Director startup warnings and separate GeoIP metric collection

---

.github/workflows/post-release.yaml

Hits the release webhook toggling dl.pelicanplatform.org to pull down the newest release.

Toggle dl webhook on release

---

.github/workflows/test-template.yml
.github/workflows/test.yml
.goreleaser.yml
images/Dockerfile
images/entrypoint.sh
lotman/lotman.go
lotman/lotman_linux.go
lotman/lotman_test.go
lotman/lotman_ui.go
lotman/resources/lots-config.yaml

This PR creates a second server binary, which for now only enables Lotman by passing the `lotman` build tag through goreleaser. This is necessary for the long-term development goals we have to use Pelican as the distribution layer for lotman configuration across caches.
Eventually we can also use this second binary to fine-tune which modules are built into clients or servers, which should make the HTCondor developers happy as well. For now, the new server binary replaces the regular binary only in cache containers, since that's where lotman is needed.
As for testing, I've tried to split our GHA test runner across the two binaries. This resulted in creating a workflow template that I can pass build tags/binary names to.

Restore lotman through splitting off a second server binary

---

images/Dockerfile
images/entrypoint.sh

- pelican and osdf go into /usr/local/bin
- pelican-server and osdf-server go into /usr/local/sbin
Fixes #1744

Docker images: Put binaries into standard locations

---

cache/advertise.go
director/director.go
director/director_test.go
origin/advertise.go
server_structs/director.go

This PR addresses issue #1725. This PR adds a version field to the server ad. The goal is use this version field in the future for monitoring purposes.

Add Version info to ServerAd

---

cmd/progress_bars.go

The overall effect of this PR is to make it so that the client displays progress bars only for "in progress" and "recently completed" transfers. For large, recursive transfers and syncs, this:
* Prevents noisy scrollback buffers.
* Bounds the number of progress bars being displayed to something closer to the number of worker threads and not the total number of objects being transferred, which in turn reduces the number of progress bars that must be removed from the terminal's display when the client exits.
To achieve this:
1. When each progress bar is created, we configure it to be removed when its "completed" event is triggered.
2. We enable each progress bar to trigger a "completed" event when we set its total size. (Because each progress bar was originally created with a size of zero, …

Remove each progress bar immediately upon completion

---

oa4mp/resources/policies.qdl

Both the SciTokens and WLCG profiles require that a scope's path components be URL encoded. When substituting for `$USER` and `$GROUP` in any authorization templates, we should ensure that the value being substituted in is URL encoded.
References:
* [QDL function reference](https://qdl-lang.org/pdf/function-reference.pdf)
* [SciTokens profile](https://scitokens.org/technical_docs/Claims)
* [WLCG profile](https://github.com/WLCG-AuthZ-WG/common-jwt-profile/blob/master/profile.md)

Escape user and group names in issued tokens (#1494)

---

web_ui/frontend/app/origin/page.tsx
web_ui/frontend/components/DataExportTable.tsx

- UI and UI backing updates to make sure its up to date
The current issue is that when you redirect from a corrected registration in the registry back to the origin you were registering the initial query from the origin is so fast that it misses the changes. 
This adds a UI loading bar that waits 5 seconds for a requery. If for some reason it takes longer then 5 seconds I also auto refresh these metrics every 5 seconds in the background so things will just switch over automatically in the UI.

Add a refresh interval to the origin exports

---

.goreleaser.yml

Prevent snapshot from incrementing version

---

.goreleaser.yml
config/config.go
config/config_default.go
config/config_linux.go
config/init_server_creds.go
docs/pages/federating-your-data.mdx
docs/parameters.yaml
launcher_utils/xrootd_servers.go
param/parameters.go
param/parameters_struct.go
systemd/10-osdf-defaults.yaml
web_ui/engine_test.go
web_ui/ui.go
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

Rename Server.TLSCertificate to Server.TLSCertificateChain

---

github_scripts/osx_install.sh
images/Dockerfile
images/dev.Dockerfile

Changes primarily affect the S3 backend, with big speedups for reads/writes and bug fixes that correct the way we parse some headers.

Bump containerized S3/HTTP backend version from v0.1.7 to v0.1.8

---

config/resources/defaults.yaml
docs/parameters.yaml
launchers/cache_serve.go
lotman/lotman.go
lotman/lotman_linux.go
lotman/lotman_test.go
lotman/resources/lots-config.yaml
lotman/resources/malformed-lots-config.yaml
param/parameters.go
param/parameters_struct.go
server_utils/server_utils.go
server_utils/server_utils_test.go
xrootd/xrootd_config.go

This gives caches the ability to inform Lotman of known namespaces, which Lotman can use to automatically create a (currently toothless) purge policy.
A lot of the work here involved figuring out how to specify named lot policies through our yaml config. Examples of what I came up with can be found in docs/parameters.yaml. Outside of that, some changes involved figuring out how to merge local config with potentially-discovered config.
Until Pelican actually uses the new purge code with the Lotman purge plugin, none of this really does much other than set up a database. For now, this lets us set up most of the lot config in a cache through Pelican, and then the last bits for testing purge stuff need to be configured manually. Until then, the actual purge ordering portion of a policy isn't …

Enable auto-generation of Lotman policies

---

client/director.go
client/director_test.go
client/fed_linux_test.go
client/fed_test.go
client/handle_http.go
client/main.go
client/resources/origin-with-and-without-write.yaml
cmd/config_mgr.go
cmd/object_delete.go
director/director.go

This PR closes #1685 by implementing an object delete command.
The object delete command is not openly supported and is marked hidden. It deletes data from the origin and does not clean data from caches the data might have propagated to.
The object delete command supports the recursive option to delete collections.

Implement Object Delete Command

---

.github/workflows/build-prod-container.yml
.github/workflows/release.yml
.goreleaser.yml

Since we now plan to give release candidates tags suffixed with `-rc.X`, where X indicates the release candidate number, we also need to run the release actions for these tags.
The release.yaml action generates artifacts for our github repo and marks things as a pre-release, so we definitely want it to trigger on release candidate tags. The build-prod-container.yaml action creates our containers, and since these are used by integrations to test release candidates, we also need those too. It looks like the triggers for dev container builds will already match against release candidate tags (if I can mentally parse the regex) so we should be fine there.

Trigger release actions if tag matches new `-rc.X` prerelease tags

---

.goreleaser.yml
scripts/preinstall-alpine.sh
scripts/preinstall.sh

#1860 ; this creates a system user and group named `pelican`; it also pre-creates some directories that Pelican won't be able to create after dropping privs to the `pelican` user.

Packaging: create pelican user and group and some directories for it

---

images/Dockerfile

Since we're not building it from source, pelican-plugin.conf, which we copy into a later image, is not in /usr/local so that path needed to be fixed too.
Closes #1592

Install xrdcl-pelican from osg-testing instead of building it from source

---

.github/workflows/release.yml

Previously, the action would trigger on a tag like `v7.12.3` and would then use regex to checkout `v7.12.x`, which it would use for generating goreleaser artifacts.
If I'm parsing things correctly, this means that creating a tag and then adding extra commits on top of 7.12.x _could_ cause us to build the wrong thing if the tag is pushed after the extra commits.
Instead, this just checks out whatever github ref triggered the action and builds that.

Run release action against triggering tag instead of checking out branch

---

config/config.go
config/config_test.go
docs/parameters.yaml

This PR fixes the logic of handling for deprecated parameters. Before this PR, we were setting the values from the deprecated config parameters as the default for the values of the new config parameters. However, these defaults from deprecated config params were overwritten when the server or client were initialized.
This PR adds changes so that rather than setting the value from the deprecated param as `viper.SetDefault` on the new config parameter, it uses `viper.Set` if the new config param is not set.
There still remains the issue that if the default of the new config param comes from `defaults.yaml`, the deprecation handling logic would fail. Another issue #1870 is created to address this.

Fix logic for handling deprecated configuration parameters

---

images/Dockerfile

Prior to the introduction of the pelican-server binary, pelican was always statically-linked. However, pelican-sever needs to be dynamic so it can access the lotman shared library.
This caused an issue in our production cache containers because the pelican-server binary was built in an alpine container (inherited from the old goreleaser container) which uses libmusl for linking, but then copied into an Alma container in the final stage, where libmusl is unavailable.
In this fix, the base container used to build pelican binaries is switched from the goreleaser container to a raw alma9 container. A side effect of this is that we now have to install a few things we previously didn't. Another thing I can't readily explain is that making this change appears to have altered the path these …

Use alma9 container for building prod pelican-server binaries

---

config/config.go
director/director.go
director/director_test.go
director/registry_periodic_query.go
director/registry_periodic_query_test.go
docs/parameters.yaml
launchers/director_serve.go
param/parameters.go
param/parameters_struct.go
registry/registry.go
registry/registry_db.go
registry/registry_db_test.go

This PR introduces a mechanism to define restrictions on the prefixes a cache is allowed to serve. The list of allowed prefixes can now be configured in the `custom_fields` column of the registry database as a JSON list, for example:
```json
{"AllowedPrefixes": ["/ns1", "/ns1/ns2"]}
```
- The cache will only serve requests for the specified prefixes in the `AllowedPrefixes` list.
- If the `AllowedPrefixes` key is absent in `custom_fields`, the default behavior remains unchanged (i.e., the cache will serve all prefixes).
- **Note**: If `/ns1` is in `AllowedPrefixes`, it does not imply that the cache is allowed to serve `/ns1/ns2`.
---
1. **New Registry Endpoint**:  
- A new endpoint, `/caches/allowedPrefixes`, is added to the registry.
- This endpoint returns a mapping of cache hostnames …

Add prefix restrictions on caches

---

docs/pages/about-pelican.mdx

Add 'pelican enables researchers to...' blurb in index page

---

director/director.go
metrics/director.go

This PR addresses issue #1774. This metric is a simple counter that tracks the number of times the director has rejected an advertisement from an origin or cache.

Rejected Advertisement Metric

---

server_utils/monitor.go
server_utils/server_utils.go

In the `Launch*` family of methods, if we stop the ticker outside the launched thread, it will never fire in the goroutine and hence never actually update.
From within the goroutine, it'll stop at shutdown and clean up the resources appropriately.
This needs to get backported to the v7.11 and v7.12 series.

Move `ticker.Stop()` into goroutine

---

config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
web_ui/prometheus.go

This PR addresses issue #1311. This PR uses the default values as described in [this design doc](https://docs.google.com/document/d/1sVJiZWKj8g3k7t_cy07aA_P7Es3Cg39mklrDKe_xo3c/edit?usp=sharing). This PR adds the ability to configure the label name and value length limits, the number of labels per time series, and the scrape limit. More information about these parameters can be found [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)

Add configuration for Prometheus to limit cardinality

---

images/Dockerfile
images/dev.Dockerfile

While we wait for certain riskier patches to be ingested upstream (either by XRootD itself or by the OSG repos), we need to install XRootD directly from Kojihub RPMs.
This commit primarily does that, with some other cleanup along the way, such as parameterizing versioning of various installed dependencies.

Install custom XRootD directly from Kojihub RPMs

---

client/director.go
client/fed_linux_test.go
client/handle_http.go
cmd/plugin_test.go
config/logging.go
config/resources/defaults.yaml
director/advertise_test.go
director/cache_ads.go
director/cache_ads_test.go
director/director.go
director/director_api.go
director/resources/director-public.yaml
director/sort.go
director/sort_test.go
director/stat.go
director/stat_stress_test.go
director/stat_test.go
docs/parameters.yaml
github_scripts/get_put_test.sh
local_cache/cache_test.go
metrics/director.go

This PR tidies up the "stat cache" code, attempting to get it to the point where it can be enabled in production again.
Fixes/changes include:
- Addition of a "memory stress test" that performs as many transfers as possible within a fixed time interval.  The goal is to fill the contents of the stat cache and check for leaks.
- Several small memory hoarding / leak issues fixed:
- The admin can no longer accidentally make the cache unbounded by setting the size to 0 and the TTLcache goroutine eviction is now run.
- The client IP cache similarly grew unbounded as the TTL cache goroutine is run.  Various log lines have been tidied up.
- The stat cache is cleared after a server disappears.
- A prometheus metric was added to record the number of entries in the caches, not just the number of …

Improve memory usage of the "stat cache"

---

config/config.go
director/monitor.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
web_ui/ui.go
xrootd/authorization.go
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

This PR contains one fix for the director test (solving confusion between the discovery URL and the director URL -- the director tests should have been using the discovery URL).
An integration test is *not* included but bugfixes are included that will eventually be necessary for the integration test.  In discussion with @jhiemstrawisc, we realized that the "federation-in-the-box" tests are failing because the scitokens.cfg is written prior to XRootD startup but the correct audience URL is not known until _after_ startup.  Our best idea for a fix is to implement an "automatic" mode for XRootD to have it determine the correct audience (which will require an XRootD release and hence take some time).
In the meantime, the bugfixes for a future test include:
1. Correct temporary directory …

Fixes for the director tests

---

github_scripts/osx_install.sh

Switch OS X to the consolidated Pelican branch for xrootd and update various dependencies (xrdcl-pelican, xrootd-s3-http) to the latest desired release.

Update dependencies for OSX GitHub Action

---

client/acquire_token.go
client/fed_test.go
client/handle_http.go
client/handle_http_test.go
client/main.go
client/prestage.go
client/resources/both-auth.yml
cmd/object_ls.go
cmd/object_prestage.go
cmd/plugin_test.go
config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-cache.cfg
xrootd/xrootd_config.go

This PR is a rebase of PR #1603 on the latest `main` branch. 
1. Adds the ability to prestage objects (files/directories) to caches:
- Currently, this is done by downloading the object to the client machine but disregarding the object instead of saving it to the disk.
2. Adds a collections URL override for the `object ls` command:
- This was originally part of PR #1603.

Add Prestage Functionality to Client

---

images/Dockerfile

We've run into a lot of issues with the way we install dependencies in our production container, including the inability to determine versions for what's installed, and shared objects that are copied without bringing along their dependencies.
Instead, we should just install whatever we can directly as an RPM into the final-stage container. This solves both issues in one fell swoop of a Pelican's beak.

Install pelican dependencies in final stage container

---

director/director_api.go

Reviewer can make the call as to whether this will make things hard to debug in the future. This line is 99% of existing Director logs at the moment.

Remove particularly verbose logging line

---

images/Dockerfile
images/dev.Dockerfile

Decouples xrootd-s3-http from EPEL, allowing us to quickly push out a new release with bugfixes.

Switch xrootd-s3-http plugin to be built from source

---

docs/pages/advanced-usage/server.mdx

Users will need to follow this procedure when getting a namespace in the OSDF.  De-jargon this to make it sound less imposing.

Remove jargon from the credential management page

---

.github/workflows/build-dev-container.yml

The previous action had a side effect such that whenever someone created a new tag for some release/release candidate, a new container with latest-itb would get pushed to Harbor, but from the `dev.Dockerfile` as it exists for that tag.
This essentially means _some_ but not all latest-itb tags weren't actually tracking main, but other branches instead.
After a chat with Sarthak & Emma, we don't see much use in building dev containers that aren't produced from the main branch, since we don't do dev work like that on our release series branches.
This commit removes tags as a trigger from the workflow, and only uses the image's sha256 and latest-itb as tags

Don't build dev images on git tags, tag im with latest-itb and sha256

---

cache/advertise.go
launcher_utils/advertise.go
launcher_utils/key_refresh_and_update_namespace_pubkey.go
launchers/cache_serve.go
launchers/origin_serve.go
origin/advertise.go
origin/origin_ui.go
server_structs/director.go

This PR unifies the namespace registration for both origin and cache by using their server hostname (without port) as prefix. Before this PR, origin itself registers with "hostname:port" in its own `Server_ExternalWebUrl` as prefix; cache registers with its `Xrootd_Sitename` as prefix (no port). This inconsistency causes plenty of friction. The change in this PR will be a cornerstone for multiple subsequent tickets for Pelican developers.
When this comes into prod, the origin/cache server installed this Pelican version will send serverAd with the updated prefix. OSDF system admin needs to approve server's new advertisement and remove the old registration db entries if necessary.

Use Server.Hostname as the prefix for origin/cache namespace registration

---

.github/workflows/release.yml
.github/workflows/test-template.yml
.github/workflows/test.yml
.goreleaser.yml

Very simple PR, fixes in the containers as well since they build from source.

Pinned the goreleaser version to 2

---

cmd/config_printer/config_printer_test.go
config/config.go
config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
xrootd/xrootd_config.go
xrootd/xrootd_config_test.go

This carries two fixes -- the first is for providing an xrootd log level that previously didn't have a definition, e.g. Logging.Origin.Http: trace. The new code should handle mapping that down if able, and up a level if needed
The new code also uses Pelican's configured Logging.Level as the default for the other xrootd values. This lets us crank up logging all at once without having to toggle each directive individually, while still allowing for individual overrides if so desired.

Fix xrootd log level mapping bug and inherit from Pelican log level

---

cache/advertise.go
launcher_utils/advertise.go
launcher_utils/key_refresh_and_update_namespace_pubkey.go
launchers/cache_serve.go
launchers/origin_serve.go
origin/advertise.go
origin/origin_ui.go
server_structs/director.go

Reverts PelicanPlatform/pelican#1984

Revert "Use Server.Hostname as the prefix for origin/cache namespace registration"

---

.github/workflows/build-and-test.yml
.github/workflows/test-linux.yml
.github/workflows/test-macos-windows.yml
github_scripts/citests.sh
images/Dockerfile
images/build-stages.dot
images/build-stages.svg
images/dev-config.yaml

The triggers for the unit tests have been moved into `build-and-test.yaml` (which was previously named `build-images.yaml`), because in order to run unit tests in a more appropriate container image, we might need to wait for that container to be built first.
The basic philosophy is this:
- Tags (`v{semvar}`) are always tested in a container based on the containers being pushed for that release or release candidate. This is the critical part.
- Pull requests are tested in whatever version of `pelican-test:latest-itb` happens to be available at the time. We can't push images during a pull request, and in the name of simplicity, I decided to forgo trying to find a "better" image. In practice, this should be fine so long as:
1. Updates to Pelican's dependences are pushed to `main` prior to …

Run tests in more appropriate container images

---

images/Dockerfile

Since the `Dockerfile` has been revamped, I took the new xrdhttp-pelican plugin installation out of the dropping privileges PR, tweaked the installation steps to fit in the new container building process with the help of @brianaydemir, and created this separated PR to get xrdhttp-pelican installed in Pelican.

Install new plugin: xrdhttp-pelican v0.0.3

---

fed_test_utils/fed.go

This should cut down on the noise in our logs. I'm also open to further refinement of the log levels if the reviewer(s) think anything should be turned up or down. That being said, this sets everything to the same level they used before tying XRootD log levels to the global Pelican log level.
I also switched a bunch of viper variables to their typed `param` equivalents. This protects us from changing param names without remembering to update things in our tests.

Pin xrootd log levels in fed test and use typed params throughout

---

director/director.go
director/director_test.go
e2e_fed_tests/README.md
e2e_fed_tests/director_test.go
e2e_fed_tests/resources/both-public.yml

The cache's `xrdcl-pelican` plugin switched from doing a HEAD request against requested resources to a PROPFIND request, the answer to which is used by the cache to determine whether something is an object or a collection. That's hunky dory, except that it broke the pseudo Director origin responsible for generating health test files, because the Director's health test API wasn't handling the propfinds.
This commit adds PROPFIND handling and generates the XML needed by the cache to understand the response. Note that I constructed the XML by pinging a cache with a real PROPFIND and then templating the response with file name, size, and time stamp.
One item remaining here is an actual E2E test of the setup -- while the unit tests are passing just fine, they passed just fine when everything …

Enable PROPFIND of Director health test API

---

cmd/plugin.go
cmd/plugin_test.go

If `K8SPhysicalHostName` set in the machine ad, have the plugin output "Hostname: <name>" in the error message.

K8SPhysicalHostName Error Message

---

github_scripts/osx_install.sh

Aligns OS X with other platforms and potentially fixes random deadlocks seen in unit tests.

Update OS X install of xrootd-s3-http to v0.2.1

---

web_ui/frontend/app/director/map/page.tsx
web_ui/frontend/components/InformationSpan.tsx
web_ui/frontend/components/Map/PopOutCard.tsx
web_ui/frontend/components/Map/ServerCard.tsx
web_ui/frontend/components/Map/ServerMap.tsx
web_ui/frontend/components/Map/index.ts

- Add more data onClick to the map server components
**Redacted to prevent scope creep** (_This is ready, but I would like to tack on a couple items before merge and need the director data to work first_)
https://github.com/PelicanPlatform/pelican/issues/1778

Add Cache and Server Cards to Map

---

server_utils/origin.go
server_utils/origin_globus.go
server_utils/origin_https.go
server_utils/origin_posix.go
server_utils/origin_s3.go
server_utils/origin_test.go
server_utils/origin_xroot.go
server_utils/resources/globus-origins/multi-export-valid.yml
server_utils/resources/globus-origins/single-export-invalid.yml
server_utils/resources/globus-origins/single-export-valid.yml
server_utils/resources/https-origins/multi-export.yml
server_utils/resources/https-origins/single-export.yml
server_utils/resources/s3-origins/env-var-mimic.yml
server_utils/resources/s3-origins/export-volumes-valid.yml
server_utils/resources/s3-origins/multi-export-valid.yml
server_utils/resources/s3-origins/single-export-block.yml
server_utils/resources/s3-origins/single-export-volume.yml
server_utils/resources/xroot-origins/single-export-invalid.yml
server_utils/resources/xroot-origins/single-export-valid.yml

This refactors a lot of the suburban sprawl from `server_utils/origin.go` in a way that I hope is much more maintainable and much less likely to have hard-to-diagnose errors.
In particular, I tried out some OOP go-style (and left lots of comments for others to follow along with the setup). I couldn't _quite_ do things the way I expected, but I think I got pretty close to something that's clean and easy to follow.

Refactor & Cleanup Origin Exports code

---

cache/advertise.go
config/config.go
config/resources/defaults.yaml
director/director.go
director/director_test.go
director/fed_token.go
director/fed_token_test.go
docs/parameters.yaml
e2e_fed_tests/cache_test.go
e2e_fed_tests/director_test.go
launcher_utils/advertise.go
launchers/cache_serve.go
origin/advertise.go
param/parameters.go
param/parameters_struct.go
registry/registry.go
registry/registry_db.go
server_structs/auth.go
server_structs/xrootd_server.go
server_utils/server_utils.go
server_utils/server_utils_test.go
swagger/pelican-swagger.yaml

I believe this implementation accomplishes the goal (and I can observe it working when I set things up locally), but there's still a lot of unit testing to do. I worked myself into a hole with the approach that now makes testing very hard due to cyclic imports.
Rather than finish all the refactoring to fix that up, I decided I'd open a draft to have others comment on the approach first. If the token management/verification checks out, I'll end up spending some time untangling things so I can run this through a proper test that spins up an entire fed-in-a-box.
Note that I started down this road because I assume Origins will also need fed tokens eventually, especially for third-party copies from origin to origin.

Add federation token endpoint in Director, and implement routine for caches to fetch one

---

web_ui/frontend/app/director/components/GeoIpErrorTable.tsx
web_ui/frontend/app/director/metrics/components/StorageTable.tsx

This PR addresses #2036. This PR adds some fallbacks to some locations where data was null or undefined.

Fix UI crashes

---

swagger/pelican-swagger.yaml
web_ui/ui.go

Added a new /version endpoint to expose version and build details, including build commit, build date, built by, and version number. Integrated this into the common set of APIs and updated the Swagger documentation accordingly.

Add /version endpoint to expose version and build info

---

config/config.go

Previously, we were only dumping the config to stderr on server startup. With this change, we also add a structured log for the full Pelican configuration.

Log Pelican config on server startup

---

metrics/shoveler.go
metrics/xrootd_metrics.go
metrics/xrootd_metrics_test.go
xrootd/xrootd_config.go

This PR fixes [issue #1916](https://github.com/PelicanPlatform/pelican/issues/1916). During investigation with the local federation, we discovered that the XRootD monitoring packet handler wasn’t processing shoveler messages correctly. The shoveler was sending JSON-encoded packets, which the existing code couldn’t interpret. This update ensures that shoveler packets are now correctly parsed and understood.

Allow for Shoveler messages to be understood by monitoring packet handler. 

---

docs/pages/federating-your-data/choosing-namespaces.mdx

Screenshot of the way this renders:

Document restricted characters in fed prefixes

---

images/Dockerfile

The move to `/usr/local/bin` was an unintentional change made when refactoring the container image build stages.
See #2052 for additional background.

Install `pelican-server` into `/usr/local/sbin`

---

config/config.go
config/mkdirall.go

See #2055 and #2056 for this PR's background.
In `config/mkdirall.go`, I've decided that it's preferable to avoid doing a lookup on the provided `uid` and `gid` if at all possible. `MkdirAll` is a sufficiently low-level function that it seems reasonable that callers should bear the responsibility for providing correct UIDs and GIDs.

Do not assume the existence of XRootD (`xrootd`) when it is not necessary

---

images/Dockerfile
scripts/geoquery.py

This new tool lets you run `geoquery -i {ip addr}` inside Director containers. The output is a printout of what the Director is able to tell about the IP address, based on the MaxMind database, e.g.:
```
$ geoquery -i "128.104.153.58"
IP address 128.104.153.58 is resolvable.
City: Madison
Country: United States
Latitude: 43.0782
Longitude: -89.4075
Accuracy Radius: 10
```

Add geoquery tool to Director containers

---

xrootd/launch_linux.go

Fix the error `panic: runtime error: index out of range [3] with length 3` and add comment to explain this code snippet.

Fix index out of bound error in attrs.Files

---

github_scripts/osx_install.sh

Try to update the OS X dependencies to match Linux; we've been observing infrequent (but annoying) segfaults during unit tests.
Particularly, xrdcl-pelican v1.0.3 fixes a segfault in the director response caching code.
I'm not entirely sure this will fix the problem -- but it's useful to hit the "low hanging fruit"!

Bump OS X Dependencies to avoid potential segfault

---

cmd/generate_keygen.go
cmd/generate_keygen_test.go
config/init_server_creds.go

`config.GeneratePrivateKey` is documented as generating a PEM-encoded key, so I've updated the code underlying `generate keygen` to use what seems to be the function for reading such PEM-encoded keys.
(There seem to be multiple functions for "reading" private keys, so I went with calling the function whose implementation most directly seems to address the problems of #2084.)

Fix `generate keygen` so that public keys included required fields

---

.goreleaser.yml

Add the dependencies required for the pre-script (which creates the pelican user and group) to run. Note that GoReleaser does not support the `Requires(pre)` header for RPMs, so even with the dependency, there is still no guarantee that e.g. /bin/sh will exist on disk by the time the pre script is invoked.

Add RPM and Deb dependencies for the programs required to run the pre-install script

---

images/Dockerfile

Curiously, at least to me, `sssd-client` doesn't create an `sssd` UID and GID.
If I recall correctly, the reason we create an `sssd` UID and GID is so that the sockets used to communicate with the actual `sssd` daemon are owned by the daemon, which is presumably running as that UID and GID. But in at least one instance I have access to, the sockets are public read/write and owned by `root` (which is what the daemon is running as).
So, it doesn't look like we actually need to create the `sssd` UID and GID, except perhaps as a nicety for those looking at the sockets on the file system in certain specific setups.

Install `sssd-client` into both origin container images

---

cmd/main.go
config/config.go
logging/logging.go

Implemented log buffering by creating a Logrus hook that buffers logs in memory until a flush is triggered. The flush runs only once, after which the hook is disabled.
Currently, the flush is triggered in `InitClient` and `InitServer`, sending buffered logs to the configured destination (stdout or file). For `config` commands that do not call `InitClient` or `InitServer`, logs are buffered until the program exits or terminates unexpectedly, at which point they are flushed to stdout without creating a log file.

Add log buffering mechanism using Logrus hook

---

database/director.go
server_structs/db.go
swagger/pelican-swagger.yaml
web_ui/ui.go
web_ui/ui_test.go

Closes #2069. This PR adds an endpoint to list all of the api tokens. This new endpoint is available with the other director web UI endpoints.

Create API token listing endpoint

---

xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg

This helps prepare Pelican for future end-to-end checksumming support by turning on a consistent set of algorithms, including `crc32c` (which I currently plan to use as the default).
Functionality at the origin tested by hand.

Enable crc32 and crc32c algorithms

---

docs/pages/federating-your-data/generating-tokens.mdx

There has been talk about removing the issuer from the xrootd
channel (e.g., port 8443)

Use the web port for the token issuer

---

director/director_ui.go

Now Origin/Cache version can be obtained in the following Director API endpoints:
{DIRECTOR_HOSTNAME}/api/v1.0/director_ui/servers
{DIRECTOR_HOSTNAME}/api/v1.0/director_ui/servers/{SERVER_NAME}
Then the frontend can consume them for displaying version for each origin/cache in the Director web UI.

Report origin/cache version info in Director display

---

config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
web_ui/oauth2_client.go

This PR introduces a new configuration parameter, `Issuer.OIDCPreferClaimsFromIDToken`, that when when set to `true`, causes Pelican's user authentication flow to first look for claims in the OIDC ID token before falling back on the OIDC UserInfo endpoint.
Pelican's current behavior is to consider only the UserInfo endpoint, hence why this new parameter's default value is `false`.

Add config parameter to allow preferring OIDC ID token claims

---

metrics/xrootd_metrics.go
xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg

This PR addresses #2051. 
This does the following:
- enable XRootD OSS stats plugin
- consume OSS stats from g-stream
- create metrics from the new statistics

Integrate XRootD OSS stats

---

client/director.go
director/cache_ads.go
director/director.go
director/sort.go
director/sort_algorithms.go
director/sort_algorithms_test.go
director/sort_test.go
server_structs/director.go

One of the most frequent user/integrator issues I've encountered is "why is the Director choosing _this_ list of caches/origins to redirect me to." As this redirection logic grows more complex, it may be useful to empower curious users to inspect some of the underlying logic themselves (with the appropriate debug logging flags). Not only does provide information about the Director's choices, but it might also let users identify issues that we can solve, such as client IPs that aren't resolvable with MaxMind.
This PR should accomplish two things:
- Add information about the Director's redirect choices to its response body for both cache & origin redirects
- Display that information in the client when debug information is turned on

Start plumbing redirect choice info into Director's response body

---

web_ui/oauth2_client.go
web_ui/oauth2_client_test.go

Given that [double encoding attacks](https://en.wikipedia.org/wiki/Double_encoding) are a thing, in order to prevent OAuth providers from mangling the `state` parameter that Pelican constructs, the simplest fix might be to set the parameter's value to a value that does not contain any URL encoding. I've chosen to base-64 encode it.
And while not strictly related to the above issue, I'm taking this opportunity to add a line to the debug logging, specifically to record the user info received from an OAuth provider. This is related to making #1054 a reality (same as this PR), and it's otherwise "challenging" to get any insight into this part of the OAuth flow.

Base64 encode the OAuth state to avoid a double URL-encoded string

---

cmd/root.go
logging/logging.go

Previously, the log buffering code handled interrupt signals but prevented the main cleanup routine from executing. This update ensures that log flushing on interrupt is correctly integrated with the existing cleanup logic.
Also corrected output syncing: replaced `os.Stdout.Sync()` with `Sync()` on the configured log destination.

Fix signal interrupt handling in log buffering code

---

director/stat_stress_test.go

Fill the cache before testing for potential memory leaks.
That said, it's worth noting that Go's runtime [does not use a "stop the world" collector](https://tip.golang.org/doc/gc-guide), and thus while [`runtime.GC()` promises to stop its caller in order to perform one complete generation of garbage collection](https://cs.opensource.google/go/go/+/refs/tags/go1.24.1:src/runtime/mgc.go;l=467), it's not clear to me what this actually means when we ask the runtime for the heap's current metrics.

Fix `TestStatMemory` (maybe)

---

.github/workflows/build-and-test.yml
.github/workflows/test-linux-pr.yaml

And while I'm here, make it so that the testing workflow for PRs can be triggered manually, just to be consistent with the other workflows.

Fix testing workflow for release candidates

---

config/config.go

The YAML marshaller has support for durations. The JSON marshaller does not.
And as discussed on #1662, there isn't a particularly compelling reason for sticking with JSON.

Use YAML for the debug-level config dumps

---

server_structs/db.go
swagger/pelican-swagger.yaml
web_ui/ui.go
web_ui/ui_test.go

Token API Patches:
- Align the endpoints to best practices using the HTTP verbs to indicate the action
- Unify the json that is returned to use the same keys across all models ( expiration vs expiresAt )
- Unify the json so the object posted aligns with the one I get back (scopes is a array on POST and csv on GET)
- Update the json keys to use camelCase
- Patch the Swagger docs to work with params in the path
PR is not to be a pedant, these small things result in a messy UI and I would rather just fix them.

Align token endpoints with REST API best practices

---

director/cache_ads.go
director/director.go
director/sort.go
metrics/director.go
metrics/xrootd_metrics.go

This PR addresses #1434. To maintain backwards compatibility, this adds metrics with new names instead of changing the existing names. Eventually we will want to use just the newly named metrics.

Revise Prometheus Metric Names

---

server_utils/director_discovery.go

Fixes the backwards compatibility issue with the directors in 7.14
The problem is that while the federation director endpoint was being added to the directors that were being checked to advertisementUrls, it then was never added to the final list of director endpoints because it would fail at the director listing in doDiscovery.
This fix checks for origins/directors that if there is no director advertisement endpoints to advertise to from the federation, then advertise to the origin federation director endpoint found during federation discovery.

Fix director backwards compatibility

---

.github/workflows/enforce-PR-labelling.yml

Increase event page size to 100 for issues with more then 30 events. This isn't a perfect update but should be good enough.

Add more events to response for long history issues

---

go.mod
go.sum
local_cache/cache_api.go
local_cache/cache_linux_test.go
local_cache/local_cache.go

Add PURGEFIRST functionality and reconstruct state from Data Location
- Introduced an endpoint to mark objects as PURGEFIRST, which creates a `.PURGEFIRST` sentinel file and adds the object to the PURGEFIRST heap.
- Objects marked PURGEFIRST are purged first using LRU, based on when they were originally added to the cache, when the purge routine runs.
- Modified startup logic to reconstruct in-memory state from `localcache.datalocation` instead of wiping out the directory on startup.

Add PURGEFIRST functionality and reconstruct state from Data Location

---

client/handle_http.go
github_scripts/citests.sh

When the client requests an object, grab determines the expected download size by inspecting the `Content-Length` header. Previously we didn't perform any checks against this value to make sure the number of bytes we receive actually match the number of expected bytes -- we only used status codes to determine success.
With this diff, we sanity check the number of bytes witnessed by the grab client, and when the client is writing a regular file and not a directory/unpacked object, we also stat the file on disk as a second check.

Sanity check received size and on-disk size for client GETs

---

config/config.go
docs/parameters.yaml
go.mod
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

This lets an Origin admin set:
```
Origin:
Concurrency: <int>
```
to limit the number of accepted concurrent requests to the Origin. You can test the diff by adding the config and observing the line `throttle.throttle concurrency <int>` in the generated xrootd config.
I also got annoyed enough by all the errant whitespace in the generated xrootd config that I tidied some of it up.

Make Origin throttling configurable

---

director/director.go
director/director_test.go
test_utils/utils.go

The bug was that we switched the Director to issue service discovery tokens using the Federation root as an issuer, but neglected to update the auth handler in the service discovery endpoint to accept federation tokens.
This adds the extra auth handler and gives the test a face lift that I think would have caught the bug the first go around had they existed.
I also added a mock federation root server, which I've wound up re-implementing too many times. Some other time I'll go back through some old code and switch it to use this standard test utility.

Fix metrics scraping by accepting fed tokens for Director service discovery

---

config/resources/osdf.yaml
director/advertise.go
director/advertise_test.go
docs/parameters.yaml
launchers/registry_serve.go
param/parameters.go
param/parameters_struct.go
xrootd/authorization.go
xrootd/authorization_test.go

Added flags to disable getting downtime from Topology, getting X509 authentication from Topology (caches and origins), getting caches themselves, and getting origins.
These are meant to be modular, so rather than gutting AdvertiseOSDF or playing with the "isTopology" settings in the ads, this just selectively disables what information it creates/retrieves from Topology as needed.
I recommend testing by using the osdf binary and selectively applying various versions of the TopologyFlags and seeing that the various features are turned off.

Disable topology flags

---

director/director_ui.go
server_structs/director.go

This PR addresses issue #2073. After a series of trials and conversations with @jhiemstrawisc. We concluded that it would be difficult to align these structures together without breaking compatibility. This PR adds a warning message comment so that hopefully to prevent misalignments in the future.

Add Warning Comment for Misaligned ServerAd and serverResponse structs

---

docs/parameters.yaml
oa4mp/resources/policies.qdl
oa4mp/serve.go

Please refer to the updated documentation in `parameters.yaml` for how this new functionality is intended to work.
Some notes about the implementation:
- `if [true] then` in the generated QDL is superfluous, but that is an intentional stylistic choice on my part. It ensures that each authorization template renders to a similar set of QDL control-flow constructs, which I think makes it easer to scan the generated QDL.
- I added a `sort` to the process of generating the final `scope` claim, because it makes it easier, as a human, to check for the presence or absence of a particular authorization, especially when the list gets quite long.

Add user and group requirements to the built-in issuer's authorization templates

---

cmd/main_test.go
config/config.go
config/config_test.go
config/config_validation_test.go
local_cache/cache_linux_test.go
logging/logging.go
registry/registry_ui_test.go
server_utils/server_utils.go
web_ui/authentication_test.go
web_ui/server_api_test.go
xrootd/authorization_test.go

There were two bugs here:
1) The web config override function assigned all the new viper overrides but it didn't use them to set the log level. Because the logging library doesn't look at viper, it was potentially unaware it needed to update its levels.
2) Logs were flushed (and consequently their location assigned) before the web config yaml was loaded/merged.
The reviewer can test this diff by starting any Pelican server and modifying log levels and log locations via the web UI. Previously, doing this had no effect but now the values should be used correctly.

Fix log level/location issues coming from web UI config

---

client/acquire_token.go
cmd/director.go
cmd/downtime.go
cmd/downtime_create.go
cmd/downtime_delete.go
cmd/downtime_list.go
cmd/downtime_update.go
cmd/root.go
database/server.go
server_structs/director.go
utils/utils.go
web_ui/server_api.go

This PR gives server admin the power of setting their own server's downtime via command line interface. The commands includes list, create, update, delete downtimes.
Examples:
`pelican downtime list --server=<WEB_URL>  [--status=incomplete(default)/all] [--output=json(default)/yaml]`
`pelican downtime create --server=<WEB_URL>`
`pelican downtime update <DOWNTIME_ID> --server=<WEB_URL>`
`pelican downtime delete <DOWNTIME_ID> --server=<WEB_URL>` 
Optional flag for above commands: `--token=<PATH_TO_TOKEN_FILE>` Use the token in specific file, instead of the token automatically generated by Pelican's current issuer key.

Downtime CLI for server admin

---

fed_test_utils/fed.go

Fix a bug in the downtime tests.

Make sure the server dblocation is in a tmpdir in NewFedTest

---

registry/registry_db.go
registry/registry_ui.go
registry/registry_ui_test.go
registry/registry_validation_test.go

It excludes the namespace itself from its super/sub spaces.
With this update, Registry admin can overwrite any namespace's public key.
Q: After this change, when a namespace registers, how do we check if there is a same namespace already registered?
A: We have a dedicated `namespaceExistsByPrefix` func to do that when a namespace registers. Note that this func won't be executed when Registry admin updates the namespace. So, it's safe to exclude the namespace itself from its super/sub spaces.
Next, @CannonLock will add a warning on the UI when Registry admin wants to edit the public key of a namespace that has super/sub spaces.

Exclude namespace itself from its super/sub spaces & allow Registry admin to overwrite the public key of a namespace

---

fed_test_utils/fed.go
local_cache/cache_api.go
local_cache/cache_test.go

Create a temporary file for the local cache unix socket and rename it into place.  This prevents any pre-existing socket (say, from a prior crash of the local cache) from causing startup to fail.
Fixes #2216

Create cache socket as temporary and overwrite

---

images/Dockerfile

From #2232:
> It should be possible to run something somewhere in the build process to make sure we don't overwrite software like this.
This is exactly what [DNF's versionlock plugin](https://dnf-plugins-core.readthedocs.io/en/latest/versionlock.html) is for.

Prevent package dependencies from changing the XRootD install

---

xrootd/launch.go
xrootd/launch_linux.go
xrootd/resources/xrootd-cache.cfg

This adds configuration and runtime environment tweaks for XRootD ahead of upcoming v71.6 features (particularly, allows for checksums to be passed through and is needed for some xrdcl-pelican unit tests).

XRootD config changes for v7.16

---

cmd/cmd_utils.go
cmd/object_copy.go
cmd/object_get.go
cmd/object_prestage.go
cmd/object_sync.go
cmd/plugin.go
config/config.go
docs/pages/advanced-usage/plugin.mdx
docs/parameters.yaml
github_scripts/citests.sh
param/parameters.go
param/parameters_struct.go
utils/utils.go

This standardizes our use of `Client.PreferredCaches` internally as a
string slice, bearing the "+ means continue" semantics. Previously
we used an entirely undocumented environment variable `NEAREST_CACHE`,
and in only a subset of places we also checked for `PELICAN_NEAREST_CACHE`.
With the new approach, we still handle these configurations, but immediately
stuff them into viper to be used later in a standardized way.

Pelicanize "NEAREST_CACHE" env var with 'Client.PreferredCaches'

---

.pre-commit-config.yaml

This seems to resolve the failure in the GitHub Action.
In the name of expediency, I'm not attempting to upgrade everything that's fallen behind.

Update the version of golangci-lint used by pre-commit

---

.goreleaser.yml
systemd/osdf-cache.service
systemd/osdf-origin.service
systemd/pelican-cache.service
systemd/pelican-origin.service

Also updates the SystemD files for the cache and origin to use `pelican-server` instead of `pelican` or `osdf`.  For consistency with the current images, the director and registry .service files continue to use `pelican` or `osdf`.  Note that osdf-cache and osdf-origin no longer run a program with the magic `osdf` prefix, so they will be getting generic config unless overridden.

Put the dynamically-linked pelican-server binary in the pelican-server RPM

---

classads/classads.go
classads/classads_test.go
client/fed_test.go
client/handle_http.go
client/handle_http_test.go
client/main.go
cmd/object_stat.go
cmd/plugin.go
cmd/plugin_test.go

This PR improves the checksum functionality:
- Adds a bugfix that prevents checksum failures from not being reported as checksum mismatch errors (@jhiemstrawisc - I think this is probably important enough to put into a 7.16 RC).
- Records the client and server-side checksums into the plugin outputs.  This will allow ElasticSearch to detect the frequency of errors.
- Adds a flag to `pelican object stat` that allows CLI users to get a checksum back.
Example:
```
pelican object stat --json --checksums md5 pelican://`hostname`:8444/tmp/test/hello_world.txt
{"Name":"/tmp/test/hello_world.txt","Size":12,"ModTime":"2025-04-26T15:16:26Z","IsCollection":false,"checksums":{"md5":"6f5902ac237024bdd0c176cb93063dc4"}}
```

Bugfixes, tests, and tools around checksums

---

metrics/xrootd_metrics.go

This PR addresses #1463. This PR adds a new metric `xrootd_cpu_utilization`. This metric is calculated from the summary statistics provided by XRootD. The CPU utilization is calculated via the following: (CPU time used) / (Wall time elapsed). The CPU time used is calculate by calculating the delta between the last amount of CPU time used and the current cpu time used. The wall time elapsed is calculated as the difference between the current time and the last time we received a summary statistic.

XRootD CPU Utilization Metric

---

client/handle_http.go
client/handle_http_test.go

Previously, only the bytes from the latest attempt (which doesn't necessarily start at the beginning of the file if done during a retry) were used, meaning the comparison with total size always failed.
Additionally, avoid doing a transfer retry when there are zero bytes left to transfer.  That will always fail.

Correctly compare the total local size with the total downloaded size

---

.goreleaser.yml

Closes #2284 . The packages providing `/usr/bin/getent`, `/usr/sbin/useradd`, and `/usr/sbin/groupadd` (used in the pre-install script to create the `pelican` user and group) are not named the same on openSUSE Leap vs RHEL-based distributions. We can get around the issue by requiring the specific files instead.

RPM: Specify pre-install script requirements by binary instead of by containing package

---

director/director.go
director/director_test.go

Fix the bug that when the Director toggles the downtimes set by origin/cache, it skips re-evaluating any server that already has a filter (downtime).
Also simplify the code logics.
For example, let's say there is a downtime entry set by the Origin and propagated to the Director with server ads every minute:
> Note: "existing" means "existingFilterType", "had" means "isServerFiltered" in the code
> First ever “active” → had==false, so it sets serverFiltered.
> 
> Subsequent still-active → had==true && existing==serverFiltered, it doesn’t enter the `!had` branch, but we also don’t delete, because active==true skips the delete block.
> 
> Subsequent no longer active → active == false && had == true && existing == serverFiltered, so it falls into the delete block
> 
> Change time: Active to …

Toggle origin/cache downtimes in director correctly

---

config/config.go
director/cache_ads.go
director/director_api.go
go.mod

The bug here was nuanced -- if a server had previously succeeded at advertising but was restarted quickly in a way that caused advertisement failure, the IO Stats routine would refresh the ad every 15 seconds, completely preventing expiration. This adds the disable on touch option so that these ads can expire.
I've also added it as the default behavior on ttlcache instantiation as well. Why do it in both places, you may ask? I want to future proof the bug against anyone purposefully/accidentally removing the default from the ttlcache instantiation, while also adding some protection against this type of bug for anyone in the future who might write a routine that calls `serverAds.Get()` without remembering to include the option there as well. Including the option in both places covers both …

Don't refresh expiration on serverAds.Get()

---

client/acquire_token.go

This PR addresses issue #2131 by adding an additional selection criterion to the token selection process. Specifically, it introduces a check to compare the issuer provided in the Director’s response with the issuer in each token. Tokens are only considered further if the issuers match.

Client uses token issuer as selection criteria during token selection process

---

client/acquire_token.go
client/main_test.go

Pelican’s client today only recognizes WLCG tokens (i.e. JWTs with a wlcg.ver claim). When a user supplies a SciTokens‑profile JWT (with ver: "scitokens:2.0"), Pelican will reject it as “unacceptable”. This PR extends the token profiles Pelican support from WLCG to SciTokens. Check out the linked issue for more details.
Close #2130

Accept SciTokens-profile JWT

---

director/director.go
registry/registry.go
registry/registry_validation.go
server_utils/origin.go
server_utils/origin_test.go
server_utils/resources/posix-origins/multi-export-trailing-slash.yml

We should allow user to set either `/foo/bar` or `/foo/bar/` as the federationprefix, but fundamentally treat them as the same (without trailing slash).
This patch switches the order of prefix validation and prefix existence checking. It removes the trailing slash for the user input prefix, which prevents the error [like this](https://github.com/PelicanPlatform/pelican/issues/1806#issuecomment-2840109314) in the future.
Closes #1806

Properly handle the trailing`/` in namespace registration and advertisement

---

director/director_test.go

There is a flaky test on GitHub Action (actually, almost always failing) because the test downtime window is too tight, which results in the test downtime expires before the server ad gets to the Director.

A wider test downtime window to avoid flaky test

---

.goreleaser.yml
images/Dockerfile

The goal of this PR is to ensure that Pelican's release process yields an RPM (yes, specifically an RPM) whose `pelican` binary includes sufficient information to be run successfully under a debugger, such as [Delve](https://github.com/go-delve/delve).
--------
Some notes about the changes here:
- I am taking advantage of YAML "anchors" and "aliases" to avoid duplicating raw YAML text. Admittedly, this depends on support for [merge keys](https://yaml.org/type/merge.html), but I've yet to encounter a YAML parser that behaves in an unexpected manner when presented with such.
- I've edited some of the lists in `.goreleaser.yml` so that the `id` key appears towards the top of each list element. It would seem that GoReleaser requires that these keys be unique, so burying them in the depths of …

Build a "debug" RPM for the Pelican client

---

images/Dockerfile

xrootd-5.8.2-1.4 has known issues w.r.t. missing symbols in the scitokens plugin

Downgrade xrootd in the images to 5.8.2-1.3 (7.16)

---

web_ui/frontend/app/registry/denied/page.tsx
web_ui/frontend/app/registry/page.tsx
web_ui/frontend/components/Namespace/Card.tsx
web_ui/frontend/components/Namespace/DeniedCard.tsx
web_ui/frontend/helpers/api.ts

- Create single mutate key for all getExtendedNamespace functions that is called when the data is updated
Closes #2124

Refresh Namespace list on update

---

config/config.go
director/cache_ads.go
director/director_test.go

In Director, expired downtimes set by Registry should also be cleared when no active downtimes set by Registry.
Spin up Registry, Director, Origin (or Cache). In Registry, create a downtime (ends at X minutes from now) for the Origin. Go to Director to verify this Origin is **in** downtime. X minutes later, this downtime expires. Check this Origin in Director again to make sure it is **not in** downtime.
If you find these downtime logics are too complicated... here is a diagram for the Downtime management workflow in Pelican #2218

Bugfix for downtime handling in Director

---

client/handle_http.go
config/config.go
config/resources/defaults.yaml
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go

Correct various and sundry bugs around the download rate calculation, progress bars after a slow transfer timeout, and minimum download speed.

Fix rate and progress calculations

---

director/director_test.go

The previous fix #2308 for the flaky test “future-to-active-toggle” was not enough. This test still goes south sometimes ([example](https://github.com/PelicanPlatform/pelican/actions/runs/15218213055/job/42808498892#step:9:14717)).
This PR aims to eliminate the flakiness by the following two approaches:
1. Radically increase the test downtime window to avoid `now` not being in the downtime window
2. Wrap the filter check in an `eventually` block with deterministic timeout and polling, so that we don't need to worry that downtime setting on the mock server is slower than the test execution.
Closes #2309

A radical fix for “future-to-active-toggle” downtime test

---

broker/client.go
broker/server_apis.go
cache/advertise.go
director/director.go
docs/parameters.yaml
e2e_fed_tests/director_test.go
e2e_fed_tests/downtime_test.go
launchers/cache_serve.go
server_structs/xrootd_server.go
server_structs/xrootd_server_test.go
server_utils/server_utils.go
server_utils/sitename.go

The bug was that I'd designed this to always use the server's hostname when requesting federation tokens. However, when `Xrootd.Sitename` is set in caches, that's the name that gets registered. This misalignment prevented the Director from validating caches' advertise tokens, which blocked it from handing out the federation tokens.
Assigning @h2zh as the reviewer since I know he's currently working on some things related to server names in the Registry -- does this approach look okay to you? Ultimately the value I send to the director's fed token API in the `host` query parameter needs to match the cache/origin's registered name.

Use proper name from registry when requesting federation tokens

---

github_scripts/osx_install.sh
images/Dockerfile

This new plugin version comes with a few bugfixes that we hope help with various deadlocks we've seen recently.

Bump containerized xrootd-s3-http plugin version to 0.4.1

---

director/director_test.go

This PR is a continuation of #2352, aiming to use the same approach to eliminate the flakiness in other two downtime subtests ([here](https://github.com/PelicanPlatform/pelican/actions/runs/15308443325/job/43066952842?pr=2291) is an example of failure).
1. Radically increase the test downtime window
2. Wrap the filter check in an `eventually` block with deterministic timeout and polling, so that we don't need to worry that downtime setting on the mock server is slower than the test execution.
Closes #2309

Fix other flaky downtime subtests

---

client/handle_http.go
client/handle_http_test.go

This is fixing the issue described here: #2248 
It mimics how downloadHTTP deals with the proxy.
This is just meant to be a fix to make sure both functions are behaving the same way, but I think there is a larger issue involving the correctness of the code that I created a different issue for in #2371 
Test this by running a put using the built binary on the ospool with 
Requirements = GLIDEIN_Site == "UA Little Rock ITS"

Updated runPut to mimic downloadHttp's proxy logic

---

cmd/generate_password.go
config/config.go
config/init_server_creds.go
config/mkdirall.go
xrootd/authorization.go
xrootd/launch.go
xrootd/self_monitor.go
xrootd/xrootd_config.go

This PR is built on top of #2120, which should be reviewed first.
During the development of the above PR, I notice there are several other permissions denied errors happened on several directories/locations, as below:
```
WARNING[2025-03-17T17:06:33Z] Failed to open auth database for reload:open /etc/pelican/server-web-passwd: permission denied
WARNING[2025-03-17T17:07:03Z] Failed to load key /etc/pelican/issuer-keys/pelican_generated_1740770124479586092_2096306543.pem: failed to read key file: open /etc/pelican/issuer-keys/pelican_generated_1740770124479586092_2096306543.pem: permission denied
ERROR[2025-03-17T17:08:03Z] Failure when generating authfile: Failed to create a generated authfile /run/pelican/xrootd/cache/authfile-cache-generated: open …
```

Handle directories permission denied error in drop privs mode

---

config/config.go
daemon/launch_unix.go
director/cache_ads.go
director/director.go
director/director_api.go
docs/parameters.yaml
launchers/launcher.go
metrics/health.go
metrics/health_test.go
param/parameters.go
param/parameters_struct.go
server_structs/director.go
web_ui/frontend/app/config/components/RestartBox.tsx

Trigger the graceful shutdown once a Pelican Origin or Cache receives a SIGTERM signal (`kill -TERM <pid>`)
Upon receiving `SIGTERM`, the Origin or Cache process waits one minute for in-flight transfers to complete. If any transfers remain after the one-minute grace period, the server shuts down immediately.
Before the wait, the Origin or Cache sends a shutdown advertisement with the new `Status` field (="shutting down") to the Director, instructing it to stop routing any new transfer requests to this server. The Director then applies an indefinite downtime window to this server, so that offline servers still listed in its cached `serverAds` will be excluded from new requests. Whenever the server is back online, it will send a regular server ad to flush out the "shutting down" downtime. …

Graceful shutdown an Origin or Cache

---

config/init_server_creds.go

- Mitigate backward compat friction for Integration work

Support key files with `.jwk` extension in `IssuerKeysDirectory`

---

cmd/plugin_test.go

Without this, if the test fails, various goroutines stick around and can prevent the unit test framework from a clean shutdown.

Ensure test is properly shut down on failure

---

config/encrypted.go

This PR address issue #1986. This PR simply moves the keyring error messages behind the debug log level.

Move keyring errors behind debug log level

---

xrootd/resources/xrootd-origin.cfg

The previous value of `2` is lower than what is used for the concurrency of the memory stress test, resulting in occasional test failures.
Additionally, 10 concurrent jobs are probably more reasonable for an origin.
I don't currently see a need to make this exposed to the origin administrator (but I'm willing to revisit if needed).

Increase maximum checksum jobs to 10

---

client/handle_http.go
client/handle_http_test.go
cmd/object_get.go
cmd/object_put.go

This PR resolves issue #2391 by adding a feature to the client CLI that outputs transfer statistics in JSON format. Users can enable this output using the new `--transfer-stats` flag with the `object get` and `object put` commands.

Introduce client transfer statistics output

---

config/init_server_creds.go

The issue being fixed here is that some of our internal tests were producing bad certificates by adding IP addresses as DNS names, which was exposed recently when we started checking the configured certs against the configured server hostnames
This diff does two things -- it only toggles the cert<-->hostname validation when TLS is enabled in Pelican, and it adds the IP addresses to the cert correctly regardless.

When creating custom TLS certs, add IPs to SANs as IPs and not DNS names

---

director/director.go
director/director_test.go

Fixes an error where the link header depth when querying the directory for collections was incorrect at the top level of a namespace because the prefix would have an "/" appended to it which would cause the prefix matching to fail.
Simple solution, remove the potential extra "/" after doing the matching.
Also ensures that a full match has a link depth of 0.

Fix link depth header for listings

---

client/errorAccum.go
client/handle_http.go
client/handle_http_test.go

The goal of this PR was to mark errors that weren't being retried as retry-able
Specifically, when an invalid byte is in the chunk length header or an unexpected EOF, as those are most likely because a connection dropped or something went wrong during data transfer.
The third error is when there is a TLS connection error on a put. The expectation is that, again, is retryable.

Mark additional errors as retry-able

---

client/acquire_token.go
client/main_test.go

This PR addresses issue #2441. This PR fixes a bug where the token is marked acceptable when it shouldn't as described in the issue. This PR adds the appropriate logic to mark the token as acceptable based on the operation that the client is trying to achieve.

Added per operation scope checking

---

xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg

Adds the appropriate CORS headers to that we can make queries to Xrootd services from the browser.
To test spin up a Origin/Cache and curl it to verify that it is returning the appropriate headers.

Web client - Origin and Cache changes

---

web_ui/frontend/app/(landing)/layout.tsx
web_ui/frontend/app/(login)/initialization/code/layout.tsx
web_ui/frontend/app/(login)/initialization/password/layout.tsx
web_ui/frontend/app/(login)/layout.tsx
web_ui/frontend/app/api/docs/layout.tsx
web_ui/frontend/app/cache/layout.tsx
web_ui/frontend/app/config/layout.tsx
web_ui/frontend/app/director/layout.tsx
web_ui/frontend/app/director/map/layout.tsx
web_ui/frontend/app/director/metrics/layout.tsx
web_ui/frontend/app/layout.tsx
web_ui/frontend/app/origin/globus/layout.tsx
web_ui/frontend/app/origin/issuer/layout.tsx
web_ui/frontend/app/origin/layout.tsx
web_ui/frontend/app/registry/cache/edit/layout.tsx
web_ui/frontend/app/registry/cache/register/layout.tsx
web_ui/frontend/app/registry/denied/layout.tsx
web_ui/frontend/app/registry/layout.tsx
web_ui/frontend/app/registry/namespace/edit/layout.tsx
web_ui/frontend/app/registry/namespace/register/layout.tsx
web_ui/frontend/app/registry/origin/edit/layout.tsx
web_ui/frontend/app/registry/origin/register/layout.tsx
web_ui/frontend/components/layout/MetaLayout.tsx

- Page specific titles, so rather then only "Pelican Platform" you will see "Register Cache | Origin" for example
- Create MetaLayout for an unobtrusive layout for metadata inclusion

Add meaningful page titles

---

web_ui/frontend/components/Downtime/DateTile.tsx
web_ui/frontend/components/Downtime/DowntimeCalendar.tsx
web_ui/frontend/components/Downtime/DowntimeEditContext.tsx
web_ui/frontend/components/Downtime/EditDowntimePageHeader.tsx
web_ui/frontend/components/Downtime/Registry/ServerUnknownDowntimeForm.tsx
web_ui/frontend/components/Downtime/Server/DowntimeForm.tsx
web_ui/frontend/components/Downtime/calendar.css
web_ui/frontend/helpers/Registry/namespaceToServer.ts
web_ui/frontend/helpers/getDaysInMonth.ts
web_ui/frontend/helpers/getUtcOffsetString.ts
web_ui/frontend/index.ts
web_ui/frontend/package-lock.json
web_ui/frontend/package.json

- Sort, add icons, clean prefix in server options on registry
- Add note about current timezone on time entry
- Always have start and end time autopopulate to current time
- Filter out not approved servers
- Update styles to prevent number overload and add more meaning to Tiles
Closes #2373
Closes #2254
Closes https://github.com/PelicanPlatform/pelican/issues/2398

Downtime Upgrades

---

client/acquire_token.go
director/director.go
docs/parameters.yaml
images/Dockerfile
oa4mp/proxy.go
oa4mp/resources/authorize-remote-user.jsp
oa4mp/resources/device-consent.jsp
oa4mp/resources/device-fail.jsp
oa4mp/resources/device-ok.jsp
param/parameters.go
param/parameters_struct.go
server_structs/director.go
server_utils/oidc.go

Intended to be merged after #2467
**Add redirect=false to the director so that the web client can read the directors headers before being redirected**
Used by the web client which cannot read headers from a url that has redirected itself. Allows the web client to consume the `X-Pelican-Authorization` header, which in turn points it at the issuer to begin the token exchange.
**Add CORs configuration on the Director and the Origin Issuer**
Enables browser requests to the Director and the Origin. These are used on PUT, POST, OPTION, GET methods depending on the service. 
The director needs to be able to handle the PUT, POST, GET and OPTION which are typically forwarded to the cache/origin.
The Origin needs to be able to respond to the Issuer requests such as the code exchange and the Client …

Web client - All Changes

---

images/Dockerfile

Now that `xrootd-lotman-0.0.5` is in the OSG repos, we should install from there instead of building from source.
This should also fix the currently-failing tests that point to an un-located symbol when dlopening Lotman.
Since this passed the GHA tests last time, I'd recommend the following testing procedure:
1. Checkout this diff
2. Build the image, launch tests in the container, e.g.:
```
docker build -t pelican-test:latest -f images/Dockerfile
docker run --rm --volume $(pwd):/pelican --entrypoint go -w /pelican/lotman pelican-test:latest test -tags=lotman
```
This avoids any container/repo mangling that happens in the GHA tests.

Install xrootd-lotman and lotman from osg repos

---

.github/workflows/test-linux.yml
.goreleaser.yml
launchers/droppriv_unix.go

Enable CGO for the build that includes lotman. Lotman uses purego, which implements a fakecgo and persuades runtime that CGO is enabled. Then in the drop-privs feature, CGO_ENABLED=0 would make syscall.Setgid and syscall.Setuid call AllThreadsSyscall(), while this function is incompatible with binaries that use cgo (and fakecgo also counts). Set CGO_ENABLED=1 to avoid calling AllThreadsSyscall(), which causes this panic.

Enable CGO for the binary build that includes purego

---

director/director.go
director/director_advertise.go
director/forward_service_test.go
server_structs/director.go
server_utils/sitename.go
server_utils/test_file_transfer.go

This PR addresses issue #2369. 
The following key changes were made:
1. Implemented `nil` checks in advertisement handling, specifically within `updateInternalDirectorCache` and `IsDirectorAdFromSelf`. This resolves the `SIGSEGV` and `nil pointer dereference` panics that occurred when processing `nil` director ads, a core problem noted in the issue.
2. All service and director advertisements are now wrapped in a consistent `forwardAd` struct before being propagated to other directors. This ensures uniform processing across the federation.
3. Directors now track the originator of incoming service ads and will not forward them back to the sender. This crucial change prevents advertisement loops, which were causing instability and timeouts.
4. Fixed a bug in `updateInternalDirectorCache` …

Multiple Director Bug Fixes

---

config/init_server_creds.go
config/init_server_creds_test.go

Let Pelican to follow issuer key symlinks.
1. Use `pelican key create` command to create a new pair of private and public keys in any directory.
2. In `IssuerKeyDirectory`, create a symlink pointing to the private key you just created. 
3. Obtain the public key of this server (e.g. via the .well-known endpoint). If it contains a key whose id is the same as the public key id generated in the first step, the test passes.

Follow symlink to load private key

---

cmd/config_printer/config_get.go
cmd/config_printer/config_printer_root.go

When user tries to get a deprecated config via `pelican config get`, this PR:
1. Show deprecation messages for deprecated parameters instead of silently skipping them
2. Provide clear instructions on how to view deprecated parameters using `--include-deprecated` flag
It also gives users the flexibility to choose between broad discovery (substring) and precise targeting (exact match) when retrieving configuration parameters.
Expected behavior:
```
issuerkey: This parameter is DEPRECATED. If you still need to view it, run: pelican config get issuerkey --include-deprecated
issuerkeysdirectory: "issuer-keys"
issuerkey: This parameter is DEPRECATED. If you still need to view it, run: pelican config get issuerkey --include-deprecated
No matching configuration parameters found.
issuerkey: …
```

Improve deprecated parameter handling in `pelican config get`

---

client/acquire_token.go

Based on the scitoken official [docs](https://scitokens.org/technical_docs/Verification) (scroll to the bottom), the correct behavior is for the `ver` claim is `scitoken:2.0` (singular). However, to maintain backward compatibility and typo tolerance, Pelican should keep accepting `scitokens:2.0` too.
The implementation is inspired by the `scitokens-cpp` [scitoken check](https://github.com/scitokens/scitokens-cpp/blob/709393585ae238397bdabe1e941541cc01044478/src/scitokens_internal.h#L553-L554) mentioned by @brianaydemir

Use the correct `ver` claim in scitoken verification

---

.github/workflows/test-linux.yml
.github/workflows/test-macos-windows.yml
client/director.go
client/fed_long_test.go
client/fed_test.go
client/handle_http.go
client/main.go
config/transport.go
daemon/launch.go
daemon/launch_unix.go
director/cache_monitor.go
director/director_advertise.go
director/director_advertise_test.go
director/stat.go
director/stat_stress_test.go
director/stat_test.go
launcher_utils/advertise.go
local_cache/cache_authz.go
pelican_url/discovery.go
xrootd/launch.go
xrootd/launch_linux.go

This PR overhauls the stat stress test to make it more reliable.  This includes:
- Using a common client throughout the code base.  As a side-effect, I noticed we were editing the global transport object from multiple threads simultaneously when proxies are present which is probably ... bad.
- Ensure we correctly handle HTTP responses.  For a TCP connection to be reused, we *must* fully read the response and close it.  One issue with the stat test was its churning through TCP connections (and associated data structures) at an incredible rate.
- Having some environment-variable based tuning of the test, allowing one to run it for longer and dump heap profiles.
Honestly, if we're still seeing weirdness after this PR, I think I might just mark the test skippable and move on with life.

Improvements for HTTP transports and stat tests

---

web_ui/frontend/app/(login)/403/page.tsx
web_ui/ui.go
web_ui/ui_test.go

- Adds 403 page to explain what happened if a user logs in to non admin account
- Redirects cache and origin pages if user is not admin
Closes #2202

Fixes login handling for Origin and Cache

---

cmd/config_printer/utils.go
config/config.go
go.mod

This PR fixes the bug that Pelican `config` CLI tool does not take env vars into account.
Design thinking: I decide to temporarily suppress excessive logging in `InitConfigInternal`, because the power user of this CLI tool wants to get a cleaner output

Fix the bug that Pelican `config` CLI tool does not take env vars into account

---

client/handle_http.go
client/handle_http_test.go

This PR addresses #2543. This PR fixes the way we handle the case where the origin fails to produce a checksum requested by the client. In the previous implementation, we would produce an error and the transfer would fail. The transfer should only fail if we **required** the checksum in the transfer. 
This PR fixes the bug, adds tests, and fixes existing ones to reflect this behavior.

Fix checksum requirements on `put`

---

cmd/plugin.go

This PR addresses issue #2557. This PR adds a new error classification for a slow Origin. This PR also fixes the error message for an unprocessed error.

New error classification for slow Origins

---

client/fed_long_test.go
client/fed_test.go
client/handle_http.go
client/handle_http_test.go

This PR addresses issue #2470. This PR adds a simple check to see if the object exists at the origin before proceeding with the upload. This check doesn't take into account any tokens and will simply block the upload if the object exists. 
I added test cases to ensure this behavior works as expected.

Prevent overwriting objects at upload

---

github_scripts/osx_install.sh
images/Dockerfile

Bumps xrdcl-pelican to 1.5.1 (for the 7.19 release)

Bump xrdcl-pelican version to 1.5.1

---

config/config.go
docs/parameters.yaml
param/parameters.go
param/parameters_struct.go
xrootd/resources/xrootd-cache.cfg
xrootd/resources/xrootd-origin.cfg
xrootd/xrootd_config.go

This PR addresses issue #2571. This PR introduces a new configuration parameter, `Xrootd.HttpMaxDelay`. The default value is configured to be 9 seconds. This new configuration is added to both the origin and the cache.

Set `http.maxwait` in XRootD configuration

---

daemon/launch_unix.go
launchers/launcher.go

This PR addresses issue #2565. This PR makes it so, when Pelican receives a SIGHUP, the process will restart.

Restart Pelican when SIGHUP is received

---

.github/workflows/enforce-issue-labelling.yml
.github/workflows/stale-issues.yml

This PR address issue #2551. This PR adds a Github action workflow to close stale issues. Issues are automatically marked with a `stale` label after 60 days of no activity. They can also be closed if it has been inactive for 30 days since being marked as stale.

Add work flow to close stale issues

---

broker/broker_test.go
registry/client_commands_test.go
registry/registry.go
registry/registry_db.go
registry/registry_db_server_test.go
registry/registry_db_test.go
registry/registry_ui.go
registry/registry_ui_test.go

This PR fixes the problems found by William in Pelican 7.19.0-rc.0 testing and other minor issues.
After the Registry ID Overhaul (#2483), a server could have more than one service (Origin/Cache). There are two ways to register a service on a server in the Registry: CLI auto-registration adn Registry WebUI.
When a request wants to register a new service (Origin/Cache) on an existing server, we need to verify they are allowed to do so by checking if they have the same public keys.
- For CLI auto-registration, we add an extra step: check if the signature they present can be verified by the existing server's keyset

Fix duplicate name handling in the registration process

---

docs/parameters.yaml
origin/advertise.go

Looking through various comments and past bugfixes, I'm really unsure what the guiding philosophy surrounding this header is supposed to be, and how that philosophy differs from the X-Pelican-Issuer header.
At a high level, there are issuers for a namespace and issuers for the Origin server itself, issuers for monitoring services and issuers for federation-related operations _at_ the Origin, but we've never formally explained how these interact, let alone the configuration mechanisms needed to cleanly split these as concepts. In any case, it seems like the token generation header should be using an issuer URL tied to the namespace itself.
This commit uses the first specified namespace issuer as the default issuer for clients to bootstrap tokens.

Use namespace prefix token issuer as X-Pelican-Token-Generation issuer

---

config/config.go
docs/parameters.yaml
launchers/cache_serve.go
metrics/xrdcl_curl_stats.go
metrics/xrootd_metrics.go
param/parameters.go
param/parameters_struct.go
xrootd/launch.go

This PR addresses issue #2596. This PR consumes metrics from the xrdcl-pelican. It creates a new routine to periodically gather the new statistics and then funnels them along into Prometheus metrics.

xrdcl-pelican metrics

---

systemd/examples/10-federation.yaml

We don't want it to override a valid Federation.DiscoveryUrl that was specified earlier in the config sequence, such as in `/usr/share/pelican/config.d`.

Comment out the Federation.DiscoveryUrl from `/etc/pelican/config.d/10-federation.yaml` from the `pelican-server` RPM

---

.github/workflows/release.yml

Current webhook toggle doesn't run because an action can't trigger another action. Update the release so that after the release is done we explicitly run the webhook.
Closes https://github.com/PelicanPlatform/pelican/issues/2631

Add push to release action

---

config/encrypted.go
config/encrypted_test.go
config/init_server_creds.go
origin/origin_db.go

- Update string encrypt/decrypt functions with NaCl's box pkg
- Record the id of the key used for encryption in the output string
- Iterate all valid issuer key to decrypt
- Enable support for key rotation and decryption of data encrypted with previous keys.
- To achieve this goal, GetSecret and key pair derivation functions now accept a specific issuer key as input
- No backward compatibility issue because the `EncryptString` and `DecryptString` are used for globus collection only, which is never in the prod. cc @whwjiang: This PR may have impact on your globus development.
- Replace the standard errors package with github.com/pkg/errors

Support multiple keys in string encrypt/decrypt functions

---

registry/registry.go

This method properly compares the cryptographic content rather than string representation, making the key comparison method in `matchKeys` function consistent with other parts of the codebase like:
* compareJwks() 
* checkNamespaceExistsHandler()
Also add extra debugging logs.
**Important Note** The current PR may not resolve the problem in the Github Issue, since I cannot reproduce this error in v7.16 with a similar setup (superspace "/foo" registered, try to register a new namespace "/foo/bar" with the same key) -> it works without the error. Nevertheless, this is my best shot at this time-sensitive moment. It at least implements the best practice for key comparison, and could provide more logs for debugging. Any wisdom would be appreciated!!

Use jwk.Equal() instead of JSON string comparison for super/sub spaces key matching

---

config/config.go

This PR changes the default monitoring interval from being interpreted as `60ns` to `60s`. 
Test to reproduce:
1. Enable the `Cache.EnableEvictionMonitoring`, do not set `Cache.EvictionMonitoringInterval`. 
2. Run `pelican config get Cache.EvictionMonitoringInterval`, this should report `1m0s` with this fix enabled. Without the fix it should report `60ns`
@turetske this needs to be patched into the 7.19.x series

Fix Cache eviction monitoring interval to be reasonable

---

database/collection.go
oa4mp/proxy.go
oa4mp/resources/policies.qdl
oa4mp/serve.go
web_ui/oauth2_client.go

This PR addresses issue #2617. This PR allows for an authorization template to use a database defined group as a requirement for access. This PR also allows the Origin's built-in issuer to issue tokens with the collections scopes.

Groups-Collections Authorization Integration

---

.github/workflows/pre-commit-linter.yml
.golangci.yaml
.pre-commit-config.yaml
config/resources/defaults.yaml
director/cache_ads.go
director/director_api.go
director/director_ui.go
director/maxmind.go
director/sort.go
director/sort_algorithms.go
director/sort_algorithms_test.go
director/sort_test.go
director/sort_utilities.go
director/sort_utilities_test.go
docs/parameters.yaml
fed_test_utils/fed.go
go.mod
go.sum
metrics/director.go
param/parameters.go
param/parameters_struct.go
server_structs/director.go

Notes for reviewers:
- I did my best to arrange the git history coherently to explain the various steps I took to undertake this overhaul. That being said, if you step through commit-by-commit there may be a few wonky artifacts that came from difficulties I had in splitting all the hunks the way I wanted (I got to know `git add -e` pretty well!). Each commit message tries to explain the broad intentions of that commit, so if you see unrelated stuff assume it's addressed in another commit.
- I'd advise reviewing the code starting from `sortServerAds` which acts as the entrypoint for all the sorting algorithms. For a given algorithm, step through the code to understand the steps that go into re-arranging the input server ads.
- This diff spans work from roughly two weeks, and I waffled a …

Overhaul the Director's sorting algorithms

---

docs/parameters.yaml

Closes #2673. Does what the title says.

Fix default Cache.ClientStatisticsLocation in docs

---

config/config.go
xrootd/xrootd_config.go

The crux of the issue was a conversion of Pelican log levels through logrus:
```
Warn --> (parse with Logrus) --> Warning --> apply default level on sub-systems
```
This meant that when you set `Logging.Level: Warn`, we'd parse the level and use the parsed level to set defaults for things like `Logging.Origin.Cms`.
However, when we mapped the derived default for `param.Logging_Origin_Cms` into xrootd config, the mapping failed because we didn't check for `warning`.
This fix is two-fold:
- first, I map "warning" back to "warn" when we're setting defaults for the subsystems.
- second, I modified the xrootd logging code to treat "warning" the same as "Warn"
Either of these fixes would solve the original bug, but I'm hoping that the application of both makes a future regression that much less …

Fix bug preventing Origins with `Logging.Level: Warn` from starting

---

github_scripts/osx_install.sh
images/Dockerfile

Simple version bump -- I successfully built the container locally from the repo root with:
```
docker build -t jhiemstra/pelican-test:latest -f images/Dockerfile --target origin .
```
When this is merged, I'll open a follow-up issue to switch this from a source build once it's been released through epel (which is not something we do in-house).

Bump xrootd-s3-http version

---

images/Dockerfile

Exactly what the PR's title says.
I tested this by building and running all eight server images, checking that they made it at least as far as executing the `pelican-server` binary.

Switch to installing the `pelican-server` binary in all server images
